### ISSUE TITLE
azure-arm EOF 

### ISSUE THREAD

**Issue by edikmkoyan** [hashicorp/packer#10018]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

packer 1.6.3 crashes on EOF returned by azure-arm. The same template works with packer 1.6.2. 

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `1.6.3`

### Operating system and Environment details

ubuntu 18.04, osx. 

### Log Fragments and crash.log files

: Packer build (Command Line) (3s)
[15:31:21]	[Step 3/3] Starting: /opt/buildAgent/temp/agentTmp/custom_script4288328277188383191
[15:31:21]	[Step 3/3] in directory: /opt/buildAgent/work/a31e233926cac46a
[15:31:23]	[Step 3/3] azure-arm: output will be in this color.
[15:31:23]	[Step 3/3] 
[15:31:23]	[Step 3/3] ==> azure-arm: Running builder ...
[15:31:23]	[Step 3/3] ==> azure-arm: Getting tokens using client secret
[15:31:23]	[Step 3/3] ==> azure-arm: Getting tokens using client secret
[15:31:24]	[Step 3/3]     azure-arm: Creating Azure Resource Manager (ARM) client ...
[15:31:24]	[Step 3/3] ==> azure-arm: WARNING: Zone resiliency may not be supported in West US, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/
[15:31:24]	[Step 3/3] Build 'azure-arm' errored after 972 milliseconds 491 microseconds: unexpected EOF
[15:31:24]	[Step 3/3] 
[15:31:24]	[Step 3/3] ==> Wait completed after 972 milliseconds 679 microseconds
[15:31:24]	[Step 3/3] 
[15:31:24]	[Step 3/3] ==> Some builds didn't complete successfully and had errors:
[15:31:24]	[Step 3/3] --> azure-arm: unexpected EOF
[15:31:24]	[Step 3/3] 
[15:31:24]	[Step 3/3] ==> Builds finished but no artifacts were created.
[15:31:24]	[Step 3/3] panic: interface conversion: interface {} is map[string]string, not map[string]*string
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: goroutine 21 [running]:
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/builder/azure/arm.(*StepCreateResourceGroup).Run(0xc0009ee660, 0x520d6c0, 0xc000794340, 0x520e300, 0xc001237860, 0xc001237860)
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/builder/azure/arm/step_create_resource_group.go:64 +0xa36
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc0009eeb10, 0x520d6c0, 0xc000794340, 0x520e300, 0xc001237860)
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/helper/multistep/basic_runner.go:67 +0x21c
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc000258000, 0x520d6c0, 0xc000794340, 0x5227f20, 0xc001237b00, 0x518eb00, 0xc0012768a0, 0x0, 0x0, 0x0, ...)
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/builder/azure/arm/builder.go:285 +0x15a2
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc00081e1c0, 0x1, 0xc0006806e0, 0x0, 0x0)
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/packer/rpc/builder.go:117 +0x1c4
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: reflect.Value.call(0xc0008142a0, 0xc000270078, 0x13, 0x4bd13c4, 0x4, 0xc00062cf08, 0x3, 0x3, 0x4d19078, 0xc00008e000, ...)
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/reflect/value.go:475 +0x8c7
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: reflect.Value.Call(0xc0008142a0, 0xc000270078, 0x13, 0xc000abaf08, 0x3, 0x3, 0xc000ae8eb8, 0xc0000c76d0, 0x4607c0)
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/reflect/value.go:336 +0xb9
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: net/rpc.(*service).call(0xc00081e200, 0xc000260050, 0xc00060a178, 0xc00060a180, 0xc000272180, 0xc00079a280, 0x3d82f60, 0xc0006806dc, 0x18a, 0x3c91be0, ...)
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x189
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: created by net/rpc.(*Server).ServeCodec
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x445
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 /usr/bin/packer: plugin process exited
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 [INFO] (telemetry) ending azure-arm
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 ui error: Build 'azure-arm' errored after 972 milliseconds 491 microseconds: unexpected EOF
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 ui: 
[15:31:24]	[Step 3/3] ==> Wait completed after 972 milliseconds 679 microseconds
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 machine readable: error-count []string{"1"}
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 ui error: 
[15:31:24]	[Step 3/3] ==> Some builds didn't complete successfully and had errors:
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 machine readable: azure-arm,error []string{"unexpected EOF"}
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 ui error: --> azure-arm: unexpected EOF
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 ui: 
[15:31:24]	[Step 3/3] ==> Builds finished but no artifacts were created.
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 [INFO] (telemetry) Finalizing.
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 waiting for all plugin processes to complete...
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 /usr/bin/packer: plugin process exited
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 /usr/bin/packer: plugin process exited
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 /usr/bin/packer: plugin process exited
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 /usr/bin/packer: plugin process exited
[15:31:24]	[Step 3/3] 2020/09/30 11:31:24 /usr/bin/packer: plugin process exited

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by braunsonm** [comment]
Closed via #10014 @nywilken

**Comment by nywilken** [comment]
Hi there thanks for reaching out. This is a duplicate of #10012 which has been fixed and set to be released shortly. I'm going to close this issue, but we are keeping the other issues open so that they can be tracked until the next release. Thanks again for reporting this issue.
