### ISSUE TITLE
When using qemu "disk_image: true", packer tries to open output file twice and fails

### ISSUE THREAD

**Issue by hills** [hashicorp/packer#10223]
#### Overview of the Issue

Qemu builder can specify that "iso_url" is a disk image not an ISO, but this functionality is now broken (previously it worked).

But when doing so, execution aborts with the error:
```
==> qemu: Error launching VM: Qemu failed to start. Please run with PACKER_LOG=1 to get more info.`
````

The crucial line from the log appears to be:
```
2020/11/05 15:41:36 packer-builder-qemu plugin: Executing /opt/vm/bin/qemu-system-x86_64: []string{"-vnc", "127.0.0.1:30", "-m", "192M", "-device", "virtio-net,netdev=user.0", "-drive", "file=test/packer-qemu,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-drive", "file=test/packer-qemu,if=virtio,cache=writeback,discard=ignore,format=qcow2", "-boot", "c", "-name", "packer-qemu", "-machine", "type=pc,accel=kvm", "-netdev", "user,id=user.0,hostfwd=tcp::3272-:22"}
2020/11/05 15:41:36 packer-builder-qemu plugin: Started Qemu. Pid: 25287
2020/11/05 15:41:36 packer-builder-qemu plugin: Qemu stderr: qemu-system-x86_64: -drive file=test/packer-qemu,if=virtio,cache=writeback,discard=ignore,format=qcow2: Failed to get "write" lock
2020/11/05 15:41:36 packer-builder-qemu plugin: Qemu stderr: Is another process using the image [test/packer-qemu]?
````

I suspect rationally it should not be requesting "-drive" on the same file, twice. One should probably be the backing file? 

#### Reproduction Steps

* Use this [example JSON](https://github.com/hashicorp/packer/files/5495355/test.json.txt)
* Swap "iso_url" for a path to a disk image
* `packer build test.json`

### Packer version

This bug report refers to v1.6.5.

I have used this functionality before; it works in v1.5.2. I haven't tested other versions.

### Simplified Packer Buildfile

Attached above in steps to reproduce.

### Operating system and Environment details

Linux, x86_64, glibc 2.23.

### Log Fragments and crash.log files

The relevant fragment is above; here's a [complete log](https://github.com/hashicorp/packer/files/5495395/packer.txt).

**Comment by nywilken** [comment]
Thanks for reaching out. We’ll take a look when we get a chance.

**Comment by muratmozdemir** [comment]
I'm having the same issue, you can workaround it by providing some qemu args:

`        "qemuargs": [
          ["-drive", "file=<YourImage>.qcow2,if=virtio,cache=writeback,discard=ignore,format=qcow2"]
        ]`

**Comment by hansgogia** [comment]
Along with this, when we don't set `"use_backing_file": true` it just fails with the error,

```
2020/11/26 13:00:09 packer-builder-qemu plugin: Qemu --version output: QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.8)
2020/11/26 13:00:09 packer-builder-qemu plugin: Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
2020/11/26 13:00:09 packer-builder-qemu plugin: Qemu version: 4.2.1
2020/11/26 13:00:09 ui: [1;32m==> qemu: Starting VM, booting disk imageESC[0m
2020/11/26 13:00:09 ui: ESC[0;32m    qemu: The VM will be run headless, without a GUI. If you want to
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: vnc://127.0.0.1:86ESC[0m
2020/11/26 13:00:09 packer-builder-qemu plugin: Qemu Builder has no floppy files, not attaching a floppy.
2020/11/26 13:00:09 packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:5986: use of closed network connection
2020/11/26 13:00:09 packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:3746: use of closed network connection
2020/11/26 13:00:09 packer-builder-qemu plugin: Deleting CD disk: /tmp/packer166843067.iso
2020/11/26 13:00:09 packer-builder-qemu plugin: panic: interface conversion: interface {} is nil, not []string
2020/11/26 13:00:09 packer-builder-qemu plugin:
2020/11/26 13:00:09 packer-builder-qemu plugin: goroutine 69 [running]:
2020/11/26 13:00:09 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).getDeviceAndDriveArgs(0xc0008ac640, 0xc000470e00, 0x535df40, 0xc000457290, 0x0, 0xc000072d00, 0x10, 0x0, 0x0, 0x0)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /home/circleci/project/packer/builder/qemu/step_run.go:219 +0x1b25
2020/11/26 13:00:09 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).getDefaultArgs(0xc0008ac640, 0xc000470e00, 0x535df40, 0xc000457290, 0x3)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /home/circleci/project/packer/builder/qemu/step_run.go:172 +0x8d7
2020/11/26 13:00:09 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).getCommandArgs(0xc0008ac640, 0xc000470e00, 0x535df40, 0xc000457290, 0x0, 0x0, 0xc000457298, 0xc0004572c0, 0x4d1addc)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /home/circleci/project/packer/builder/qemu/step_run.go:368 +0x4d
2020/11/26 13:00:09 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).Run(0xc0008ac640, 0x535d300, 0xc00045c180, 0x535df40, 0xc000457290, 0x0)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /home/circleci/project/packer/builder/qemu/step_run.go:47 +0x37b
2020/11/26 13:00:09 packer-builder-qemu plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc0004572f0, 0x535d300, 0xc00045c180, 0x535df40, 0xc000457290)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /home/circleci/project/packer/helper/multistep/basic_runner.go:70 +0x234
2020/11/26 13:00:09 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*Builder).Run(0xc000470e00, 0x535d300, 0xc00045c180, 0x53785e0, 0xc0004570e0, 0x52e9320, 0xc0008ac620, 0x0, 0xc0001bf5f8, 0xc000635bd0, ...)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /home/circleci/project/packer/builder/qemu/builder.go:158 +0x11a2
2020/11/26 13:00:09 packer-builder-qemu plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc00051cbc0, 0x1, 0xc0000726d0, 0x0, 0x0)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /home/circleci/project/packer/packer/rpc/builder.go:117 +0x1c4
2020/11/26 13:00:09 packer-builder-qemu plugin: reflect.Value.call(0xc0001bf5c0, 0xc00000e4d0, 0x13, 0x4d10ab6, 0x4, 0xc000635f08, 0x3, 0x3, 0x4e45cb8, 0xc000084800, ...)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /usr/local/go/src/reflect/value.go:475 +0x8c7
2020/11/26 13:00:09 packer-builder-qemu plugin: reflect.Value.Call(0xc0001bf5c0, 0xc00000e4d0, 0x13, 0xc000c83f08, 0x3, 0x3, 0xc000683938, 0xc000bfd190, 0x4609c0)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /usr/local/go/src/reflect/value.go:336 +0xb9
2020/11/26 13:00:09 packer-builder-qemu plugin: net/rpc.(*service).call(0xc00051cc00, 0xc00010c780, 0xc0004be5c8, 0xc0004be5d0, 0xc0001cd580, 0xc000204720, 0x3e8fda0, 0xc0000726bc, 0x18a, 0x3d92a80, ...)
2020/11/26 13:00:09 packer-builder-qemu plugin:         /usr/local/go/src/net/rpc/server.go:377 +0x189
2020/11/26 13:00:09 packer-builder-qemu plugin: created by net/rpc.(*Server).ServeCodec
2020/11/26 13:00:09 packer-builder-qemu plugin:         /usr/local/go/src/net/rpc/server.go:474 +0x445
2020/11/26 13:00:09 /usr/local/bin/packer: plugin process exited
2020/11/26 13:00:09 [INFO] (telemetry) ending qemu
2020/11/26 13:00:09 ui error: ESC[1;31mBuild 'qemu' errored after 4 seconds 54 milliseconds: unexpected EOFESC[0m
```

**Comment by serverwentdown** [comment]
https://github.com/hashicorp/packer/blob/fab442eb52de2821de68d7579d22a2f806e79fb1/builder/qemu/step_create_disk.go#L31-L33

I suspect that mismatch between two conditions will cause the state to contain the original disk image and also the run step to append the same. 
 https://github.com/hashicorp/packer/blob/196ac12d077f7c518beab5ab7c7c45526dd9fd3f/builder/qemu/step_run.go#L215-L217

I can attempt this.

**Comment by serverwentdown** [comment]
@hansgogia can you provide the exact configuration and packer version that causes your panic?
