### ISSUE TITLE
packer-builder-qemu panic when disk_image=true and source image has no file extension

### ISSUE THREAD

**Issue by ndimiduk** [hashicorp/packer#10226]
#### Overview of the Issue

`packer-builder-qemu` panic when `disk_image=true` and source image has no file extension

Per the title. The input disk image is generated from a previous `packer` invocation. Packer does not add a disk format extension to its output file. However, as input, it appears a file extension is used as the basis for some feature detection. When there's no extension at all, it panics.

#### Reproduction Steps

Create a QEMU source with `disk_image = true` and an `iso_url` pointed at a file without an extension.

### Packer version

```
$ packer version
Packer v1.6.4
```

### Operating system and Environment details

MacOS 10.15.7

### Log Fragments and crash.log files

```
==> Some builds didn't complete successfully and had errors:
--> qemu.cmvm: unexpected EOF

==> Builds finished but no artifacts were created.
2020/11/06 13:42:36 packer-builder-qemu plugin: panic: runtime error: slice bounds out of range [1:0]
2020/11/06 13:42:36 packer-builder-qemu plugin: 
2020/11/06 13:42:36 packer-builder-qemu plugin: goroutine 41 [running]:
2020/11/06 13:42:36 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepCopyDisk).Run(0xc000ce98c0, 0x8d1fea0, 0xc00066b340, 0x8d20aa0, 0xc000d635f0, 0x0)
2020/11/06 13:42:36 packer-builder-qemu plugin:         github.com/hashicorp/packer/builder/qemu/step_copy_disk.go:36 +0x850
2020/11/06 13:42:36 packer-builder-qemu plugin: github.com/hashicorp/packer/common.askStep.Run(0x8ce14e0, 0xc000ce98c0, 0x8d3a380, 0xc000d63440, 0x8d1fea0, 0xc00066b340, 0x8d20aa0, 0xc000d635f0, 0x8838558)
2020/11/06 13:42:36 packer-builder-qemu plugin:         github.com/hashicorp/packer/common/multistep_runner.go:109 +0x69
2020/11/06 13:42:36 packer-builder-qemu plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc000d63650, 0x8d1fea0, 0xc00066b340, 0x8d20aa0, 0xc000d635f0)
2020/11/06 13:42:36 packer-builder-qemu plugin:         github.com/hashicorp/packer/helper/multistep/basic_runner.go:67 +0x21c
2020/11/06 13:42:36 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*Builder).Run(0xc0005fdc00, 0x8d1fea0, 0xc00066b340, 0x8d3a380, 0xc000d63440, 0x8ca3200, 0xc000e67020, 0x43bcf65, 0xc0001421e0, 0xc0000aabd0, ...)
2020/11/06 13:42:36 packer-builder-qemu plugin:         github.com/hashicorp/packer/builder/qemu/builder.go:154 +0x1142
2020/11/06 13:42:36 packer-builder-qemu plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc000708200, 0x1, 0xc000135dc0, 0x0, 0x0)
2020/11/06 13:42:36 packer-builder-qemu plugin:         github.com/hashicorp/packer/packer/rpc/builder.go:117 +0x1c4
2020/11/06 13:42:36 packer-builder-qemu plugin: reflect.Value.call(0xc0005b0480, 0xc000624118, 0x13, 0x86f3ebd, 0x4, 0xc0000aaf08, 0x3, 0x3, 0x8838340, 0xc000089000, ...)
2020/11/06 13:42:36 packer-builder-qemu plugin:         reflect/value.go:475 +0x8c7
2020/11/06 13:42:36 packer-builder-qemu plugin: reflect.Value.Call(0xc0005b0480, 0xc000624118, 0x13, 0xc000d0e708, 0x3, 0x3, 0xc00072d338, 0xc0006d6dd0, 0x40650a0)
2020/11/06 13:42:36 packer-builder-qemu plugin:         reflect/value.go:336 +0xb9
2020/11/06 13:42:36 packer-builder-qemu plugin: net/rpc.(*service).call(0xc000708240, 0xc0001500a0, 0xc000580310, 0xc000580320, 0xc0003ec200, 0xc00000ec60, 0x78bbc00, 0xc000135aec, 0x18a, 0x77cb860, ...)
2020/11/06 13:42:36 packer-builder-qemu plugin:         net/rpc/server.go:377 +0x189
2020/11/06 13:42:36 packer-builder-qemu plugin: created by net/rpc.(*Server).ServeCodec
2020/11/06 13:42:36 packer-builder-qemu plugin:         net/rpc/server.go:474 +0x445
```

**Comment by SwampDragons** [comment]
Thanks for reporting this regression; we'll try to get it fixed before the next release.

**Comment by waremal** [comment]
Source of the error: https://github.com/hashicorp/packer/blob/fab442eb52de2821de68d7579d22a2f806e79fb1/builder/qemu/step_copy_disk.go#L36

**Comment by ndimiduk** [comment]
🎉
