### ISSUE TITLE
googlecompute: unexpected EOF

### ISSUE THREAD

**Issue by jimdigriz** [hashicorp/packer#10262]
#### Overview of the Issue

Since packer 1.6.5 (version 1.6.4 works fine) `packer` explodes with:

```
googlecompute: unexpected EOF
```

#### Reproduction Steps

...let me know if you need to look at my `packer.json`, but this looks like a problem in talking to GCP rather than something in my `packer.json`, especially as earlier versions work fine.

```
env TMPDIR=/home/alex/src/adloox/pubint /home/alex/src/adloox/pubint/packer build -on-error=ask -only googlecompute -var PACKER_LOG=1 packer.json
```

### Packer version

1.6.5, version 1.6.4 and earlier work fine.

### Operating system and Environment details

Debian 'buster' 10.

### Log Fragments and crash.log files

```
2020/11/16 11:36:52 [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 Deleting kv.Value: 
2020/11/16 11:36:52 Deleting kv.Value: 
2020/11/16 11:36:52 Deleting kv.Value: 
2020/11/16 11:36:52 Deleting kv.Value: 
2020/11/16 11:36:52 Deleting kv.Value: 
2020/11/16 11:36:52 Deleting kv.Value: 
2020/11/16 11:36:52 Deleting kv.Value: 
2020/11/16 11:36:52 Deleting kv.Value: 1
2020/11/16 11:36:52 Deleting kv.Value: pubint
2020/11/16 11:36:52 Deleting kv.Value: europe-west4-c
2020/11/16 11:36:52 Deleting kv.Value: pubint
2020/11/16 11:36:52 Deleting kv.Value: adloox
2020/11/16 11:36:52 Creating plugin client for path: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 Starting plugin: /home/alex/src/adloox/pubint/packer []string{"/home/alex/src/adloox/pubint/packer", "plugin", "packer-builder-googlecompute"}
2020/11/16 11:36:52 Waiting for RPC address for: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 packer-builder-googlecompute plugin: [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 packer-builder-googlecompute plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 packer-builder-googlecompute plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 packer-builder-googlecompute plugin: Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-builder-googlecompute plugin: [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-builder-googlecompute plugin: Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 packer-builder-googlecompute plugin: args: []string{"packer-builder-googlecompute"}
2020/11/16 11:36:52 packer-builder-googlecompute plugin: Plugin address: unix /home/alex/src/adloox/pubint/packer-plugin229734797
2020/11/16 11:36:52 packer-builder-googlecompute plugin: Waiting for connection...
2020/11/16 11:36:52 Received unix RPC address for /home/alex/src/adloox/pubint/packer: addr is /home/alex/src/adloox/pubint/packer-plugin229734797
2020/11/16 11:36:52 packer-builder-googlecompute plugin: Serving a plugin connection...
2020/11/16 11:36:52 Creating plugin client for path: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 Starting plugin: /home/alex/src/adloox/pubint/packer []string{"/home/alex/src/adloox/pubint/packer", "plugin", "packer-provisioner-shell-local"}
2020/11/16 11:36:52 Waiting for RPC address for: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: args: []string{"packer-provisioner-shell-local"}
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Plugin address: unix /home/alex/src/adloox/pubint/packer-plugin686253030
2020/11/16 11:36:52 Received unix RPC address for /home/alex/src/adloox/pubint/packer: addr is /home/alex/src/adloox/pubint/packer-plugin686253030
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Waiting for connection...
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Serving a plugin connection...
2020/11/16 11:36:52 Creating plugin client for path: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 Starting plugin: /home/alex/src/adloox/pubint/packer []string{"/home/alex/src/adloox/pubint/packer", "plugin", "packer-provisioner-file"}
2020/11/16 11:36:52 Waiting for RPC address for: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 packer-provisioner-file plugin: [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 packer-provisioner-file plugin: Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-file plugin: Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/11/16 11:36:52 packer-provisioner-file plugin: Plugin address: unix /home/alex/src/adloox/pubint/packer-plugin427390873
2020/11/16 11:36:52 Received unix RPC address for /home/alex/src/adloox/pubint/packer: addr is /home/alex/src/adloox/pubint/packer-plugin427390873
2020/11/16 11:36:52 packer-provisioner-file plugin: Waiting for connection...
2020/11/16 11:36:52 packer-provisioner-file plugin: Serving a plugin connection...
2020/11/16 11:36:52 Creating plugin client for path: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 Starting plugin: /home/alex/src/adloox/pubint/packer []string{"/home/alex/src/adloox/pubint/packer", "plugin", "packer-provisioner-shell-local"}
2020/11/16 11:36:52 Waiting for RPC address for: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: args: []string{"packer-provisioner-shell-local"}
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Plugin address: unix /home/alex/src/adloox/pubint/packer-plugin323821693
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Waiting for connection...
2020/11/16 11:36:52 Received unix RPC address for /home/alex/src/adloox/pubint/packer: addr is /home/alex/src/adloox/pubint/packer-plugin323821693
2020/11/16 11:36:52 packer-provisioner-shell-local plugin: Serving a plugin connection...
2020/11/16 11:36:52 Creating plugin client for path: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 Starting plugin: /home/alex/src/adloox/pubint/packer []string{"/home/alex/src/adloox/pubint/packer", "plugin", "packer-provisioner-shell"}
2020/11/16 11:36:52 Waiting for RPC address for: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 packer-provisioner-shell plugin: [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 packer-provisioner-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 packer-provisioner-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 packer-provisioner-shell plugin: Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell plugin: Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2020/11/16 11:36:52 packer-provisioner-shell plugin: Plugin address: unix /home/alex/src/adloox/pubint/packer-plugin873063680
2020/11/16 11:36:52 Received unix RPC address for /home/alex/src/adloox/pubint/packer: addr is /home/alex/src/adloox/pubint/packer-plugin873063680
2020/11/16 11:36:52 packer-provisioner-shell plugin: Waiting for connection...
2020/11/16 11:36:52 packer-provisioner-shell plugin: Serving a plugin connection...
2020/11/16 11:36:52 Creating plugin client for path: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 Starting plugin: /home/alex/src/adloox/pubint/packer []string{"/home/alex/src/adloox/pubint/packer", "plugin", "packer-provisioner-shell"}
2020/11/16 11:36:52 Waiting for RPC address for: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 packer-provisioner-shell plugin: [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 packer-provisioner-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 packer-provisioner-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 packer-provisioner-shell plugin: Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell plugin: Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2020/11/16 11:36:52 packer-provisioner-shell plugin: Plugin address: unix /home/alex/src/adloox/pubint/packer-plugin852455556
2020/11/16 11:36:52 packer-provisioner-shell plugin: Waiting for connection...
2020/11/16 11:36:52 Received unix RPC address for /home/alex/src/adloox/pubint/packer: addr is /home/alex/src/adloox/pubint/packer-plugin852455556
2020/11/16 11:36:52 packer-provisioner-shell plugin: Serving a plugin connection...
2020/11/16 11:36:52 Creating plugin client for path: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 Starting plugin: /home/alex/src/adloox/pubint/packer []string{"/home/alex/src/adloox/pubint/packer", "plugin", "packer-provisioner-shell"}
2020/11/16 11:36:52 Waiting for RPC address for: /home/alex/src/adloox/pubint/packer
2020/11/16 11:36:52 packer-provisioner-shell plugin: [INFO] Packer version: 1.6.5 [go1.15.3 linux amd64]
2020/11/16 11:36:52 packer-provisioner-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/11/16 11:36:52 packer-provisioner-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/11/16 11:36:52 packer-provisioner-shell plugin: Attempting to open config file: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell plugin: [WARN] Config file doesn't exist: /home/alex/.packerconfig
2020/11/16 11:36:52 packer-provisioner-shell plugin: Setting cache directory: /home/alex/src/adloox/pubint/packer_cache
2020/11/16 11:36:52 packer-provisioner-shell plugin: args: []string{"packer-provisioner-shell"}
2020/11/16 11:36:52 packer-provisioner-shell plugin: Plugin address: unix /home/alex/src/adloox/pubint/packer-plugin418270650
2020/11/16 11:36:52 packer-provisioner-shell plugin: Waiting for connection...
2020/11/16 11:36:52 Received unix RPC address for /home/alex/src/adloox/pubint/packer: addr is /home/alex/src/adloox/pubint/packer-plugin418270650
2020/11/16 11:36:52 packer-provisioner-shell plugin: Serving a plugin connection...
2020/11/16 11:36:52 Preparing build: googlecompute
2020/11/16 11:36:52 ui: [1;32mgooglecompute: output will be in this color.[0m
2020/11/16 11:36:52 ui: 
2020/11/16 11:36:52 Build debug mode: false
2020/11/16 11:36:52 Force build: false
2020/11/16 11:36:52 On error: ask
2020/11/16 11:36:52 Waiting on builds to complete...
2020/11/16 11:36:52 Starting build run: googlecompute
2020/11/16 11:36:52 Running builder: googlecompute
2020/11/16 11:36:52 [INFO] (telemetry) Starting builder googlecompute
2020/11/16 11:36:52 packer-builder-googlecompute plugin: [INFO] Requesting Google token via GCE API Default Client Token Source...
2020/11/16 11:36:52 packer-builder-googlecompute plugin: [INFO] Instantiating GCE client...
2020/11/16 11:36:52 packer-builder-googlecompute plugin: [INFO] Instantiating OS Login client...
2020/11/16 11:36:52 ui: [1;32m==> googlecompute: Checking image does not exist...[0m
2020/11/16 11:36:53 ui: [1;32m==> googlecompute: Creating temporary rsa SSH key for instance...[0m
2020/11/16 11:36:54 packer-builder-googlecompute plugin: panic: runtime error: invalid memory address or nil pointer dereference
2020/11/16 11:36:54 packer-builder-googlecompute plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x155d746]
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 
2020/11/16 11:36:54 packer-builder-googlecompute plugin: goroutine 66 [running]:
2020/11/16 11:36:54 packer-builder-googlecompute plugin: github.com/hashicorp/packer/common.askStep.Run(0x0, 0x0, 0x53785e0, 0xc0005d2690, 0x535d300, 0xc000972c40, 0x535df40, 0xc0005d2930, 0x4e45de0)
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/home/circleci/project/packer/common/multistep_runner.go:109 +0x26
2020/11/16 11:36:54 packer-builder-googlecompute plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc0005d29c0, 0x535d300, 0xc000972c40, 0x535df40, 0xc0005d2930)
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/home/circleci/project/packer/helper/multistep/basic_runner.go:70 +0x234
2020/11/16 11:36:54 packer-builder-googlecompute plugin: github.com/hashicorp/packer/builder/googlecompute.(*Builder).Run(0xc00043aa00, 0x535d300, 0xc000972c40, 0x53785e0, 0xc0005d2690, 0x52e9320, 0xc00011ebc0, 0x0, 0xc0000ba818, 0xc000131bd0, ...)
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/home/circleci/project/packer/builder/googlecompute/builder.go:110 +0xc42
2020/11/16 11:36:54 packer-builder-googlecompute plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc00013c080, 0x1, 0xc00052c710, 0x0, 0x0)
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/home/circleci/project/packer/packer/rpc/builder.go:117 +0x1c4
2020/11/16 11:36:54 packer-builder-googlecompute plugin: reflect.Value.call(0xc0000ba7e0, 0xc00000e300, 0x13, 0x4d10ab6, 0x4, 0xc000131f08, 0x3, 0x3, 0x4e45cb8, 0xc000082000, ...)
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/usr/local/go/src/reflect/value.go:475 +0x8c7
2020/11/16 11:36:54 packer-builder-googlecompute plugin: reflect.Value.Call(0xc0000ba7e0, 0xc00000e300, 0x13, 0xc000aea708, 0x3, 0x3, 0xc000682738, 0xc000180470, 0x4609c0)
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/usr/local/go/src/reflect/value.go:336 +0xb9
2020/11/16 11:36:54 packer-builder-googlecompute plugin: net/rpc.(*service).call(0xc00013c0c0, 0xc00022a0a0, 0xc000204670, 0xc0002046c0, 0xc000222680, 0xc00019e3e0, 0x3e8fda0, 0xc00052c6dc, 0x18a, 0x3d92a80, ...)
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x189
2020/11/16 11:36:54 packer-builder-googlecompute plugin: created by net/rpc.(*Server).ServeCodec
2020/11/16 11:36:54 packer-builder-googlecompute plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x445
2020/11/16 11:36:54 /home/alex/src/adloox/pubint/packer: plugin process exited
2020/11/16 11:36:54 [INFO] (telemetry) ending googlecompute
2020/11/16 11:36:54 ui error: [1;31mBuild 'googlecompute' errored after 1 second 679 milliseconds: unexpected EOF[0m
2020/11/16 11:36:54 ui: 
==> Wait completed after 1 second 679 milliseconds
2020/11/16 11:36:54 machine readable: error-count []string{"1"}
2020/11/16 11:36:54 ui error: 
==> Some builds didn't complete successfully and had errors:
2020/11/16 11:36:54 machine readable: googlecompute,error []string{"unexpected EOF"}
2020/11/16 11:36:54 ui error: --> googlecompute: unexpected EOF
2020/11/16 11:36:54 ui: 
==> Builds finished but no artifacts were created.
2020/11/16 11:36:54 [INFO] (telemetry) Finalizing.
2020/11/16 11:36:54 waiting for all plugin processes to complete...
2020/11/16 11:36:54 /home/alex/src/adloox/pubint/packer: plugin process exited
2020/11/16 11:36:54 /home/alex/src/adloox/pubint/packer: plugin process exited
2020/11/16 11:36:54 /home/alex/src/adloox/pubint/packer: plugin process exited
2020/11/16 11:36:54 /home/alex/src/adloox/pubint/packer: plugin process exited
2020/11/16 11:36:54 /home/alex/src/adloox/pubint/packer: plugin process exited
2020/11/16 11:36:54 /home/alex/src/adloox/pubint/packer: plugin process exited
```

**Comment by azr** [comment]
Hello @jimdigriz thanks for opening and sorry about that one ! I think it was fixed by #10241 and you can find binaries for the fix here: https://app.circleci.com/pipelines/github/hashicorp/packer/7942/workflows/fb3d26dc-f092-46c7-882a-3ef62d5d8288/jobs/92013/artifacts can you please tell me if that fixes this one for you ? Thanks !

**Comment by jimdigriz** [comment]
I did look for something similar, looks like `unexpected EOF` was not in #10241 so I missed it, sorry for the dupe.

I cannot test the binaries unfortunately, CircleCI thinks it is fair to ask for 'This application will be able to read and write all public and private repository data' which is a bit rude and not really something I am keen to do.

Guess I'll wait for 1.6.6?

**Comment by nywilken** [comment]
Hi @jimdigriz just want to follow up with @azr comment. The fix in #10241 should fix this issue, and will be made available for use in the next [nightly](https://github.com/hashicorp/packer/releases/tag/nightly). To be released tomorrow so no need to wait until v1.6.6 if you are okay running a nightly version.

**Comment by azr** [comment]
Hey @jimdigriz, no worries. Yup I understand your concern here ! I think circle needs that to be able to write ci status to commits. Which you're not going to use :D. Here's a copy paste of the urls that could use to download these files using incognito mode.

https://92013-8966356-gh.circle-artifacts.com/0/packer_windows_amd64.zip
https://92013-8966356-gh.circle-artifacts.com/0/packer_solaris_amd64.zip
https://92013-8966356-gh.circle-artifacts.com/0/packer_darwin_amd64.zip
https://92013-8966356-gh.circle-artifacts.com/0/packer_openbsd_amd64.zip
https://92013-8966356-gh.circle-artifacts.com/0/packer_linux_amd64.zip
https://92013-8966356-gh.circle-artifacts.com/0/packer_freebsd_amd64.zip

Also you could wait for the nightly, yup !

**Comment by jimdigriz** [comment]
I grabbed https://92013-8966356-gh.circle-artifacts.com/0/packer_linux_amd64.zip (identifies interestingly as 1.6.4) and can confirm it works for me.

**Comment by azr** [comment]
Super cool ! In the meantime the nightly was released ! The next release is going to contain @nywilken's fix ! 🙂 .

**Comment by jimdigriz** [comment]
Thanks all for being really responsive and helpful. Have a great week!

**Comment by nywilken** [comment]
Thanks for letting us know the fix resolves the problem. I'm going to close this as it has been resolved.
