### ISSUE TITLE
packer-builder-qemu panic when booting from a qcow2 file

### ISSUE THREAD

**Issue by ndimiduk** [hashicorp/packer#10356]
#### Overview of the Issue

`packer-builder-qemu` panic when booting from a qcow2 file. `disk_image = true`, `format = "qcow2"`, `iso_urls = [ "path/to/baseimage.qcow2" ]`.

#### Reproduction Steps

It reproduces reliably with this project. I'm not sure which settings are resulting in the issue.

### Packer version

```sh
$ packer version
Packer v1.6.5
```

### Simplified Packer Buildfile

```
source "qemu" "centos7" {
  disk_compression = "${var.disk_compression}"
  disk_image = true
  disk_size = "${var.disk_size}"
  format = "${local.format}"
  iso_checksum = "${var.iso_checksum_type}:${var.iso_checksum}"
  iso_urls = [
    "${var.iso_path}/${var.iso_name}",
  ]
}

locals {
  format = "qcow2"
}
```

### Operating system and Environment details

macOS 10.15.7

### Log Fragments and crash.log files

```
==> Builds finished but no artifacts were created. 
2020/12/07 16:45:11 packer-builder-qemu plugin: panic: interface conversion: interface {} is nil, not []string
2020/12/07 16:45:11 packer-builder-qemu plugin: 
2020/12/07 16:45:11 packer-builder-qemu plugin: goroutine 110 [running]:
2020/12/07 16:45:11 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).getDeviceAndDriveArgs(0xc0001281e0, 0xc0006e6300, 0x8e6a9c0, 0xc00039a540, 0xc0000eeb08, 0xc000b7ed00,
 0x5, 0x0, 0x0, 0x0)
2020/12/07 16:45:11 packer-builder-qemu plugin:         github.com/hashicorp/packer/builder/qemu/step_run.go:219 +0x1b25
2020/12/07 16:45:11 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).getDefaultArgs(0xc0001281e0, 0xc0006e6300, 0x8e6a9c0, 0xc00039a540, 0x3)
2020/12/07 16:45:11 packer-builder-qemu plugin:         github.com/hashicorp/packer/builder/qemu/step_run.go:172 +0x8d7
2020/12/07 16:45:11 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).getCommandArgs(0xc0001281e0, 0xc0006e6300, 0x8e6a9c0, 0xc00039a540, 0x0, 0x0, 0xc00039a548, 0xc00039a5
70, 0x88381dd)
2020/12/07 16:45:11 packer-builder-qemu plugin:         github.com/hashicorp/packer/builder/qemu/step_run.go:368 +0x4d
2020/12/07 16:45:11 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*stepRun).Run(0xc0001281e0, 0x8e69dc0, 0xc00039c080, 0x8e6a9c0, 0xc00039a540, 0x0)
2020/12/07 16:45:11 packer-builder-qemu plugin:         github.com/hashicorp/packer/builder/qemu/step_run.go:47 +0x37b
2020/12/07 16:45:11 packer-builder-qemu plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc00039a5a0, 0x8e69dc0, 0xc00039c080, 0x8e6a9c0, 0xc00039a540)
2020/12/07 16:45:11 packer-builder-qemu plugin:         github.com/hashicorp/packer/helper/multistep/basic_runner.go:70 +0x234
2020/12/07 16:45:11 packer-builder-qemu plugin: github.com/hashicorp/packer/builder/qemu.(*Builder).Run(0xc0006e6300, 0x8e69dc0, 0xc00039c080, 0x8e84cc0, 0xc00039a300, 0x8df7f40, 0xc0001281c0, 0x0, 0xc0
000c74d8, 0xc0003a2bd0, ...)
2020/12/07 16:45:11 packer-builder-qemu plugin:         github.com/hashicorp/packer/builder/qemu/builder.go:158 +0x11a2
2020/12/07 16:45:11 packer-builder-qemu plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc00055cc00, 0x1, 0xc00004c020, 0x0, 0x0)
2020/12/07 16:45:11 packer-builder-qemu plugin:         github.com/hashicorp/packer/packer/rpc/builder.go:117 +0x1c4
2020/12/07 16:45:11 packer-builder-qemu plugin: reflect.Value.call(0xc0000c74a0, 0xc000010590, 0x13, 0x882dfcc, 0x4, 0xc0003a2f08, 0x3, 0x3, 0x0, 0x0, ...)
2020/12/07 16:45:11 packer-builder-qemu plugin:         reflect/value.go:475 +0x8c7
2020/12/07 16:45:11 packer-builder-qemu plugin: reflect.Value.Call(0xc0000c74a0, 0xc000010590, 0x13, 0xc000394f08, 0x3, 0x3, 0x0, 0x0, 0x0)
2020/12/07 16:45:11 packer-builder-qemu plugin:         reflect/value.go:336 +0xb9
2020/12/07 16:45:11 packer-builder-qemu plugin: net/rpc.(*service).call(0xc00055cc40, 0xc0000d0550, 0xc000546610, 0xc000546630, 0xc0000d3500, 0xc000299e00, 0x79c3e00, 0xc00004c01c, 0x18a, 0x78c7b00, ...
)
2020/12/07 16:45:11 packer-builder-qemu plugin:         net/rpc/server.go:377 +0x189
2020/12/07 16:45:11 packer-builder-qemu plugin: created by net/rpc.(*Server).ServeCodec
2020/12/07 16:45:11 packer-builder-qemu plugin:         net/rpc/server.go:474 +0x445
2020/12/07 16:45:11 [INFO] (telemetry) ending
```

**Comment by nywilken** [comment]
Hello :wave: thanks for reporting, this should be fixed by #10249. The fix is slated for the next upcoming release but it is available for use in the latest Packer [nightly release](https://github.com/hashicorp/packer/releases/tag/nightly). 

Can you please test with the nightly release and let us know if it resolves your issue, please.

**Comment by ndimiduk** [comment]
Yes, this bug seems to be resolved when using the nightly. Thank you!

**Comment by nywilken** [comment]
Great, thank for testing. I'm going to mark this issue as resolved since the fix has been merged. Cheers!
