### ISSUE TITLE
packer hcl2_upgrade: panic: must not call ListVal with empty slice

### ISSUE THREAD

**Issue by bbros-dev** [hashicorp/packer#10673]
#### Overview of the Issue

Packer crash on trying to convert JSON to HCL2:
```bash
$ packer hcl2_upgrade ubuntu-18.04-chef0-development-amd64-vars-commented.json
```

#### Reproduction Steps

JSON file:

```bash
{
"variables": {
    "_comment": "Built with $(packer build -var-file=${PWD}/packer/ubuntu-18.04-chef0-amd64-vars-uncommented.json ${PWD}/packer/ubuntu/ubuntu-18.04-chef0-amd64-uncommented.json)",
  "chefdk_sha256": "2f27da230b6a0f2cc3772f8c831e1e8beb0e5b3c334f87388f571bb12aef7788",
  "chefdk_version": "4.8.23",
  "_comment2": "One of: d, p, t, s.",
  "environment": "d",
  "primary_dc": "dc68",
  "release_version": "0.4.0",
  "ruby_path_version": "2.6.0"
 }
}
```

### Packer version

 ```bash
$ packer version
Packer v1.7.01.7.0
```

### Simplified Packer Buildfile

See JSON file above.

### Operating system and Environment details

```bash
$ uname -a
Linux desktop.local.lan 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments and crash.log files

User name redacted: `<>`

```bash
$ cat crash.log
2021/02/21 14:12:53 [INFO] Packer version: 1.7.0 [go1.15.8 linux amd64]
2021/02/21 14:12:53 [TRACE] discovering plugins in /usr/local/bin/packer-1.7.0
2021/02/21 14:12:53 [TRACE] discovering plugins in /home/<>/.packer.d/plugins
2021/02/21 14:12:53 [DEBUG] Discovered plugin: upcloud = /home/<>/.packer.d/plugins/packer-builder-upcloud
2021/02/21 14:12:53 [DEBUG] Discovered plugin: vultr = /home/<>/.packer.d/plugins/packer-builder-vultr
2021/02/21 14:12:53 [INFO] using external builders: [upcloud vultr]
2021/02/21 14:12:53 [TRACE] discovering plugins in .
2021/02/21 14:12:53 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/02/21 14:12:53 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/<>/.packerconfig
2021/02/21 14:12:53 [WARN] Config file doesn't exist: /home/<>/.packerconfig
2021/02/21 14:12:53 [INFO] Setting cache directory: /home/<>/src/kfchub.tf/packer/packer_cache
2021/02/21 14:12:53 ui error: Ignoring following initialization error: 1 error occurred:
	* at least one builder must be defined

2021/02/21 14:12:53 waiting for all plugin processes to complete...
panic: must not call ListVal with empty slice

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.ListVal(0x7f52ad8, 0x0, 0x0, 0x7f52ad8, 0x0, 0xc0005a8e40, 0xc0005a8de0)
	/home/circleci/go/pkg/mod/github.com/zclconf/go-cty@v1.7.0/cty/value_init.go:157 +0x465
github.com/hashicorp/packer-plugin-sdk/hcl2helper.HCL2ValueFromConfigValue(0x3ef9780, 0xc0003b4100, 0x0, 0xc0003b4100, 0xc00000e360, 0xc0008af920)
	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.0.14/hcl2helper/values.go:50 +0x205
github.com/hashicorp/packer/command.(*BuildParser).Parse(0xc00061b080, 0xc0006f6210, 0x0, 0x0)
	/home/circleci/project/packer/command/hcl2_upgrade.go:910 +0x2ab
github.com/hashicorp/packer/command.(*HCL2UpgradeCommand).RunContext(0xc00060f680, 0x54f7600, 0xc0006101c0, 0xc000140900, 0x0)
	/home/circleci/project/packer/command/hcl2_upgrade.go:222 +0x7a6
github.com/hashicorp/packer/command.(*HCL2UpgradeCommand).Run(0xc00060f680, 0xc000106170, 0x1, 0x1, 0x0)
	/home/circleci/project/packer/command/hcl2_upgrade.go:38 +0xff
github.com/mitchellh/cli.(*CLI).Run(0xc0000ce640, 0xc0000ce640, 0x1, 0x1)
	/home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x1cf
main.wrappedMain(0x0)
	/home/circleci/project/packer/main.go:245 +0x812
main.realMain(0x0)
	/home/circleci/project/packer/main.go:49 +0x105
main.main()
	/home/circleci/project/packer/main.go:35 +0x25

```

**Comment by sylviamoss** [comment]
Hey there, thanks for reaching out! 
Just to make sure I got this right - you were trying to upgrade a variables file, right? 
This panics when it looks for the rest of the template and it can't find any builder. It is supposed to work for complete templates only but that's not explicitly documented. 

I won't tag this issue as documentation bug because I'd like it to work as expected. Thanks again for reporting, we will try to work on this for the next release.

**Comment by bbros-dev** [comment]
Thanks for the prompt response.

>  you were trying to upgrade a variables file, right?

Correct.
