### ISSUE TITLE
packer crashes with shell provisioner pause_before option

### ISSUE THREAD

**Issue by kovalromank** [hashicorp/packer#10975]
#### Overview of the Issue

When setting the `pause_before` option of the shell provisioner packer crashes.

#### Reproduction Steps

Using the sample configuration (sample.pkr.hcl) below and running 

`packer build sample.pkr.hcl`

 crashes with a runtime error: invalid memory address or nil pointer dereference

Simply commenting out the line `pause_before = 5` stops packer from crashing.

### Packer version

v1.7.2

### Simplified Packer Buildfile

```hcl
variable do_token {
  sensitive = true
  default = "${env("DO_TOKEN")}"
}

source digitalocean sample {
  api_token = var.do_token

  image = "debian-10-x64"
  region = "tor1"
  size = "s-1vcpu-1gb"
  snapshot_name = format("sample-%s", formatdate("YYYYMMDDhhmm", timestamp()))

  ssh_username = "root"
}

build {
  name = "bot"

  sources = [
    "source.digitalocean.sample",
  ]

  provisioner shell {
    pause_before = "5"
    inline = ["cloud-init status --wait"]
  }
}
```

### Operating system and Environment details

Output of `go env`:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/romankoval/go/bin"
GOCACHE="/Users/romankoval/Library/Caches/go-build"
GOENV="/Users/romankoval/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/romankoval/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/romankoval/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ry/80sdld5d1yqbsk9lgg04n84r0000gn/T/go-build3800929814=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Log Fragments and crash.log files

Packer crash.log with PACKER_LOG=1 set:

```log
2021/04/23 13:58:12 [INFO] Packer version: 1.7.2 [go1.16.3 darwin amd64]
2021/04/23 13:58:12 [TRACE] discovering plugins in /usr/local/bin
2021/04/23 13:58:12 [TRACE] discovering plugins in /Users/romankoval/.packer.d/plugins
2021/04/23 13:58:12 [TRACE] discovering plugins in .
2021/04/23 13:58:12 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/04/23 13:58:12 [INFO] PACKER_CONFIG env var set; attempting to open config file: /Users/romankoval/.packerconfig
2021/04/23 13:58:12 [WARN] Config file doesn't exist: /Users/romankoval/.packerconfig
2021/04/23 13:58:12 [INFO] Setting cache directory: /Users/romankoval/Projects/Crypto/<redacted>/builder/packer_cache
2021/04/23 13:58:12 [TRACE] validateValue: not active for do_token, so skipping
2021/04/23 13:58:12 waiting for all plugin processes to complete...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x495cfe9]

goroutine 1 [running]:
github.com/hashicorp/packer/hcl2template.(*PackerConfig).initializeBlocks(0xc0005fcb40, 0xc0000104d8, 0x1, 0xc0000104c8)
	github.com/hashicorp/packer/hcl2template/plugin.go:156 +0xbc9
github.com/hashicorp/packer/hcl2template.(*PackerConfig).Initialize(0xc0005fcb40, 0xc000317400, 0x8f8b6f8, 0xc0005fcb40, 0x0)
	github.com/hashicorp/packer/hcl2template/parser.go:328 +0x536
github.com/hashicorp/packer/command.(*BuildCommand).RunContext(0xc000a941b0, 0x8f73780, 0xc0007b83c0, 0xc000317440, 0xc000317440)
	github.com/hashicorp/packer/command/build.go:152 +0x8b
github.com/hashicorp/packer/command.(*BuildCommand).Run(0xc000a941b0, 0xc0001a2020, 0x2, 0x2, 0x0)
	github.com/hashicorp/packer/command/build.go:40 +0xff
github.com/mitchellh/cli.(*CLI).Run(0xc00041b7c0, 0xc00041b7c0, 0x1, 0x1)
	github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x41a
main.wrappedMain(0x0)
	github.com/hashicorp/packer/main.go:262 +0x872
main.realMain(0x0)
	github.com/hashicorp/packer/main.go:49 +0x105
main.main()
	github.com/hashicorp/packer/main.go:35 +0x25
```

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out! Packer should definitely never crash. I can reproduce, and I'll try to make sure that initializing fails elegantly instead of crashing. 

In the meantime, you can get un-stuck by adding units to the duration string.("5s" for seconds, "5m" for minutes)

```hcl
  provisioner shell {
    pause_before = "5s"
...
}
```
