### ISSUE TITLE
Timeout when using chef-solo provisioner

### ISSUE THREAD

**Issue by rexcsn** [hashicorp/packer#11015]
Hi,

Using `Packer v1.7.2` and  Chef/CINC client `v16.13.16`

We are experiencing an issue with `amazon-ebs` builder. We have a long running `chef-solo` provisioner step, but the step constantly times out after 1 hour:
```
[2021-05-13T05:30:58.185Z]     ubuntu1804:   * remote_file[/opt/parallelcluster/sources/torque-6.1.2.tar.gz] action create
[2021-05-13T05:30:58.185Z]     ubuntu1804:     - create new file /opt/parallelcluster/sources/torque-6.1.2.tar.gz
[2021-05-13T05:30:58.185Z]     ubuntu1804:     - update content in file /opt/parallelcluster/sources/torque-6.1.2.tar.gz from none to bdef1d
[2021-05-13T05:30:58.185Z]     ubuntu1804:     (new content is binary, diff output suppressed)
[2021-05-13T05:30:58.185Z]     ubuntu1804:     - change mode from '' to '0644'
[2021-05-13T05:31:36.738Z]     ubuntu1804:   * bash[prepare_ubuntu] action run[1mTraceback[m (most recent call last):
[2021-05-13T05:31:36.738Z]     ubuntu1804: 	4: from /usr/bin/chef-client:146:in `<main>'
[2021-05-13T05:31:36.738Z]     ubuntu1804: 	3: from /usr/bin/chef-client:146:in `load'
[2021-05-13T05:31:36.738Z]     ubuntu1804: 	2: from /opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.13.16/bin/cinc-wrapper:34:in `<top (required)>'
[2021-05-13T05:31:36.738Z]     ubuntu1804: 	1: from /opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:270:in `run_command'
[2021-05-13T05:31:36.738Z]     ubuntu1804: /opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:128:in `run_command': [1mCommand timed out after 3600s: ([1;4mMixlib::ShellOut::CommandTimeout[m[1m)[m
[2021-05-13T05:31:36.738Z]     ubuntu1804: [1mCommand exceeded allowed execution time, process terminated[m
[2021-05-13T05:31:36.738Z]     ubuntu1804: [1m---- Begin output of ["/opt/cinc/bin/cinc-client", "-z", "--no-color", "-c", "/tmp/packer-chef-solo/solo.rb", "-j", "/tmp/packer-chef-solo/node.json"]
```
Just to show that this is not related to a particular recipe step, here is another occurance:
```
[2021-05-13T02:41:52.743Z]     ubuntu2004:   * apt_package[whoopsie] action install
[2021-05-13T02:41:52.743Z]     ubuntu2004:     - install version 0.2.69ubuntu0.3 of package whoopsie
[2021-05-13T02:59:13.998Z]     ubuntu2004:   * apt_package[ubuntu-desktop, lightdm, mesa-utils] action install[1mTraceback[m (most recent call last):
[2021-05-13T02:59:13.998Z]     ubuntu2004: 	4: from /usr/bin/chef-client:146:in `<main>'
[2021-05-13T02:59:13.998Z]     ubuntu2004: 	3: from /usr/bin/chef-client:146:in `load'
[2021-05-13T02:59:13.998Z]     ubuntu2004: 	2: from /opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.13.16/bin/cinc-wrapper:34:in `<top (required)>'
[2021-05-13T02:59:13.998Z]     ubuntu2004: 	1: from /opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:270:in `run_command'
[2021-05-13T02:59:13.998Z]     ubuntu2004: /opt/cinc/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/unix.rb:128:in `run_command': [1mCommand timed out after 3600s: ([1;4mMixlib::ShellOut::CommandTimeout[m[1m)[m
[2021-05-13T02:59:13.998Z]     ubuntu2004: [1mCommand exceeded allowed execution time, process terminated[m
[2021-05-13T02:59:13.998Z]     ubuntu2004: [1m---- Begin output of ["/opt/cinc/bin/cinc-client", "-z", "--no-color", "-c", "/tmp/packer-chef-solo/solo.rb", "-j", "/tmp/packer-chef-solo/node.json"] ----[m
```

From the log, it seems like the entire chef/cinc client provisioner step timed out. However, in our provisioner step we define a timeout of 3 hours:
```
{
      "type" : "chef-solo",
      "timeout": "3h",
...
      "execute_command" : "sudo chef-client -z --no-color -c {{.ConfigPath}} -j {{.JsonPath}}",
}
```

Don't know if it's related, but we also set `AWS_TIMEOUT_SECONDS=3600` to avoid ami copy timeout issue: https://github.com/hashicorp/packer/issues/6536
A quick test to change to `AWS_TIMEOUT_SECONDS=60` does not seem to affect the timeout issue, so `AWS_TIMEOUT_SECONDS` is probably not related

Can you help us understand why this timeout issue is happening? Thank you.

**Comment by rexcsn** [comment]
We eventually found out that it was an issue with [CINC wrapper in CINC 16.x](https://gitlab.com/cinc-project/upstream/chef/-/blob/5bf8ddcbfdb262655c23b2267b36bd817cb8b699/chef-bin/bin/cinc-wrapper#L39) that is causing the issue:
```
cmd = Mixlib::ShellOut.new("#{cmd_dir}/#{command}", *ARGV, live_stream: STDOUT, timeout: 3600)
```

Closing the issue as the issue is not related to packer. Thanks
