### ISSUE TITLE
Crash in digitalocean builder under Github Actions

### ISSUE THREAD

**Issue by davefp** [hashicorp/packer#11118]
#### Overview of the Issue

Packer crashes immediately while running digitalocean builder under Github Actions

#### Reproduction Steps

The issue is intermittent, but occurs with a simple `packer build` after checking out my code inside a Github Action. I never see this issue when running packer locally.

Here's a simplified workflow file:

<details>

<summary>workflow.yml</summary>

```yaml
name: Pack Application

on:
  push:
    branches: master

jobs:
  pack-app:
    runs-on: ubuntu-latest
    env:
      PKR_VAR_deploy_private_key_file: ~/.ssh/id_ed25519
      PKR_VAR_digital_ocean_api_key: ${{ secrets.API_KEY }}
      PKR_VAR_digital_ocean_application_image_id: ${{ secrets.IMAGE_ID }}
    defaults:
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_ed25519
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Build app image
        run: packer build
```

</details>

### Packer version

Github tells me that [their runners have Packer v1.7.3 pre-installed](https://github.com/actions/virtual-environments/blob/ubuntu20/20210621.1/images/linux/Ubuntu2004-README.md)

### Simplified Packer Buildfile

<details>
 <summary>Sources</summary>

```hcl
variable "digital_ocean_api_key" {
  type = string
}

source "digitalocean" "default" {
  api_token     = var.digital_ocean_api_key
  region        = "tor1"
  size          = "2gb"
}
```
</details>

<details>
 <summary>Buildfile</summary>

```hcl
variable "deploy_private_key_file" {
  type = string
  default = null
}

variable "digital_ocean_application_image_id" {
  type = string
  default = null
}

variable "commit_sha" {
  type = string
  default = null
}

variable "branch" {
  type = string
  default = null
}

build {
  name = "application_server"
  source "source.digitalocean.default" {
    ssh_username = "deploy"
    ssh_private_key_file = var.deploy_private_key_file
    image = var.digital_ocean_application_image_id
    snapshot_name = "server-${var.branch}_${var.commit_sha}"
    snapshot_regions = ["tor1", "nyc3"]
  }

  provisioner "ansible" {
    extra_arguments = ["--extra-vars", "commit_sha=${var.commit_sha}"]
    playbook_file   = "ansible_playbooks/application_server.yml"
  }
}
```
</details>

### Operating system and Environment details

This is running on an `ubuntu-latest` Github runner, full specs here: https://github.com/actions/virtual-environments/blob/ubuntu20/20210621.1/images/linux/Ubuntu2004-README.md

### Log Fragments and crash.log files

<details>
<summary>Packer output</summary>

```
application_server.digitalocean.default: output will be in this color.

==> application_server.digitalocean.default: Using existing SSH private key
==> application_server.digitalocean.default: No public SSH key found; skipping SSH public key import...
Build 'application_server.digitalocean.default' errored after 504 milliseconds 241 microseconds: unexpected EOF

==> Wait completed after 504 milliseconds 294 microseconds

==> Some builds didn't complete successfully and had errors:
--> application_server.digitalocean.default: unexpected EOF

==> Builds finished but no artifacts were created.
panic: interface conversion: interface {} is nil, not int
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 
2021/06/24 18:28:36 packer-builder-digitalocean plugin: goroutine 79 [running]:
2021/06/24 18:28:36 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-digitalocean/builder/digitalocean.(*stepCreateDroplet).Run(0xc0003a07e8, 0x5e4ce20, 0xc000af5540, 0x5e4d868, 0xc0009b10b0, 0x0)
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-digitalocean@v1.0.0/builder/digitalocean/step_create_droplet.go:24 +0x886
2021/06/24 18:28:36 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc0009b1140, 0x5e4ce20, 0xc000af5540, 0x5e4d868, 0xc0009b10b0)
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.2.3/multistep/basic_runner.go:70 +0x234
2021/06/24 18:28:36 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-digitalocean/builder/digitalocean.(*Builder).Run(0xc00045a900, 0x5e4ce20, 0xc000af5540, 0x5e66138, 0xc000ec3710, 0x5dbd780, 0xc000d16160, 0xc00085fd70, 0x4ab6740, 0xc0000cffc0, ...)
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-digitalocean@v1.0.0/builder/digitalocean/builder.go:116 +0x7f4
2021/06/24 18:28:36 packer-builder-digitalocean plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc000720280, 0x1, 0xc00002ef9c, 0x0, 0x0)
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/home/circleci/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.2.3/rpc/builder.go:117 +0x1c4
2021/06/24 18:28:36 packer-builder-digitalocean plugin: reflect.Value.call(0xc000cd36e0, 0xc00000e5e0, 0x13, 0x56cc20d, 0x4, 0xc00071bf08, 0x3, 0x3, 0xc000ec6180, 0x0, ...)
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/usr/local/go/src/reflect/value.go:476 +0x8e7
2021/06/24 18:28:36 packer-builder-digitalocean plugin: reflect.Value.Call(0xc000cd36e0, 0xc00000e5e0, 0x13, 0xc0006a7f08, 0x3, 0x3, 0x708fe5, 0xc0006a7f48, 0xc0006a7f2c)
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/usr/local/go/src/reflect/value.go:337 +0xb9
2021/06/24 18:28:36 packer-builder-digitalocean plugin: net/rpc.(*service).call(0xc0007202c0, 0xc0000ec5f0, 0xc000dc01b8, 0xc000dc01c0, 0xc000d62600, 0xc000d176c0, 0x469d880, 0xc00002ef98, 0x18a, 0x4577e60, ...)
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x189
2021/06/24 18:28:36 packer-builder-digitalocean plugin: created by net/rpc.(*Server).ServeCodec
2021/06/24 18:28:36 packer-builder-digitalocean plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x44d
2021/06/24 18:28:36 [INFO] (telemetry) ending 
2021/06/24 18:28:36 ui error: Build 'application_server.digitalocean.default' errored after 504 milliseconds 241 microseconds: unexpected EOF
2021/06/24 18:28:36 ui: 
==> Wait completed after 504 milliseconds 294 microseconds
2021/06/24 18:28:36 machine readable: error-count []string{"1"}
2021/06/24 18:28:36 ui error: 
==> Some builds didn't complete successfully and had errors:
2021/06/24 18:28:36 /usr/local/bin/packer: plugin process exited
2021/06/24 18:28:36 machine readable: application_server.digitalocean.default,error []string{"unexpected EOF"}
2021/06/24 18:28:36 ui error: --> application_server.digitalocean.default: unexpected EOF
2021/06/24 18:28:36 ui: 
==> Builds finished but no artifacts were created.
2021/06/24 18:28:36 [INFO] (telemetry) Finalizing.
2021/06/24 18:28:37 waiting for all plugin processes to complete...
2021/06/24 18:28:37 /usr/local/bin/packer: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
</details>

I don't have the full crash log since the github runner doesn't provide that for me by default. I'm going to work on setting up a build artifact to capture it and will post one as and when I'm able to do so.

**Comment by davefp** [comment]
After doing some further debugging I've narrowed down the cause somewhat:

* The error only occurs on `1.7.3`, it's not present in `1.7.2`
* The error only occurs when specifying the `ssh_private_key_file` option on the digitalocean builder

**Comment by davefp** [comment]
I've debugged this issue more and think it's more appropriate to file the bug against the digitalocean plugin repo, which I've done here: https://github.com/hashicorp/packer-plugin-digitalocean/issues/19

Not sure if I should close this issue or not, so I'm leaving it open for now.

**Comment by SwampDragons** [comment]
I'll close this since it's been transferred 👍
