### ISSUE TITLE
Packer crashes converting JSON to HCL via hcl2_upgrade

### ISSUE THREAD

**Issue by pjmcquade** [hashicorp/packer#11387]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Packer crashes converting JSON to HCL via hcl2_upgrade

Created a JSON file ``j.pkr.json``, copying an example from: https://www.packer.io/docs/templates/legacy_json_templates/user-variables
````
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },

  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}"
      // ...
    }
  ]
}
````

Then ran the following command:
````
packer hcl2_upgrade j.pkr.json
````
packer crashes with the following error:

````
Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
Original error: Error parsing JSON: invalid character '/' after object key:value pair
At line 12, column 8 (offset 230):
   11:       "secret_key": "{{user `aws_secret_key`}}"
   12:       /
             ^

Failed to get config from JSON
panic: interface conversion: packer.Handler is nil, not *command.CoreWrapper

goroutine 1 [running]:
github.com/hashicorp/packer/command.(*HCL2UpgradeCommand).RunContext(0xc000f63800, 0x5e4ce80, 0xc000b80e80, 0xc0001a0e00, 0x0)
        /home/circleci/project/packer/command/hcl2_upgrade.go:159 +0x1255
github.com/hashicorp/packer/command.(*HCL2UpgradeCommand).Run(0xc000f63800, 0xc00006e1a0, 0x1, 0x1, 0x0)
        /home/circleci/project/packer/command/hcl2_upgrade.go:41 +0xff
github.com/mitchellh/cli.(*CLI).Run(0xc000635900, 0xc000635900, 0x1, 0x1)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x41a
main.wrappedMain(0x0)
        /home/circleci/project/packer/main.go:262 +0x872
main.realMain(0x0)
        /home/circleci/project/packer/main.go:49 +0x105
main.main()
        /home/circleci/project/packer/main.go:35 +0x25
````

#### Reproduction Steps

The above crashes 100% of the time.

However, editing the file and removing the ``// ..`` line will fix the issue:

````
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": ""
  },

  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `aws_access_key`}}",
      "secret_key": "{{user `aws_secret_key`}}"
    }
  ]
}
````

re-running:

````
$ packer hcl2_upgrade j.pkr.json
Successfully created j.pkr.json.pkr.hcl. Exit 0
````

Viewing the output:

````
$ cat j.pkr.json.pkr.hcl

variable "aws_access_key" {
  type    = string
  default = ""
}

variable "aws_secret_key" {
  type    = string
  default = ""
}

source "amazon-ebs" "autogenerated_1" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

}
````

### Packer version

````
[a769@sv0a0904 __buildcache__]$ packer version
Packer v1.7.4

Your version of Packer is out of date! The latest version
is 1.7.8. You can update by downloading from www.packer.io/downloads
````

### Operating system and Environment details

Red Hat 8.4

### Log Fragments and crash.log files

````
$ packer hcl2_upgrade j.pkr.json
Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
Original error: Error parsing JSON: invalid character '/' after object key:value pair
At line 12, column 8 (offset 230):
   11:       "secret_key": "{{user `aws_secret_key`}}"
   12:       /
             ^

Failed to get config from JSON
panic: interface conversion: packer.Handler is nil, not *command.CoreWrapper

goroutine 1 [running]:
github.com/hashicorp/packer/command.(*HCL2UpgradeCommand).RunContext(0xc000f63800, 0x5e4ce80, 0xc000b80e80, 0xc0001a0e00, 0x0)
        /home/circleci/project/packer/command/hcl2_upgrade.go:159 +0x1255
github.com/hashicorp/packer/command.(*HCL2UpgradeCommand).Run(0xc000f63800, 0xc00006e1a0, 0x1, 0x1, 0x0)
        /home/circleci/project/packer/command/hcl2_upgrade.go:41 +0xff
github.com/mitchellh/cli.(*CLI).Run(0xc000635900, 0xc000635900, 0x1, 0x1)
        /home/circleci/go/pkg/mod/github.com/mitchellh/cli@v1.1.0/cli.go:260 +0x41a
main.wrappedMain(0x0)
        /home/circleci/project/packer/main.go:262 +0x872
main.realMain(0x0)
        /home/circleci/project/packer/main.go:49 +0x105
main.main()
        /home/circleci/project/packer/main.go:35 +0x25
````

**Comment by nywilken** [comment]
Hi @pjmcquade I see you are running an older version of Packer. This issue was addressed in a later release and is no longer reproducible with Packer 1.7.8. 

```
~>  packer --version
1.7.8

~>  packer invalid-json/input.json
Failed to parse file as legacy JSON template: if you are using an HCL template, check your file extensions; they should be either *.pkr.hcl or *.pkr.json; see the docs for more details: https://www.packer.io/docs/templates/hcl_templates.
Original error: Error parsing JSON: invalid character '/' after object key:value pair
At line 12, column 8 (offset 230):
   11:       "secret_key": "{{user `aws_secret_key`}}"
   12:       /
             ^

Failed to get config from JSON
```

I'm going to close this issue and ask that you upgrade to the latest version of Packer. If after upgrading you are still running into this issue please leave a comment on this thread and we will gladly reopen. Cheers!
