### ISSUE TITLE
packer 1.7.9 runtime panic issue

### ISSUE THREAD

**Issue by chenrui333** [hashicorp/packer#11512]
👋  tried to build from the source code of release 1.7.9, but failed to run on apple m1

```
$ /opt/homebrew/Cellar/packer/1.7.9/bin/packer version
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104afc800]

goroutine 1 [running, locked to thread]:
runtime.throw({0x108022b33, 0x2a})
	runtime/panic.go:1198 +0x54 fp=0x1400031f160 sp=0x1400031f130 pc=0x104b1dbb4
runtime.sigpanic()
	runtime/signal_unix.go:719 +0x230 fp=0x1400031f1a0 sp=0x1400031f160 pc=0x104b35b40
runtime.heapBitsSetType(0x14000299470, 0x10, 0x10, 0x1093b53c0)
	runtime/mbitmap.go:894 +0x370 fp=0x1400031f270 sp=0x1400031f1b0 pc=0x104afc800
runtime.mallocgc(0x10, 0x1093b53c0, 0x1)
	runtime/malloc.go:1106 +0x654 fp=0x1400031f300 sp=0x1400031f270 pc=0x104af40b4
runtime.newarray(0x1093b53c0, 0x4)
	runtime/malloc.go:1256 +0x8c fp=0x1400031f330 sp=0x1400031f300 pc=0x104af457c
runtime.makeBucketArray(0x108df4460, 0x2, 0x0)
	runtime/map.go:362 +0x168 fp=0x1400031f370 sp=0x1400031f330 pc=0x104af5468
runtime.makemap(0x108df4460, 0xe, 0x0)
	runtime/map.go:328 +0x128 fp=0x1400031f3c0 sp=0x1400031f370 pc=0x104af5248
golang.org/x/net/http2.init()
	golang.org/x/net@v0.0.0-20210902165921-8d991716f632/http2/errors.go:32 +0xa0 fp=0x1400031f470 sp=0x1400031f3c0 pc=0x105119dd0
runtime.doInit(0x10d16b380)
	runtime/proc.go:6498 +0x138 fp=0x1400031f5d0 sp=0x1400031f470 pc=0x104b2f038
runtime.doInit(0x10d170cc0)
	runtime/proc.go:6475 +0x70 fp=0x1400031f730 sp=0x1400031f5d0 pc=0x104b2ef70
runtime.doInit(0x10d161420)
	runtime/proc.go:6475 +0x70 fp=0x1400031f890 sp=0x1400031f730 pc=0x104b2ef70
runtime.doInit(0x10d162d60)
	runtime/proc.go:6475 +0x70 fp=0x1400031f9f0 sp=0x1400031f890 pc=0x104b2ef70
runtime.doInit(0x10d15a360)
	runtime/proc.go:6475 +0x70 fp=0x1400031fb50 sp=0x1400031f9f0 pc=0x104b2ef70
runtime.doInit(0x10d1637e0)
	runtime/proc.go:6475 +0x70 fp=0x1400031fcb0 sp=0x1400031fb50 pc=0x104b2ef70
runtime.doInit(0x10d19e860)
	runtime/proc.go:6475 +0x70 fp=0x1400031fe10 sp=0x1400031fcb0 pc=0x104b2ef70
runtime.doInit(0x10d16ca00)
	runtime/proc.go:6475 +0x70 fp=0x1400031ff70 sp=0x1400031fe10 pc=0x104b2ef70
runtime.main()
	runtime/proc.go:238 +0x22c fp=0x1400031ffd0 sp=0x1400031ff70 pc=0x104b2034c
runtime.goexit()
	runtime/asm_arm64.s:1133 +0x4 fp=0x1400031ffd0 sp=0x1400031ffd0 pc=0x104b51674
```

full build log, https://github.com/Homebrew/homebrew-core/runs/4885996522
relates to https://github.com/Homebrew/homebrew-core/pull/93447

**Comment by JenGoldstrich** [comment]
Hey @chenrui333, thanks for reaching out to us about this issue!

I tried to reproduce this on my m1 mac, by running `Make` on my M1 Pro mbp while having 1.7.9 checked out, it worked for me with the following results

```
bin git:(a3f94fd3d) ✗ ./packer version
Packer v1.7.9
➜  bin git:(a3f94fd3d) ✗ file packer
packer: Mach-O 64-bit executable arm64
➜  bin git:(a3f94fd3d) ✗ go version
go version go1.17.5 darwin/arm64
➜  bin git:(a3f94fd3d) ✗ file go
go: cannot open `go' (No such file or directory)
➜  bin git:(a3f94fd3d) ✗ which go
/opt/homebrew/bin/go
➜  bin git:(a3f94fd3d) ✗ file /opt/homebrew/bin/go
/opt/homebrew/bin/go: Mach-O 64-bit executable arm64
```
What commands are y'all running to build Packer from source, and can you make sure you're running the ARM version, rather than the intel one in Rosetta by running `file packer` in your bin directory?


I do notice a warning in my output 
```
# github.com/shirou/gopsutil/cpu
../../../../pkg/mod/github.com/shirou/gopsutil@v3.21.1+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
```

Not sure if this is related at all but I'd be curious if you also see this warning.

**Comment by JenGoldstrich** [comment]
Following up this morning I figured out how y'all are building packer using brew test-bot, working to configure my environment to use the PR branch of homebrew-core with 1.7.9 instead, will update you when I've gotten that figured out

**Comment by chenrui333** [comment]
Yeah, we used test-bot for CI, thanks for the help!

**Comment by JenGoldstrich** [comment]
This should be fixed by https://github.com/hashicorp/packer/pull/11546, the next Packer release should fix this issue

**Comment by JenGoldstrich** [comment]
Closing this, should be resolved in v1.7.10 https://github.com/hashicorp/packer/releases/tag/v1.7.10, please feel free to open a new issue or re-open this one if this issue reoccurs in your pipeline, thanks @azr for the fix!

**Comment by chenrui333** [comment]
Thanks @JenGoldstrich, gonna give a shot.

**Comment by chenrui333** [comment]
Yeah, it builds out fine with 1.7.10 now.
