### ISSUE TITLE
Packer crashes because of AWS security group suppression.

### ISSUE THREAD

**Issue by mercierc** [hashicorp/packer#12149]
A bug report on a packer crash after failing to delete an AWS Security group. After the crash packer cannot delete the running ec2 instance and it must be donne manually.
 Here is the report from packer : 

$ cat crash.log 

2022/12/08 16:01:10 [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 Creating plugin client for path: /usr/bin/packer

2022/12/08 16:01:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-builder-amazon-ebs"}

2022/12/08 16:01:10 Waiting for RPC address for: /usr/bin/packer

2022/12/08 16:01:10 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin856605533

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: args: []string{"packer-builder-amazon-ebs"}

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: Plugin address: unix /tmp/packer-plugin856605533

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: Waiting for connection...

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: Serving a plugin connection...

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: [INFO] (aws): No AWS timeout and polling overrides have been set. Packer will default to waiter-specific delays and timeouts. If you would like to customize the length of time between retries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS or the configuration options aws_polling_delay_seconds and aws_polling_max_attempts to your desired values.

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 Creating plugin client for path: /usr/bin/packer

2022/12/08 16:01:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}

2022/12/08 16:01:10 Waiting for RPC address for: /usr/bin/packer

2022/12/08 16:01:10 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin766389309

2022/12/08 16:01:10 packer-provisioner-powershell plugin: [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 packer-provisioner-powershell plugin: 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin766389309

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Waiting for connection...

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Serving a plugin connection...

2022/12/08 16:01:10 Creating plugin client for path: /usr/bin/packer

2022/12/08 16:01:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-windows-restart"}

2022/12/08 16:01:10 Waiting for RPC address for: /usr/bin/packer

2022/12/08 16:01:10 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin766921169

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: args: []string{"packer-provisioner-windows-restart"}

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: Plugin address: unix /tmp/packer-plugin766921169

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: Waiting for connection...

2022/12/08 16:01:10 packer-provisioner-windows-restart plugin: Serving a plugin connection...

2022/12/08 16:01:10 Creating plugin client for path: /usr/bin/packer

2022/12/08 16:01:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}

2022/12/08 16:01:10 Waiting for RPC address for: /usr/bin/packer

2022/12/08 16:01:10 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin660257681

2022/12/08 16:01:10 packer-provisioner-powershell plugin: [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 packer-provisioner-powershell plugin: 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin660257681

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Waiting for connection...

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Serving a plugin connection...

2022/12/08 16:01:10 Creating plugin client for path: /usr/bin/packer

2022/12/08 16:01:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-powershell"}

2022/12/08 16:01:10 Waiting for RPC address for: /usr/bin/packer

2022/12/08 16:01:10 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin894986686

2022/12/08 16:01:10 packer-provisioner-powershell plugin: [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 packer-provisioner-powershell plugin: 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin894986686

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Waiting for connection...

2022/12/08 16:01:10 packer-provisioner-powershell plugin: Serving a plugin connection...

2022/12/08 16:01:10 Creating plugin client for path: /usr/bin/packer

2022/12/08 16:01:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-puppet-masterless"}

2022/12/08 16:01:10 Waiting for RPC address for: /usr/bin/packer

2022/12/08 16:01:10 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin583020881

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: args: []string{"packer-provisioner-puppet-masterless"}

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: Plugin address: unix /tmp/packer-plugin583020881

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: Waiting for connection...

2022/12/08 16:01:10 packer-provisioner-puppet-masterless plugin: Serving a plugin connection...

2022/12/08 16:01:10 Creating plugin client for path: /usr/bin/packer

2022/12/08 16:01:10 Starting plugin: /usr/bin/packer []string{"/usr/bin/packer", "plugin", "packer-provisioner-file"}

2022/12/08 16:01:10 Waiting for RPC address for: /usr/bin/packer

2022/12/08 16:01:10 Received unix RPC address for /usr/bin/packer: addr is /tmp/packer-plugin285946828

2022/12/08 16:01:10 packer-provisioner-file plugin: [INFO] Packer version: 1.6.6 [go1.15.9 linux amd64]

2022/12/08 16:01:10 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path

2022/12/08 16:01:10 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path

2022/12/08 16:01:10 packer-provisioner-file plugin: Attempting to open config file: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /home/cmercier/.packerconfig

2022/12/08 16:01:10 packer-provisioner-file plugin: Setting cache directory: /home/cmercier/git/infra_k2022/gitlab_runner_windows/windows/windows/packer_cache

2022/12/08 16:01:10 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}

2022/12/08 16:01:10 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin285946828

2022/12/08 16:01:10 packer-provisioner-file plugin: Waiting for connection...

2022/12/08 16:01:10 packer-provisioner-file plugin: Serving a plugin connection...

2022/12/08 16:01:10 [TRACE] validateValue: not active for region, so skipping

2022/12/08 16:01:10 [TRACE] validateValue: not active for timestamp, so skipping

2022/12/08 16:01:10 ui: learn-packer.amazon-ebs.firstrun-windows: output will be in this color.

2022/12/08 16:01:10 ui: 

2022/12/08 16:01:10 Build debug mode: false

2022/12/08 16:01:10 Force build: false

2022/12/08 16:01:10 On error: 

2022/12/08 16:01:10 Waiting on builds to complete...

2022/12/08 16:01:10 Starting build run: learn-packer.amazon-ebs.firstrun-windows

2022/12/08 16:01:10 Running builder: 

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: [INFO] AWS Auth provider used: "SharedCredentialsProvider"

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: Found region eu-central-1

2022/12/08 16:01:10 packer-builder-amazon-ebs plugin: [INFO] AWS Auth provider used: "SharedCredentialsProvider"

2022/12/08 16:01:10 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Prevalidating any provided VPC information

2022/12/08 16:01:10 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Prevalidating AMI Name: packer-windows-demo-20221208150110

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin: Using AMI Filters {

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:   Filters: [{

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:       Name: "name",

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:       Values: ["Windows_Server-2022-English-Full-Base-2022.11.10"]

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:     },{

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:       Name: "root-device-type",

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:       Values: ["ebs"]

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:     },{

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:       Name: "virtualization-type",

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:       Values: ["hvm"]

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:     }],

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin:   Owners: ["amazon"]

2022/12/08 16:01:11 packer-builder-amazon-ebs plugin: }

2022/12/08 16:01:12 ui:     learn-packer.amazon-ebs.firstrun-windows: Found Image ID: ami-05a60358d5cda31c5

2022/12/08 16:01:12 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Creating temporary keypair: packer_6391fc36-e510-97e8-9d8f-f2a73f01d6f5

2022/12/08 16:01:12 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Creating temporary security group for this instance: packer_6391fc38-0ada-e4d6-7816-2177d2d72791

2022/12/08 16:01:13 packer-builder-amazon-ebs plugin: [DEBUG] Waiting for temporary security group: sg-0340773700e9a15d4

2022/12/08 16:01:13 packer-builder-amazon-ebs plugin: [DEBUG] Found security group sg-0340773700e9a15d4

2022/12/08 16:01:13 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Authorizing access to port 5985 from [0.0.0.0/0] in the temporary security groups...

2022/12/08 16:01:14 packer-builder-amazon-ebs plugin: [DEBUG] base64 encoding user data...

2022/12/08 16:01:14 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Launching a source AWS instance...

2022/12/08 16:01:14 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Adding tags to source instance

2022/12/08 16:01:14 ui:     learn-packer.amazon-ebs.firstrun-windows: Adding tag: "Name": "Packer Builder"

2022/12/08 16:01:16 ui:     learn-packer.amazon-ebs.firstrun-windows: Instance ID: i-013c8ab06fa30c623

2022/12/08 16:01:16 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Waiting for instance (i-013c8ab06fa30c623) to become ready...

2022/12/08 16:01:28 ui error: Cancelling build after receiving interrupt

2022/12/08 16:01:28 Cancelling builder after context cancellation context canceled

2022/12/08 16:01:28 packer-provisioner-file plugin: Received interrupt signal (count: 1). Ignoring.

2022/12/08 16:01:28 packer-builder-amazon-ebs plugin: Received interrupt signal (count: 1). Ignoring.

2022/12/08 16:01:28 packer-provisioner-powershell plugin: Received interrupt signal (count: 1). Ignoring.

2022/12/08 16:01:28 packer-provisioner-puppet-masterless plugin: Received interrupt signal (count: 1). Ignoring.

2022/12/08 16:01:28 packer-provisioner-powershell plugin: Received interrupt signal (count: 1). Ignoring.

2022/12/08 16:01:28 packer-provisioner-windows-restart plugin: Received interrupt signal (count: 1). Ignoring.

2022/12/08 16:01:28 packer-provisioner-powershell plugin: Received interrupt signal (count: 1). Ignoring.

2022/12/08 16:01:28 ui error: ==> learn-packer.amazon-ebs.firstrun-windows: Error waiting for instance (i-013c8ab06fa30c623) to become ready: RequestCanceled: waiter context canceled

==> learn-packer.amazon-ebs.firstrun-windows: caused by: context canceled

2022/12/08 16:01:28 ui: ==> learn-packer.amazon-ebs.firstrun-windows: No volumes to clean up, skipping

2022/12/08 16:01:28 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Deleting temporary security group...

2022/12/08 16:01:28 packer-provisioner-file plugin: Received interrupt signal (count: 2). Ignoring.

2022/12/08 16:01:28 packer-builder-amazon-ebs plugin: Received interrupt signal (count: 2). Ignoring.

2022/12/08 16:01:28 packer-provisioner-powershell plugin: Received interrupt signal (count: 2). Ignoring.

2022/12/08 16:01:28 packer-provisioner-puppet-masterless plugin: Received interrupt signal (count: 2). Ignoring.

2022/12/08 16:01:28 packer-provisioner-powershell plugin: Received interrupt signal (count: 2). Ignoring.

2022/12/08 16:01:28 packer-provisioner-windows-restart plugin: Received interrupt signal (count: 2). Ignoring.

2022/12/08 16:01:28 packer-provisioner-powershell plugin: Received interrupt signal (count: 2). Ignoring.

2022/12/08 16:01:29 packer-builder-amazon-ebs plugin: Error deleting security group: DependencyViolation: resource sg-0340773700e9a15d4 has a dependent object

2022/12/08 16:01:29 packer-builder-amazon-ebs plugin: 	status code: 400, request id: 9d50c6ee-7903-488e-a2b3-e011d7cb078b

2022/12/08 16:01:35 packer-builder-amazon-ebs plugin: Error deleting security group: DependencyViolation: resource sg-0340773700e9a15d4 has a dependent object

2022/12/08 16:01:35 packer-builder-amazon-ebs plugin: 	status code: 400, request id: c2fb4649-2c14-4d41-83f4-4501f57668ad

2022/12/08 16:01:40 packer-builder-amazon-ebs plugin: Error deleting security group: DependencyViolation: resource sg-0340773700e9a15d4 has a dependent object

2022/12/08 16:01:40 packer-builder-amazon-ebs plugin: 	status code: 400, request id: b613990c-523f-46cb-87cd-123354031465

2022/12/08 16:01:46 packer-builder-amazon-ebs plugin: Error deleting security group: DependencyViolation: resource sg-0340773700e9a15d4 has a dependent object

2022/12/08 16:01:46 packer-builder-amazon-ebs plugin: 	status code: 400, request id: dcc3f0f9-3085-4550-829b-35b8f04de379

2022/12/08 16:01:52 packer-builder-amazon-ebs plugin: Error deleting security group: DependencyViolation: resource sg-0340773700e9a15d4 has a dependent object

2022/12/08 16:01:52 packer-builder-amazon-ebs plugin: 	status code: 400, request id: bef715c1-ebae-4593-949e-e56c1ccb5e21

2022/12/08 16:01:57 ui error: ==> learn-packer.amazon-ebs.firstrun-windows: Error cleaning up security group. Please delete the group manually: err: DependencyViolation: resource sg-0340773700e9a15d4 has a dependent object

==> learn-packer.amazon-ebs.firstrun-windows: 	status code: 400, request id: bef715c1-ebae-4593-949e-e56c1ccb5e21; security group ID: sg-0340773700e9a15d4

2022/12/08 16:01:57 ui: ==> learn-packer.amazon-ebs.firstrun-windows: Deleting temporary keypair...

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: panic: runtime error: invalid memory address or nil pointer dereference

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x19b8321]

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: goroutine 104 [running]:

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: github.com/hashicorp/packer/builder/amazon/common.(*StepRunSourceInstance).Run(0xc000774f20, 0x468ada0, 0xc0003602c0, 0x468b260, 0xc00073b9e0, 0x0)

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	github.com/hashicorp/packer/builder/amazon/common/step_run_source_instance.go:254 +0x16a1

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: github.com/hashicorp/packer/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc00073bad0, 0x468ada0, 0xc0003602c0, 0x468b260, 0xc00073b9e0)

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	github.com/hashicorp/packer/packer-plugin-sdk/multistep/basic_runner.go:70 +0x234

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: github.com/hashicorp/packer/builder/amazon/ebs.(*Builder).Run(0xc000284900, 0x468ada0, 0xc0003602c0, 0x46a46c0, 0xc00073b140, 0x4626c80, 0xc00042a060, 0x0, 0xc00018fbf8, 0xc000081bd0, ...)

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	github.com/hashicorp/packer/builder/amazon/ebs/builder.go:354 +0x194b

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: github.com/hashicorp/packer/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc000450dc0, 0x1, 0xc0004627b0, 0x0, 0x0)

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	github.com/hashicorp/packer/packer-plugin-sdk/rpc/builder.go:117 +0x1c4

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: reflect.Value.call(0xc00018fbc0, 0xc000010810, 0x13, 0x40f4196, 0x4, 0xc000081f08, 0x3, 0x3, 0xc000092960, 0xc000060000, ...)

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	reflect/value.go:476 +0x8c7

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: reflect.Value.Call(0xc00018fbc0, 0xc000010810, 0x13, 0xc0006de708, 0x3, 0x3, 0xc000740738, 0xc0000928f0, 0x4627a0)

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	reflect/value.go:337 +0xb9

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: net/rpc.(*service).call(0xc000450e00, 0xc000180550, 0xc000052830, 0xc000052840, 0xc0000c7980, 0xc000527380, 0x34ccd80, 0xc0004627ac, 0x18a, 0x340a880, ...)

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	net/rpc/server.go:377 +0x189

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: created by net/rpc.(*Server).ServeCodec

2022/12/08 16:01:57 packer-builder-amazon-ebs plugin: 	net/rpc/server.go:474 +0x445

2022/12/08 16:01:57 ui error: Build 'learn-packer.amazon-ebs.firstrun-windows' errored after 46 seconds 877 milliseconds: unexpected EOF

2022/12/08 16:01:57 ui: 

==> Wait completed after 46 seconds 877 milliseconds

2022/12/08 16:01:57 ui: Cleanly cancelled builds after being interrupted.

2022/12/08 16:01:57 waiting for all plugin processes to complete...

2022/12/08 16:01:57 /usr/bin/packer: plugin process exited

2022/12/08 16:01:57 /usr/bin/packer: plugin process exited

2022/12/08 16:01:57 /usr/bin/packer: plugin process exited

2022/12/08 16:01:57 /usr/bin/packer: plugin process exited

2022/12/08 16:01:57 /usr/bin/packer: plugin process exited

2022/12/08 16:01:57 /usr/bin/packer: plugin process exited

2022/12/08 16:01:57 /usr/bin/packer: plugin process exited

#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

From `packer version`

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment]
Hi @mercierc thanks for opening up this issue. Are you still running into this issue?  It looks like you are using version 1.6.6 of Packer. 

Have you tried with the latest version of Packer and AWS plugin? 

There have been a number of changes since 1.6.6 so I would like to know if you are able to reproduce the issue. If you are, could you please provide an example configuration to reproduce the problem with. 

The error message below seems to imply that the Security Group was being used by something that was not yet deleted (may deletion required more time) or something outside of the Packer build is using the security group. 

```
2022/12/08 16:01:57 ui error: ==> learn-packer.amazon-ebs.firstrun-windows: Error cleaning up security group. Please delete the group manually: err: DependencyViolation: resource sg-0340773700e9a15d4 has a dependent object
```

Is the security group being created by Packer or are you trying to use an existing security group?
