### ISSUE TITLE
azure-arm - ARM64 Image - sourceVirtualMachine source that has CPU Architecture 'Arm64' is not supported.

### ISSUE THREAD

**Issue by rbposborne** [hashicorp/packer#12188]
#### Overview of the Issue
==> azure-arm: ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture 'Arm64' is not supported. Please select a source resource with a supported CPU Architecture: 'x64'.
=

#### Reproduction Steps
See template. Reading ARM64 Image to create updated ARM64 Image in Azure Compute Gallery

### Packer version
packer --version
1.8.5

### Simplified Packer Template
```
{
  "variables": {
    "client_id"                           : "{{env `ARM_CLIENT_ID`}}",
    "client_secret"                       : "{{env `ARM_CLIENT_SECRET`}}",
    "subscription_id"                     : "{{env `ARM_SUBSCRIPTION_ID`}}",
    "tenant_id"                           : "{{env `ARM_TENANT_ID`}}",
    "resource_group"                      : "{{env `RESOURCE_GROUP`}}",
    "boot_diag_storage_account"           : "{{env `BLOB_STORAGE_ACCOUNT`}}",

    "virtual_network_name"                : "{{env `VIRTUAL_NETWORK_NAME`}}",
    "virtual_network_subnet_name"         : "{{env `VIRTUAL_NETWORK_SUBNET_NAME`}}",
    "virtual_network_resource_group_name" : "{{env `VIRTUAL_NETWORK_RESOURCE_GROUP_NAME`}}",

    "os_type"                             : "{{env `OS_TYPE`}}",
    "vm_size"                             : "{{env `VM_SIZE`}}",

    "source_image_gallery_name"           : "{{env `SOURCE_IMAGE_GALLERY_NAME`}}",
    "source_image_definition_name"        : "{{env `SOURCE_IMAGE_DEFINITION_NAME`}}",
    "source_image_name"                   : "{{env `SOURCE_IMAGE_NAME`}}",

    "destination_image_gallery_name"      : "{{env `DESTINATION_IMAGE_GALLERY_NAME`}}",
    "destination_image_definition_name"   : "{{env `DESTINATION_IMAGE_DEFINITION_NAME`}}",
    "destination_image_name"              : "{{env `DESTINATION_IMAGE_NAME`}}",
    "destination_image_version"           : "{{env `DESTINATION_IMAGE_VERSION`}}",
    "destination_image_tags"              : "{{env `DESTINATION_IMAGE_TAGS`}}",

    "ssh_username"                        : "{{env `SSH_USERNAME`}}",
    "ssh_keypair_name"                    : "{{env `SSH_KEYPAIR_NAME`}}",
    "ssh_private_key_file"                : "{{env `SSH_PRIVATE_KEY_FILE`}}"
  },
  "builders": [{
    "type": "azure-arm",

    "client_id": "{{user `client_id`}}",
    "client_secret": "{{user `client_secret`}}",

    "subscription_id": "{{user `subscription_id`}}",
    "tenant_id": "{{user `tenant_id`}}",

    "ssh_username": "{{user `ssh_username`}}",
    "ssh_keypair_name": "{{user `ssh_keypair_name`}}",
    "ssh_private_key_file": "{{user `ssh_private_key_file`}}",

    "virtual_network_name": "{{user `virtual_network_name`}}",
    "virtual_network_subnet_name": "{{user `virtual_network_subnet_name`}}",
    "virtual_network_resource_group_name": "{{user `virtual_network_resource_group_name`}}",

    "os_type": "{{user `os_type`}}",
    "boot_diag_storage_account": "{{user `boot_diag_storage_account`}}",

    "ssh_pty": "true",
    "vm_size": "{{user `vm_size`}}",

    "build_resource_group_name": "{{user `resource_group`}}",

    "managed_image_resource_group_name": "{{user `resource_group`}}",
    "managed_image_name": "{{user `destination_image_name`}}",

    "shared_image_gallery": {
      "subscription": "{{user `subscription_id`}}",
      "resource_group": "{{user `resource_group`}}",
      "gallery_name": "{{user `source_image_gallery_name`}}",
      "image_name": "{{user `source_image_name`}}",
      "image_version": "latest"
    },
    "shared_image_gallery_destination": {
      "resource_group": "{{user `resource_group`}}",
      "gallery_name": "{{user `destination_image_gallery_name`}}",
      "image_name": "{{user `destination_image_definition_name`}}",
      "image_version": "{{user `destination_image_version`}}",
      "replication_regions": [
        "westeurope", "northeurope", "eastus", "germanywestcentral","southeastasia", "eastus2"
      ]
    }
  }],
  "provisioners": [
    {
      "type": "shell",
      "expect_disconnect": "true",
      "remote_folder": "/home/{{ user `ssh_username` }}",
      "execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'",
      "inline": [
        "echo 'Hello world'"
      ]
    },
    {
      "type": "shell-local",
      "inline": [
        "echo '*** PACKER is Finished ***'"
      ]
    }
  ]
}
```
### Operating system and Environment details
cat /etc/redhat-release
Red Hat Enterprise Linux release 9.1 (Plow)
uname -a
Linux rhel-9-arm64-prd-ne-gob-admin-server 5.14.0-162.6.1.el9_1.aarch64 #1 SMP PREEMPT_DYNAMIC Fri Sep 30 07:44:58 EDT 2022 aarch64 aarch64 aarch64 GNU/Linux

### Packer Log:
```
==> azure-arm: Running builder ...
==> azure-arm: Getting tokens using client secret
==> azure-arm: Getting tokens using client secret
    azure-arm: Creating Azure Resource Manager (ARM) client ...
==> azure-arm: Getting source image id for the deployment ...
==> azure-arm: Using existing resource group ...
==> azure-arm:  -> ResourceGroupName : 'redacted'
==> azure-arm:  -> Location          : 'redacted'
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'redacted'
==> azure-arm:  -> DeploymentName    : 'pkrdpnjxdfcwj9u'
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'redacted'
==> azure-arm:  -> DeploymentName    : 'pkrdpnjxdfcwj9u'
==> azure-arm: Getting the VM's IP address ...
==> azure-arm:  -> ResourceGroupName   : 'redacted'
==> azure-arm:  -> PublicIPAddressName : 'pkripnjxdfcwj9u'
==> azure-arm:  -> NicName             : 'pkrninjxdfcwj9u'
==> azure-arm:  -> Network Connection  : 'PrivateEndpoint'
==> azure-arm:  -> IP Address          : 'redacted'
==> azure-arm: Waiting for SSH to become available...
==> azure-arm: Connected to SSH!
==> azure-arm: Provisioning with shell script: /tmp/packer-shell729456982
    azure-arm: Hello world
==> azure-arm: Running local shell script: /tmp/packer-shell1869093741
    azure-arm: *** PACKER is Finished ***
==> azure-arm: Querying the machine's properties ...
==> azure-arm:  -> ResourceGroupName : 'redacted'
==> azure-arm:  -> ComputeName       : 'pkrvmnjxdfcwj9u'
==> azure-arm:  -> Managed OS Disk   : '/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Compute/disks/pkrosnjxdfcwj9u'
==> azure-arm: Querying the machine's additional disks properties ...
==> azure-arm:  -> ResourceGroupName : 'redacted'
==> azure-arm:  -> ComputeName       : 'pkrvmnjxdfcwj9u'
==> azure-arm: Powering off machine ...
==> azure-arm:  -> ResourceGroupName : 'redacted'
==> azure-arm:  -> ComputeName       : 'pkrvmnjxdfcwj9u'
==> azure-arm: Capturing image ...
==> azure-arm:  -> Compute ResourceGroupName : 'redacted'
==> azure-arm:  -> Compute Name              : 'pkrvmnjxdfcwj9u'
==> azure-arm:  -> Compute Location          : 'redacted'
==> azure-arm:  -> Image ResourceGroupName   : 'redacted'
==> azure-arm:  -> Image Name                : 'rhel-9-arm64-dev-2023-01-11-150416'
==> azure-arm:  -> Image Location            : 'redacted'
**==> azure-arm: ERROR: -> OperationNotAllowed : Creating an image with sourceVirtualMachine source that has CPU Architecture 'Arm64' is not supported. Please select a source resource with a supported CPU Architecture: 'x64'.**
==> azure-arm:
==> azure-arm:
==> azure-arm: Deleting individual resources ...
==> azure-arm: Adding to deletion queue -> Microsoft.Compute/virtualMachines : 'pkrvmnjxdfcwj9u'
==> azure-arm: Adding to deletion queue -> Microsoft.Network/networkInterfaces : 'pkrninjxdfcwj9u'
==> azure-arm: Waiting for deletion of all resources...
==> azure-arm: Attempting deletion -> Microsoft.Network/networkInterfaces : 'pkrninjxdfcwj9u'
==> azure-arm: Attempting deletion -> Microsoft.Compute/virtualMachines : 'pkrvmnjxdfcwj9u'
==> azure-arm:  Deleting -> Microsoft.Compute/disks : '/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Compute/disks/pkrosnjxdfcwj9u'
.....
.....
panic: runtime error: invalid memory address or nil pointer dereference
2023/01/11 14:10:45 packer-builder-azure-arm plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1a97094]
2023/01/11 14:10:45 packer-builder-azure-arm plugin:
2023/01/11 14:10:45 packer-builder-azure-arm plugin: goroutine 27 [running]:
2023/01/11 14:10:45 packer-builder-azure-arm plugin: github.com/Azure/go-autorest/autorest/azure.(*Future).WaitForCompletionRef(0x4000e47f10, {0x51bb758?, 0x4000c075c0?}, {{0x517ac08, 0x40006823d0}, {0x519f0e8, 0x40004f5890}, 0x40003f2110, 0x4000d68ec0, 0x6fc23ac00, ...})
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /home/runner/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.11.19/azure/async.go:228 +0x524
2023/01/11 14:10:45 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-azure/builder/azure/arm.(*StepCaptureImage).captureImageFromVM(0x4000c1ed00, {0x51bb758, 0x4000c075c0}, {0x40003ab916?, 0x4000b8ef90?}, {0x400007b540?, 0x2d?}, 0x400017c270?)
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /home/runner/go/pkg/mod/github.com/hashicorp/packer-plugin-azure@v1.3.1/builder/azure/arm/step_capture_image.go:57 +0x168
2023/01/11 14:10:45 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-azure/builder/azure/arm.(*StepCaptureImage).Run(0x4000c1ed00, {0x51bb758, 0x4000c075c0}, {0x51bc558, 0x4000fff8c0})
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /home/runner/go/pkg/mod/github.com/hashicorp/packer-plugin-azure@v1.3.1/builder/azure/arm/step_capture_image.go:93 +0x46c
2023/01/11 14:10:45 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0x400105dd70, {0x51bb758, 0x4000c075c0}, {0x51bc558, 0x4000fff8c0})
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /home/runner/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.3.2/multistep/basic_runner.go:70 +0x2c4
2023/01/11 14:10:45 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-azure/builder/azure/arm.(*Builder).Run(0x4000b6a000, {0x51bb758, 0x4000c3c080}, {0x51c0718, 0x4000b8ef90}, {0x517f788?, 0x40003c6960})
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /home/runner/go/pkg/mod/github.com/hashicorp/packer-plugin-azure@v1.3.1/builder/azure/arm/builder.go:307 +0x2144
2023/01/11 14:10:45 packer-builder-azure-arm plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0x4000c1e000, 0x93a8c?, 0x400071a04c)
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /home/runner/go/pkg/mod/github.com/hashicorp/packer-plugin-sdk@v0.3.2/rpc/builder.go:117 +0x1e0
2023/01/11 14:10:45 packer-builder-azure-arm plugin: reflect.Value.call({0x400011cf60?, 0x400011a868?, 0x13?}, {0x4979f70, 0x4}, {0x4000ba7ef8, 0x3, 0x3?})
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /opt/hostedtoolcache/go/1.18.9/x64/src/reflect/value.go:556 +0x5e4
2023/01/11 14:10:45 packer-builder-azure-arm plugin: reflect.Value.Call({0x400011cf60?, 0x400011a868?, 0x100004000605ec8?}, {0x4000605ef8, 0x3, 0x3})
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /opt/hostedtoolcache/go/1.18.9/x64/src/reflect/value.go:339 +0x98
2023/01/11 14:10:45 packer-builder-azure-arm plugin: net/rpc.(*service).call(0x4000c1e040, 0x8?, 0x0?, 0x40003aa080, 0x400012e400, 0x4000cd9258?, {0x38ad3e0?, 0x400071a048?, 0x4000cd9200?}, {0x377fb40?, ...}, ...)
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /opt/hostedtoolcache/go/1.18.9/x64/src/net/rpc/server.go:381 +0x218
2023/01/11 14:10:45 packer-builder-azure-arm plugin: created by net/rpc.(*Server).ServeCodec
2023/01/11 14:10:45 packer-builder-azure-arm plugin:    /opt/hostedtoolcache/go/1.18.9/x64/src/net/rpc/server.go:478 +0x344
2023/01/11 14:10:45 [INFO] (telemetry) ending azure-arm
2023/01/11 14:10:45 ui error: Build 'azure-arm' errored after 6 minutes 24 seconds: unexpected EOF
2023/01/11 14:10:45 ui:
==> Wait completed after 6 minutes 24 seconds
2023/01/11 14:10:45 machine readable: error-count []string{"1"}
2023/01/11 14:10:45 ui error:
==> Some builds didn't complete successfully and had errors:
2023/01/11 14:10:45 machine readable: azure-arm,error []string{"unexpected EOF"}
2023/01/11 14:10:45 ui error: --> azure-arm: unexpected EOF
2023/01/11 14:10:45 ui:
==> Builds finished but no artifacts were created.
2023/01/11 14:10:45 [INFO] (telemetry) Finalizing.
2023/01/11 14:10:45 /usr/local/bin/packer: plugin process exited
2023/01/11 14:10:45 [WARN] (telemetry) Error finalizing report. This is safe to ignore. Post "https://checkpoint-api.hashicorp.com/v1/telemetry/packer": read tcp *********x`:42322->13.32.145.80:443: read: connection reset by peer
2023/01/11 14:10:45 waiting for all plugin processes to complete...
2023/01/11 14:10:45 /usr/local/bin/packer: plugin process exited
2023/01/11 14:10:45 /usr/local/bin/packer: plugin process exited

Failed to report panic. This is safe to ignore: Post "https://checkpoint-api.hashicorp.com/v1/telemetry/packer": read tcp redacted->13.32.145.88:443: read: connection reset by peer

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by JenGoldstrich** [comment]
Hey @rbposborne ARM64 Images are currently not supported by the Azure-ARM builder as you've pointed out, we have an open issue https://github.com/hashicorp/packer-plugin-azure/issues/210 on the Azure plugin to capture this, the short version of why this doesn't work is that Azure Console doesn't allow capturing Arm64 VMs into a managed image, only share as VM image version, and we currently don't support publishing an image to a SIG without also publishing a managed image and are actively working on a fix, please feel free to follow up on that issue/this PR https://github.com/hashicorp/packer-plugin-azure/pull/242 that implements this functionality.

**Comment by cfullen11** [comment]
@JenGoldstrich I have read through this conversation and the change of 210 but still a bit confused on what was resolved.  Should I expect linux arm64 images to publish to a compute gallery?  I am still seeing
