### ISSUE TITLE
HCP plugin crash while running `terraform plan`

### ISSUE THREAD

**Issue by StamenchoBog** [hashicorp/packer#12477]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

After running terraform plan, to get a speculative plan, the error that the Packer plugin displays is provided below. I have integrated HCP and Packer with Terraform to fetch AMIs that I use to spin my application. Tried moving back to an older and a newer version of the HCP plugin, but the error still persists.

#### Reproduction Steps

1. Integrate HCP plugin within Terraform
2. Use `hcp_packer_image` data block to fetch the AMI used to provision the application server.
3. Run remote `terraform plan`, and the error is displayed in the TF Cloud logs for that plan.

### HCP plugin version

From `v0.61.0_x5`

### Log Fragments and crash.log files

The following error below is displayed on stage Plan in TF Cloud when trying to run a remote speculative plan.
```
Stack trace from the terraform-provider-hcp_v0.61.0_x5 plugin:

panic: interface conversion: error is *url.Error, not *packer_service.PackerServiceGetChannelDefault

goroutine 74 [running]:
github.com/hashicorp/terraform-provider-hcp/internal/clients.GetPackerChannelBySlug({0x1124088?, 0x6?}, 0xc00061e0e0, 0xc000397390, {0xc00048ee10, 0x9}, {0xc00048ee40, 0x6})
github.com/hashicorp/terraform-provider-hcp/internal/clients/packer.go:28 +0x1dc
github.com/hashicorp/terraform-provider-hcp/internal/provider.dataSourcePackerImageRead({0x12775c8, 0xc000696ba0}, 0x0?, {0xf5d2e0?, 0xc00061e0e0})
github.com/hashicorp/terraform-provider-hcp/internal/provider/data_source_packer_image.go:153 +0x5b0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000247dc0, {0x1277600, 0xc00034ed50}, 0xd?, {0xf5d2e0, 0xc00061e0e0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000247dc0, {0x1277600, 0xc00034ed50}, 0xc00017b100, {0xf5d2e0, 0xc00061e0e0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000298db0, {0x1277600?, 0xc00034ec30?}, 0xc0000a6dc0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1195 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0006a63c0, {0x1277600?, 0xc0006a5b00?}, 0xc000528aa0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1098480?, 0xc0006a63c0}, {0x1277600, 0xc0006a5b00}, 0xc0006043f0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x127a5a0, 0xc000103380}, 0xc0001ff8c0, 0xc000117a70, 0x1a87770, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1336 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x127a5a0, 0xc000103380}, 0xc0001ff8c0, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1704 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-hcp_v0.61.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Also under diagnostics section the error is displayed in red, with the following text:
```
Error: Plugin did not respond
with data.hcp_packer_image.advanced_ubuntu_ami
on launch_templates.tf line 81, in data "hcp_packer_image" "advanced_ubuntu_ami":
data "hcp_packer_image" "advanced_ubuntu_ami" {
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
```

**Comment by nywilken** [comment]
Hi @StamenchoBog thanks for reaching out. I'm going to move this issue to the TF provider repo and have a member of the team take a look. Do you have a sample configuration that we can use to reproduce the issue?
