### ISSUE TITLE
Packer Crashed during building eks anywhere ubuntu 22.04 image on bare metal machine

### ISSUE THREAD

**Issue by ekaraboga** [hashicorp/packer#13207]
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

In my case i am trying to build ubuntu 22.04 image on a bare metal machine (ubuntu 22.04). I am getting following error.

----------------
Warning: Bundled plugins used

This template relies on the use of plugins bundled into the Packer binary.
The practice of bundling external plugins into Packer will be removed in an
upcoming version.

To remove this warning and ensure builds keep working you can install these
external plugins with the 'packer plugins install' command

* packer plugins install github.com/hashicorp/qemu

Alternatively, if you upgrade your templates to HCL2, you can use 'packer init'
with a 'required_plugins' block to automatically install external plugins.

You can try HCL2 by running 'packer hcl2_upgrade
/root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/raw/packe
r.json'

qemu: output will be in this color.

==> qemu: Retrieving ISO
==> qemu: Trying https://releases.ubuntu.com/22.04.5/ubuntu-22.04.5-live-server-amd64.iso
==> qemu: Trying https://releases.ubuntu.com/22.04.5/ubuntu-22.04.5-live-server-amd64.iso?checksum=sha256%3A
9bc6028870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0
==> qemu: https://releases.ubuntu.com/22.04.5/ubuntu-22.04.5-live-server-amd64.iso?checksum=sha256%3A9bc6028
870aef3f74f4e16b900008179e78b130e6b0b9a140635434a46aa98b0 => /root/.cache/packer/c968bbbeb22702b3f10a07276c8ca0672
0e80c4c.iso
==> qemu: Starting HTTP server on port 8529
==> qemu: Found port for communicator (SSH, WinRM, etc): 2773.
==> qemu: Looking for available port between 5900 and 6000 on 127.0.0.1
==> qemu: Starting VM, booting from CD-ROM
    qemu: The VM will be run headless, without a GUI. If you want to
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: vnc://127.0.0.1:5993
==> qemu: Waiting 10s for boot...
==> qemu: Connecting to VM via VNC (127.0.0.1:5993)
==> qemu: Typing the boot commands over VNC...
    qemu: Not using a NetBridge -- skipping StepWaitGuestAddress
==> qemu: Using SSH communicator to connect: 127.0.0.1
==> qemu: Waiting for SSH to become available...
==> qemu: Connected to SSH!
==> qemu: Provisioning with shell script: ./packer/files/flatcar/scripts/bootstrap-flatcar.sh
==> qemu: Setting a 30m0s timeout for the next provisioner...
==> qemu: Provisioning with Ansible...
    qemu: Setting up proxy adapter for Ansible....
==> qemu: Executing Ansible: ansible-playbook -e packer_build_name="qemu" -e packer_builder_type=qemu -e pac
ker_http_addr=10.0.2.2:8529 --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars containerd_url=https://anywhere-
assets.eks.amazonaws.com/releases/bundles/81/artifacts/containerd/v1.7.23/containerd-linux-amd64.tar.gz containerd
_sha256=0c87f055da3f577da392a8b7cb5951644c5ed6fd7325ead59ca1b5be70c5c10b pause_image=public.ecr.aws/eks-distro/kub
ernetes/pause:v1.29.9-eks-1-29-24 containerd_additional_settings= containerd_cri_socket=/var/run/containerd/contai
nerd.sock containerd_version=1.7.20 containerd_wasm_shims_url=https://github.com/deislabs/containerd-wasm-shims/re
leases/download/v0.11.1/containerd-wasm-shims-<RTVERSION>-<SHIM>-linux-x86_64.tar.gz containerd_wasm_shims_version
=v0.11.1 containerd_wasm_shims_sha256={"lunatic":"7054bc882db755ce5f3ded46d114bfd4e0a318e437fa18a2601295d20b616b32
","slight":"a6ea87d965037933a7d9edb5e20cfc175265c8e1ca92a16535f1f3c3f376f5b0","spin":"dcffedb8e4d2f585a851b3de489f
a1e8a0054ec0ad72cf111c623623919245d0","wws":"e917f90692d798d80873aa0f37990c7d652f2846129d64fecbfd41ffa77799b8"} co
ntainerd_wasm_shims_runtimes="" containerd_wasm_shims_runtime_versions="{"lunatic":"v1","slight":"v1","spin":"v2",
"wws":"v1"}" crictl_url=https://anywhere-assets.eks.amazonaws.com/releases/bundles/81/artifacts/cri-tools/v1.31.1/
cri-tools-linux-amd64.tar.gz crictl_sha256=bcc9adb89922be72590508f63a399cbae2f02e1198e4ee7fe7bef5197f3843d3 crictl
_source_type=http custom_role_names="" firstboot_custom_roles_pre="" firstboot_custom_roles_post="" node_custom_ro
les_pre="" node_custom_roles_post="" disable_public_repos=false extra_debs="nfs-common xfsprogs" extra_repos="" ex
tra_rpms="" http_proxy= https_proxy= kubeadm_template=etc/kubeadm.yml kubernetes_apiserver_port=6443 kubernetes_cn
i_http_source=https://distro.eks.amazonaws.com/kubernetes-1-29/releases/24/artifacts/plugins kubernetes_cni_http_c
hecksum=sha256:3cbaa688509c6ba980854ebb33b2e38b84a0978ff9109de8d266b822d3561bb6 kubernetes_goarch=amd64 kubernetes
_http_source=https://distro.eks.amazonaws.com/kubernetes-1-29/releases/24/artifacts/kubernetes kubernetes_containe
r_registry=public.ecr.aws/eks-distro kubernetes_rpm_repo=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/ kubernetes_r
pm_gpg_key=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key kubernetes_rpm_gpg_check=True kuber
netes_deb_repo=https://pkgs.k8s.io/core:/stable:/v1.29/deb/ kubernetes_deb_gpg_key=https://pkgs.k8s.io/core:/stabl
e:/v1.29/deb/Release.key kubernetes_cni_deb_version= kubernetes_cni_rpm_version= kubernetes_cni_semver=v1.4.0 kube
rnetes_cni_source_type=http kubernetes_semver=v1.29.9 kubernetes_source_type=http kubernetes_load_additional_imgs=
true kubernetes_deb_version=1.30.5-1.1 kubernetes_rpm_version=1.30.5 no_proxy= pip_conf_file= python_path= redhat_
epel_rpm=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm epel_rpm_gpg_key= reenable_public_
repos=true remove_extra_repos=false systemd_prefix=/usr/lib/systemd sysusr_prefix=/usr sysusrlocal_prefix=/usr/loc
al load_additional_components=true additional_registry_images=false additional_registry_images_list= ecr_credentia
l_provider=false additional_url_images=true additional_url_images_list=https://distro.eks.amazonaws.com/kubernetes
-1-28/releases/35/artifacts/kubernetes/v1.28.14/bin/linux/amd64/pause.tar additional_executables=false additional_
executables_list= additional_executables_destination_path= additional_s3=false build_target=raw amazon_ssm_agent_r
pm= enable_containerd_audit= kubernetes_enable_automatic_resource_sizing= debug_tools=false ubuntu_repo=https://us
.archive.ubuntu.com/ubuntu ubuntu_security_repo=https://security.ubuntu.com/ubuntu gpu_block_nouveau_loading= etcd
_http_source=https://distro.eks.amazonaws.com/kubernetes-1-29/releases/24/artifacts/etcd/v3.5.15/etcd-linux-amd64-
v3.5.15.tar.gz etcd_version=v3.5.15 etcdadm_http_source=https://anywhere-assets.eks.amazonaws.com/releases/bundles
/81/artifacts/etcdadm/f089d308442c18f487a52d09fd067ae9ac7cd8f2/etcdadm-linux-amd64.tar.gz etcd_sha256=211bb9f542bd
7cda00aed5dcc52b0db83190df6dd309f8547ff8d46bd21c86cb etcdadm_version=v0.1.5 rhsm_server_hostname= rhsm_server_rele
ase_version= rhsm_server_proxy_hostname= rhsm_server_proxy_port= --extra-vars ansible_python_interpreter=/usr/bin/
python3 --extra-vars  --scp-extra-args  -e ansible_ssh_private_key_file=/tmp/ansible-key1911083363 -i /tmp/packer-
provisioner-ansible1610706229 /root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builde
r/images/capi/ansible/firstboot.yml
    qemu:
    qemu: PLAY [Bootstrap Python] ********************************************************
    qemu:
    qemu: TASK [Check if Python is installed] ********************************************
    qemu: ok: [default]
    qemu:
    qemu: PLAY [all] *********************************************************************
    qemu:
    qemu: TASK [Gathering Facts] *********************************************************
    qemu: ok: [default]
    qemu:
    qemu: TASK [ansible.builtin.include_role : firstboot] ********************************
    qemu:
    qemu: TASK [setup : Put templated sources.list in place] *****************************
    qemu: changed: [default]
    qemu:
    qemu: TASK [setup : Put templated apt.conf.d/90proxy in place when defined] **********
    qemu: changed: [default]
    qemu: FAILED - RETRYING: [default]: Perform a dist-upgrade (5 retries left).
    qemu: FAILED - RETRYING: [default]: Perform a dist-upgrade (4 retries left).
    qemu: FAILED - RETRYING: [default]: Perform a dist-upgrade (3 retries left).
    qemu: FAILED - RETRYING: [default]: Perform a dist-upgrade (2 retries left).
    qemu: FAILED - RETRYING: [default]: Perform a dist-upgrade (1 retries left).
    qemu:
    qemu: TASK [setup : Perform a dist-upgrade] ******************************************
    qemu: fatal: [default]: FAILED! => {"attempts": 5, "changed": false, "msg": "Failed to update apt cache:
 unknown reason"}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=4    changed=2    unreachable=0    failed=1    skipped=64   rescue
d=0    ignored=0
    qemu:
==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: exit status 2", retrying w
ith 5 trie(s) left
==> qemu: Setting a 30m0s timeout for the next provisioner...
==> qemu: Provisioning with Ansible...
    qemu: Setting up proxy adapter for Ansible....
==> qemu: Executing Ansible: ansible-playbook -e packer_build_name="qemu" -e packer_builder_type=qemu -e pac
ker_http_addr=10.0.2.2:8529 --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars containerd_url=https://anywhere-
assets.eks.amazonaws.com/releases/bundles/81/artifacts/containerd/v1.7.23/containerd-linux-amd64.tar.gz containerd
_sha256=0c87f055da3f577da392a8b7cb5951644c5ed6fd7325ead59ca1b5be70c5c10b pause_image=public.ecr.aws/eks-distro/kub
ernetes/pause:v1.29.9-eks-1-29-24 containerd_additional_settings= containerd_cri_socket=/var/run/containerd/contai
nerd.sock containerd_version=1.7.20 containerd_wasm_shims_url=https://github.com/deislabs/containerd-wasm-shims/re
leases/download/v0.11.1/containerd-wasm-shims-<RTVERSION>-<SHIM>-linux-x86_64.tar.gz containerd_wasm_shims_version
=v0.11.1 containerd_wasm_shims_sha256={"lunatic":"7054bc882db755ce5f3ded46d114bfd4e0a318e437fa18a2601295d20b616b32
","slight":"a6ea87d965037933a7d9edb5e20cfc175265c8e1ca92a16535f1f3c3f376f5b0","spin":"dcffedb8e4d2f585a851b3de489f
a1e8a0054ec0ad72cf111c623623919245d0","wws":"e917f90692d798d80873aa0f37990c7d652f2846129d64fecbfd41ffa77799b8"} co
ntainerd_wasm_shims_runtimes="" containerd_wasm_shims_runtime_versions="{"lunatic":"v1","slight":"v1","spin":"v2",
"wws":"v1"}" crictl_url=https://anywhere-assets.eks.amazonaws.com/releases/bundles/81/artifacts/cri-tools/v1.31.1/
cri-tools-linux-amd64.tar.gz crictl_sha256=bcc9adb89922be72590508f63a399cbae2f02e1198e4ee7fe7bef5197f3843d3 crictl
_source_type=http custom_role_names="" firstboot_custom_roles_pre="" firstboot_custom_roles_post="" node_custom_ro
les_pre="" node_custom_roles_post="" disable_public_repos=false extra_debs="nfs-common xfsprogs" extra_repos="" ex
tra_rpms="" http_proxy= https_proxy= kubeadm_template=etc/kubeadm.yml kubernetes_apiserver_port=6443 kubernetes_cn
i_http_source=https://distro.eks.amazonaws.com/kubernetes-1-29/releases/24/artifacts/plugins kubernetes_cni_http_c
hecksum=sha256:3cbaa688509c6ba980854ebb33b2e38b84a0978ff9109de8d266b822d3561bb6 kubernetes_goarch=amd64 kubernetes
_http_source=https://distro.eks.amazonaws.com/kubernetes-1-29/releases/24/artifacts/kubernetes kubernetes_containe
r_registry=public.ecr.aws/eks-distro kubernetes_rpm_repo=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/ kubernetes_r
pm_gpg_key=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key kubernetes_rpm_gpg_check=True kuber
netes_deb_repo=https://pkgs.k8s.io/core:/stable:/v1.29/deb/ kubernetes_deb_gpg_key=https://pkgs.k8s.io/core:/stabl
e:/v1.29/deb/Release.key kubernetes_cni_deb_version= kubernetes_cni_rpm_version= kubernetes_cni_semver=v1.4.0 kube
rnetes_cni_source_type=http kubernetes_semver=v1.29.9 kubernetes_source_type=http kubernetes_load_additional_imgs=
true kubernetes_deb_version=1.30.5-1.1 kubernetes_rpm_version=1.30.5 no_proxy= pip_conf_file= python_path= redhat_
epel_rpm=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm epel_rpm_gpg_key= reenable_public_
repos=true remove_extra_repos=false systemd_prefix=/usr/lib/systemd sysusr_prefix=/usr sysusrlocal_prefix=/usr/loc
al load_additional_components=true additional_registry_images=false additional_registry_images_list= ecr_credentia
l_provider=false additional_url_images=true additional_url_images_list=https://distro.eks.amazonaws.com/kubernetes
-1-28/releases/35/artifacts/kubernetes/v1.28.14/bin/linux/amd64/pause.tar additional_executables=false additional_
executables_list= additional_executables_destination_path= additional_s3=false build_target=raw amazon_ssm_agent_r
pm= enable_containerd_audit= kubernetes_enable_automatic_resource_sizing= debug_tools=false ubuntu_repo=https://us
.archive.ubuntu.com/ubuntu ubuntu_security_repo=https://security.ubuntu.com/ubuntu gpu_block_nouveau_loading= etcd
_http_source=https://distro.eks.amazonaws.com/kubernetes-1-29/releases/24/artifacts/etcd/v3.5.15/etcd-linux-amd64-
v3.5.15.tar.gz etcd_version=v3.5.15 etcdadm_http_source=https://anywhere-assets.eks.amazonaws.com/releases/bundles
/81/artifacts/etcdadm/f089d308442c18f487a52d09fd067ae9ac7cd8f2/etcdadm-linux-amd64.tar.gz etcd_sha256=211bb9f542bd
7cda00aed5dcc52b0db83190df6dd309f8547ff8d46bd21c86cb etcdadm_version=v0.1.5 rhsm_server_hostname= rhsm_server_rele
ase_version= rhsm_server_proxy_hostname= rhsm_server_proxy_port= --extra-vars ansible_python_interpreter=/usr/bin/
python3 --extra-vars  --scp-extra-args  -e ansible_ssh_private_key_file=/tmp/ansible-key3409353168 -i /tmp/packer-
provisioner-ansible589560926 /root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder
/images/capi/ansible/firstboot.yml
    qemu:
    qemu: PLAY [Bootstrap Python] ********************************************************
    qemu:
    qemu: TASK [Check if Python is installed] ********************************************
    qemu: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh
: Connection timed out during banner exchange\r\nConnection to 127.0.0.1 port 34227 timed out", "unreachable": tru
e}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescue
d=0    ignored=0
    qemu:
==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: exit status 2", retrying w
ith 4 trie(s) left
==> qemu: Setting a 30m0s timeout for the next provisioner...
==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: exit status 2", retrying w
ith 3 trie(s) left
==> qemu: Setting a 30m0s timeout for the next provisioner...
==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: exit status 2", retrying w
ith 2 trie(s) left
==> qemu: Setting a 30m0s timeout for the next provisioner...
==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: exit status 2", retrying w
ith 1 trie(s) left
==> qemu: Setting a 30m0s timeout for the next provisioner...
==> qemu: retry limit reached.
==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
==> qemu: Deleting output directory...
Build 'qemu' errored after 37 minutes 27 seconds: Error executing Ansible: Non-zero exit status: exit status
 2

==> Wait completed after 37 minutes 27 seconds

==> Some builds didn't complete successfully and had errors:
--> qemu: Error executing Ansible: Non-zero exit status: exit status 2

==> Builds finished but no artifacts were created.
panic: close of closed channel
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: goroutine 784 [running]:
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-ansib
le/provisioner/ansible.(*Provisioner).Provision.func1()
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin
-ansible/provisioner/ansible/provisioner.go:643 +0x96
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-ansib
le/provisioner/ansible.(*Provisioner).Provision(0xc0001ba580, {0x0?, 0x0?}, {0x1391fd0, 0xc0002ba6c0}, {0x138df40,
 0xc000480500}, 0xc00067c2a0)
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin
-ansible/provisioner/ansible/provisioner.go:710 +0xaba
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/r
pc.(*ProvisionerServer).Provision(0xc000644040, 0xc000764300, 0x1?)
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 	github.com/hashicorp/packer-plugin
-sdk@v0.5.4/rpc/provisioner.go:91 +0x1c9
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: reflect.Value.call({0xc0000e8720?, 0xc00
06480c8?, 0x13?}, {0x100c7c6, 0x4}, {0xc0006fbef8, 0x3, 0x3?})
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 	reflect/value.go:596 +0xce7
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: reflect.Value.Call({0xc0000e8720?, 0xc00
06480c8?, 0x0?}, {0xc00075e6f8?, 0x0?, 0x0?})
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 	reflect/value.go:380 +0xb9
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: net/rpc.(*service).call(0xc000644080, 0x
0?, 0x0?, 0xc000634060, 0xc000650180, 0x0?, {0xe1bac0?, 0xc000764300?, 0x0?}, {0xe305a0, ...}, ...)
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 	net/rpc/server.go:382 +0x211
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: created by net/rpc.(*Server).ServeCodec 
in goroutine 1
2024/11/10 11:40:02 packer-plugin-ansible_v1.1.2_x5.0_linux_amd64 plugin: 	net/rpc/server.go:479 +0x410
2024/11/10 11:40:02 /root/.packer.d/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.1.2_x5.0_linux_a
md64: plugin process exited
2024/11/10 11:40:02 ui: ==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: ex
it status 2", retrying with 4 trie(s) left
2024/11/10 11:40:02 ui: ==> qemu: Setting a 30m0s timeout for the next provisioner...
2024/11/10 11:40:02 ui: ==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: ex
it status 2", retrying with 3 trie(s) left
2024/11/10 11:40:02 ui: ==> qemu: Setting a 30m0s timeout for the next provisioner...
2024/11/10 11:40:02 ui: ==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: ex
it status 2", retrying with 2 trie(s) left
2024/11/10 11:40:02 ui: ==> qemu: Setting a 30m0s timeout for the next provisioner...
2024/11/10 11:40:02 Cancelling provisioner after context cancellation context canceled
2024/11/10 11:40:02 Error cancelling provisioner: connection is shut down
2024/11/10 11:40:02 ui: ==> qemu: Provisioner failed with "Error executing Ansible: Non-zero exit status: ex
it status 2", retrying with 1 trie(s) left
2024/11/10 11:40:02 ui: ==> qemu: Setting a 30m0s timeout for the next provisioner...
2024/11/10 11:40:02 Cancelling provisioner after context cancellation context canceled
2024/11/10 11:40:02 Error cancelling provisioner: connection is shut down
2024/11/10 11:40:02 ui: ==> qemu: retry limit reached.
2024/11/10 11:40:02 [INFO] (telemetry) ending ansible
2024/11/10 11:40:02 ui: ==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present.
..
2024/11/10 11:40:02 packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:5993: use of c
losed network connection
2024/11/10 11:40:02 packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:2773: use of c
losed network connection
2024/11/10 11:40:02 ui: ==> qemu: Deleting output directory...
2024/11/10 11:40:02 [INFO] (telemetry) ending qemu
2024/11/10 11:40:02 ui error: Build 'qemu' errored after 37 minutes 27 seconds: Error executing Ansible: Non
-zero exit status: exit status 2
2024/11/10 11:40:02 ui: 
==> Wait completed after 37 minutes 27 seconds
2024/11/10 11:40:02 machine readable: error-count []string{"1"}
2024/11/10 11:40:02 ui error: 
==> Some builds didn't complete successfully and had errors:
2024/11/10 11:40:02 machine readable: qemu,error []string{"Error executing Ansible: Non-zero exit status: exit sta
tus 2"}
2024/11/10 11:40:02 ui error: --> qemu: Error executing Ansible: Non-zero exit status: exit status 2
2024/11/10 11:40:02 ui: 
==> Builds finished but no artifacts were created.
2024/11/10 11:40:02 [INFO] (telemetry) Finalizing.
2024/11/10 11:40:02 waiting for all plugin processes to complete...
2024/11/10 11:40:02 /root/.packer.d/plugins/github.com/hashicorp/ansible/packer-plugin-ansible_v1.1.2_x5.0_linux_a
md64: plugin process exited
2024/11/10 11:40:02 /root/.packer.d/plugins/github.com/yaleuniversity/goss/packer-plugin-goss_v3.2.13_x5.0_linux_a
md64: plugin process exited
2024/11/10 11:40:02 /root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/c
api/.local/bin/packer: plugin process exited
2024/11/10 11:40:02 /root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/c
api/.local/bin/packer: plugin process exited
2024/11/10 11:40:02 /root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/c
api/.local/bin/packer: plugin process exited
2024/11/10 11:40:02 /root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/c
api/.local/bin/packer: plugin process exited
2024/11/10 11:40:02 /root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/c
api/.local/bin/packer: plugin process exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
make[1]: *** [Makefile:559: build-raw-ubuntu-2204-efi] Error 1
make[1]: Leaving directory '/root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/
images/capi'
make: *** [Makefile:419: local-build-raw-ubuntu-2204] Error 2
make: Leaving directory '/root/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder'

**Comment by kp2099** [comment]
Hi @ekaraboga, could you share an example template you've used along with any other relevant details? This will help us better understand the issue.

**Comment by milgelren** [comment]
Closing this issue due to lack of a sufficient information to reproduce it. Feel free to open a new one in case you are still facing hurdles using Packer
