### ISSUE TITLE
ansible remote provisioner times out before WINRM becomes available

### ISSUE THREAD

**Issue by dayglo** [hashicorp/packer#4827]
- Packer version 0.12.3
- Host platform vmware fusion on MACOS Sierra 10.12.3

I have set up the ansible remote provisioner to use winrm as per the instructions (with the extra-vars and the connection plugin etc).

```
{
	"builders": [
		{
			"type": "vmware-vmx",
			"source_path": "../packer-windows-2/output-vmware-iso/packer-vmware-iso.vmx",
			"communicator": "winrm",
			"headless": false,
			"boot_wait": "1m",
			"winrm_username": "vagrant",
			"winrm_password": "vagrant",
			"winrm_use_ssl": false,
			"winrm_insecure": true,
			"winrm_timeout": "6h",
			"shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
			"vnc_port_min": 5900,
			"vnc_port_max": 5980,
			"output_directory":"output2",
			"floppy_files": [
			],
			"vmx_data": {
				"RemoteDisplay.vnc.enabled": "false",
				"RemoteDisplay.vnc.port": "5900",
				"memsize": "6000",
				"numvcpus": "2",
				"scsi0.virtualDev": "lsisas1068"
			}
		}
	],
	"provisioners": [

		{
			"type": "windows-shell",
			"inline":"echo grrrrr > c:/before.txt"
		},
 		{
			"type":  "ansible",
			"playbook_file": "./oo.yml",
			"extra_arguments": [
				"-vvvv",
				"--connection", "packer",
				"--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"
			]
      	},		
		{
			"type": "windows-shell",
			"inline":"echo gah > c:/after.txt"
		}
	],
	"post-processors":[

	]
}

```

When I run my packer build in debug mode, if i wait for a minute or two (after the machine comes up) it works fine. The embedded proxy thing starts up ssh connects, and the playbook runs ok. 

But, if i run packer without the -debug switch the first EXEC ssh command just sits there then times out:

```
 vmware-vmx: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=55436 -o 'IdentityFile="/var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/ansible-key754074802"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gee -o ConnectTimeout=10 -o ControlPath=/Users/gee/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAKABHAGUAdAAtAEwAbwBjAGEAdABpAG8AbgApAC4AUABhAHQAaAA='
==> vmware-vmx: unknown error Post http://192.168.172.131:5985/wsman: read tcp 192.168.172.1:55426->192.168.172.131:5985: read: operation timed out
```

Is there a way to check the ssh proxy is ready before trying to run the provisioner?

Or is there a way to increase the timeout in that command?

Here are the full logs for both a fail and a success:

**Failure, not using debug mode:**
```
gee@ziggurat ~/D/w/a/H/f/packedOO> packer build  oo_1020.json 
vmware-vmx output will be in this color.

==> vmware-vmx: Cloning source VM...
==> vmware-vmx: Starting virtual machine...
==> vmware-vmx: Waiting 1m0s for boot...
==> vmware-vmx: Connecting to VM via VNC
==> vmware-vmx: Typing the boot command over VNC...
==> vmware-vmx: Waiting for WinRM to become available...
==> vmware-vmx: Connected to WinRM!
==> vmware-vmx: Provisioning with windows-shell...
==> vmware-vmx: Provisioning with shell script: /var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/packer-windows-shell-provisioner770967716
    vmware-vmx:
    vmware-vmx: C:\Users\vagrant>echo gah  1>c:/gah.txt
==> vmware-vmx: Provisioning with Ansible...
    vmware-vmx: No config file found; using defaults
    vmware-vmx: Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
    vmware-vmx:
    vmware-vmx: PLAYBOOK: oo.yml ***************************************************************
    vmware-vmx: 1 plays in /Users/gee/Dropbox (Personal)/work/al/HPE/future/packedOO/oo.yml
    vmware-vmx:
    vmware-vmx: PLAY [default] *****************************************************************
    vmware-vmx:
    vmware-vmx: TASK [Create directory structure] **********************************************
    vmware-vmx: task path: /Users/gee/Dropbox (Personal)/work/al/HPE/future/packedOO/oo.yml:6
    vmware-vmx: Using module file /usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/modules/core/windows/win_file.ps1
    vmware-vmx: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: gee
    vmware-vmx: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=55436 -o 'IdentityFile="/var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/ansible-key754074802"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gee -o ConnectTimeout=10 -o ControlPath=/Users/gee/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAKABHAGUAdAAtAEwAbwBjAGEAdABpAG8AbgApAC4AUABhAHQAaAA='
==> vmware-vmx: unknown error Post http://192.168.172.131:5985/wsman: read tcp 192.168.172.1:55426->192.168.172.131:5985: read: operation timed out
    vmware-vmx: An exception occurred during task execution. The full traceback is:
    vmware-vmx: Traceback (most recent call last):
    vmware-vmx:   File "/usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 126, in run
    vmware-vmx:     res = self._execute()
    vmware-vmx:   File "/usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 511, in _execute
    vmware-vmx:     result = self._handler.run(task_vars=variables)
    vmware-vmx:   File "/usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run
    vmware-vmx:     results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
    vmware-vmx:   File "/usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 584, in _execute_module
    vmware-vmx:     tmp = self._make_tmp_path(remote_user)
    vmware-vmx:   File "/usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 224, in _make_tmp_path
    vmware-vmx:     tmpdir =  self._remote_expand_user(C.DEFAULT_REMOTE_TMP, sudoable=False)
    vmware-vmx:   File "/usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 506, in _remote_expand_user
    vmware-vmx:     initial_fragment = data['stdout'].strip().splitlines()[-1]
    vmware-vmx: IndexError: list index out of range
    vmware-vmx: fatal: [default]: FAILED! => {
    vmware-vmx:     "failed": true,
    vmware-vmx:     "msg": "Unexpected failure during module execution.",
    vmware-vmx:     "stdout": ""
    vmware-vmx: }
    vmware-vmx: 	to retry, use: --limit @/Users/gee/Dropbox (Personal)/work/al/HPE/future/packedOO/oo.retry
    vmware-vmx:
    vmware-vmx: PLAY RECAP *********************************************************************
    vmware-vmx: default                    : ok=0    changed=0    unreachable=0    failed=1
    vmware-vmx:
==> vmware-vmx: Stopping virtual machine...
==> vmware-vmx: Deleting output directory...
Build 'vmware-vmx' errored: Error executing Ansible: Non-zero exit status: exit status 2

==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: Error executing Ansible: Non-zero exit status: exit status 2

==> Builds finished but no artifacts were created.

````

**Running in debug mode, works fine:**
````
gee@ziggurat ~/D/w/a/H/f/packedOO> packer build -debug oo_1020.json 
Debug mode enabled. Builds will not be parallelized.
vmware-vmx output will be in this color.

==> vmware-vmx: Pausing after run of step 'StepPrepareTools'. Press enter to continue. 
==> vmware-vmx: Pausing after run of step 'StepOutputDir'. Press enter to continue. 
==> vmware-vmx: Pausing after run of step 'StepCreateFloppy'. Press enter to continue. 
==> vmware-vmx: Cloning source VM...
==> vmware-vmx: Pausing after run of step 'StepCloneVMX'. Press enter to continue. 
==> vmware-vmx: Pausing after run of step 'StepConfigureVMX'. Press enter to continue. 
==> vmware-vmx: Pausing after run of step 'StepSuppressMessages'. Press enter to continue. 
==> vmware-vmx: Pausing after run of step 'StepHTTPServer'. Press enter to continue. 
==> vmware-vmx: Pausing after run of step 'StepConfigureVNC'. Press enter to continue. 
==> vmware-vmx: Starting virtual machine...
==> vmware-vmx: Waiting 1m0s for boot...
==> vmware-vmx: Pausing after run of step 'StepRun'. Press enter to continue. 
==> vmware-vmx: Connecting to VM via VNC
==> vmware-vmx: Typing the boot command over VNC...
==> vmware-vmx: Pausing after run of step 'StepTypeBootCommand'. Press enter to continue. 
==> vmware-vmx: Waiting for WinRM to become available...
==> vmware-vmx: Connected to WinRM!
==> vmware-vmx: Pausing after run of step 'StepConnect'. Press enter to continue. 
==> vmware-vmx: Pausing after run of step 'StepUploadTools'. Press enter to continue. 
==> vmware-vmx: Provisioning with windows-shell...
==> vmware-vmx: Provisioning with shell script: /var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/packer-windows-shell-provisioner575147994
    vmware-vmx:
    vmware-vmx: C:\Users\vagrant>echo gah  1>c:/gah.txt
==> vmware-vmx: Provisioning with Ansible...
    vmware-vmx: No config file found; using defaults
    vmware-vmx: Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
    vmware-vmx:
    vmware-vmx: PLAYBOOK: oo.yml ***************************************************************
    vmware-vmx: 1 plays in /Users/gee/Dropbox (Personal)/work/al/HPE/future/packedOO/oo.yml
    vmware-vmx:
    vmware-vmx: PLAY [default] *****************************************************************
    vmware-vmx:
    vmware-vmx: TASK [Create directory structure] **********************************************
    vmware-vmx: task path: /Users/gee/Dropbox (Personal)/work/al/HPE/future/packedOO/oo.yml:6
    vmware-vmx: Using module file /usr/local/Cellar/ansible/2.2.2.0/libexec/lib/python2.7/site-packages/ansible/modules/core/windows/win_file.ps1
    vmware-vmx: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: gee
    vmware-vmx: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=56224 -o 'IdentityFile="/var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/ansible-key807517613"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gee -o ConnectTimeout=10 -o ControlPath=/Users/gee/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAKABHAGUAdAAtAEwAbwBjAGEAdABpAG8AbgApAC4AUABhAHQAaAA='
    vmware-vmx: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: gee
    vmware-vmx: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=56224 -o 'IdentityFile="/var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/ansible-key807517613"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gee -o ConnectTimeout=10 -o ControlPath=/Users/gee/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgAoAE4AZQB3AC0ASQB0AGUAbQAgAC0AVAB5AHAAZQAgAEQAaQByAGUAYwB0AG8AcgB5ACAALQBQAGEAdABoACAAJABlAG4AdgA6AHQAZQBtAHAAIAAtAE4AYQBtAGUAIAAiAGEAbgBzAGkAYgBsAGUALQB0AG0AcAAtADEANAA5ADMAMAA1ADEAMwAxADgALgA2ADUALQAxADEAMQAxADUANgA2ADcANwA4ADMAOAA1ADgAMwAiACkALgBGAHUAbABsAE4AYQBtAGUAIAB8ACAAVwByAGkAdABlAC0ASABvAHMAdAAgAC0AUwBlAHAAYQByAGEAdABvAHIAIAAnACcAOwA='
    vmware-vmx: <127.0.0.1> PUT /var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/tmpoi9yWW TO 'C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1493051318.65-111156677838583\win_file.ps1'
    vmware-vmx: <127.0.0.1> SSH: EXEC scp -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=56224 -o 'IdentityFile="/var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/ansible-key807517613"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gee -o ConnectTimeout=10 -o ControlPath=/Users/gee/.ansible/cp/ansible-ssh-%h-%p-%r /var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/tmpoi9yWW '[127.0.0.1]:'"'"''"'"'"'"'"'"'"'"'C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1493051318.65-111156677838583\win_file.ps1'"'"'"'"'"'"'"'"''"'"''
    vmware-vmx: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: gee
    vmware-vmx: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=56224 -o 'IdentityFile="/var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/ansible-key807517613"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=gee -o ConnectTimeout=10 -o ControlPath=/Users/gee/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBpAGMAdABNAG8AZABlACAALQBWAGUAcgBzAGkAbwBuACAATABhAHQAZQBzAHQACgBUAHIAeQAKAHsACgAmACAAJwBDADoAXABVAHMAZQByAHMAXAB2AGEAZwByAGEAbgB0AFwAQQBwAHAARABhAHQAYQBcAEwAbwBjAGEAbABcAFQAZQBtAHAAXABhAG4AcwBpAGIAbABlAC0AdABtAHAALQAxADQAOQAzADAANQAxADMAMQA4AC4ANgA1AC0AMQAxADEAMQA1ADYANgA3ADcAOAAzADgANQA4ADMAXAB3AGkAbgBfAGYAaQBsAGUALgBwAHMAMQAnAAoAfQAKAEMAYQB0AGMAaAAKAHsACgAkAF8AbwBiAGoAIAA9ACAAQAB7ACAAZgBhAGkAbABlAGQAIAA9ACAAJAB0AHIAdQBlACAAfQAKAEkAZgAgACgAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBHAGUAdABUAHkAcABlACkACgB7AAoAJABfAG8AYgBqAC4AQQBkAGQAKAAnAG0AcwBnACcALAAgACQAXwAuAEUAeABjAGUAcAB0AGkAbwBuAC4ATQBlAHMAcwBhAGcAZQApAAoAfQAKAEUAbABzAGUACgB7AAoAJABfAG8AYgBqAC4AQQBkAGQAKAAnAG0AcwBnACcALAAgACQAXwAuAFQAbwBTAHQAcgBpAG4AZwAoACkAKQAKAH0ACgBJAGYAIAAoACQAXwAuAEkAbgB2AG8AYwBhAHQAaQBvAG4ASQBuAGYAbwAuAFAAbwBzAGkAdABpAG8AbgBNAGUAcwBzAGEAZwBlACkACgB7AAoAJABfAG8AYgBqAC4AQQBkAGQAKAAnAGUAeABjAGUAcAB0AGkAbwBuACcALAAgACQAXwAuAEkAbgB2AG8AYwBhAHQAaQBvAG4ASQBuAGYAbwAuAFAAbwBzAGkAdABpAG8AbgBNAGUAcwBzAGEAZwBlACkACgB9AAoARQBsAHMAZQBJAGYAIAAoACQAXwAuAFMAYwByAGkAcAB0AFMAdABhAGMAawBUAHIAYQBjAGUAKQAKAHsACgAkAF8AbwBiAGoALgBBAGQAZAAoACcAZQB4AGMAZQBwAHQAaQBvAG4AJwAsACAAJABfAC4AUwBjAHIAaQBwAHQAUwB0AGEAYwBrAFQAcgBhAGMAZQApAAoAfQAKAFQAcgB5AAoAewAKACQAXwBvAGIAagAuAEEAZABkACgAJwBlAHIAcgBvAHIAXwByAGUAYwBvAHIAZAAnACwAIAAoACQAXwAgAHwAIABDAG8AbgB2AGUAcgB0AFQAbwAtAEoAcwBvAG4AIAB8ACAAQwBvAG4AdgBlAHIAdABGAHIAbwBtAC0ASgBzAG8AbgApACkACgB9AAoAQwBhAHQAYwBoAAoAewAKAH0ACgBFAGMAaABvACAAJABfAG8AYgBqACAAfAAgAEMAbwBuAHYAZQByAHQAVABvAC0ASgBzAG8AbgAgAC0AQwBvAG0AcAByAGUAcwBzACAALQBEAGUAcAB0AGgAIAA5ADkACgBFAHgAaQB0ACAAMQAKAH0ACgBGAGkAbgBhAGwAbAB5ACAAewAgAFIAZQBtAG8AdgBlAC0ASQB0AGUAbQAgACIAQwA6AFwAVQBzAGUAcgBzAFwAdgBhAGcAcgBhAG4AdABcAEEAcABwAEQAYQB0AGEAXABMAG8AYwBhAGwAXABUAGUAbQBwAFwAYQBuAHMAaQBiAGwAZQAtAHQAbQBwAC0AMQA0ADkAMwAwADUAMQAzADEAOAAuADYANQAtADEAMQAxADEANQA2ADYANwA3ADgAMwA4ADUAOAAzACIAIAAtAEYAbwByAGMAZQAgAC0AUgBlAGMAdQByAHMAZQAgAC0ARQByAHIAbwByAEEAYwB0AGkAbwBuACAAUwBpAGwAZQBuAHQAbAB5AEMAbwBuAHQAaQBuAHUAZQAgAH0A'
    vmware-vmx: changed: [default] => {
    vmware-vmx:     "changed": true,
    vmware-vmx:     "invocation": {
    vmware-vmx:         "module_name": "win_file"
    vmware-vmx:     }
    vmware-vmx: }
    vmware-vmx:
    vmware-vmx: PLAY RECAP *********************************************************************
    vmware-vmx: default                    : ok=1    changed=1    unreachable=0    failed=0
    vmware-vmx:
==> vmware-vmx: Provisioning with windows-shell...
==> vmware-vmx: Provisioning with shell script: /var/folders/q1/52bdcv4j64ndk6jmv_djs7vr0000gn/T/packer-windows-shell-provisioner163746577
    vmware-vmx:
    vmware-vmx: C:\Users\vagrant>echo gah  1>c:/gah2.txt
==> vmware-vmx: Executing local command: echo THIS LINE IS DISABLED ovftool -dm=thin --compress=1 "output-vmware-vmx/*.vmx" "output-vmware-vmx/test.ova"
    vmware-vmx: THIS LINE IS DISABLED ovftool -dm=thin --compress=1 output-vmware-vmx/*.vmx output-vmware-vmx/test.ova
==> vmware-vmx: Pausing after run of step 'StepProvision'. Press enter to continue. 

```

**Comment by SwampDragons** [comment]
I think this issue has probably been solved by stricter checking of whether WinRM is available, here: https://github.com/hashicorp/packer/pull/5300

If you still experience this with a recent version of Packer, please let me know. We're about to merge another major improvement to ansible + winRM in the 1.5.6 release: https://github.com/hashicorp/packer/pull/8625 so be sure to upgrade to 1.5.6 once it comes out at the end of this month/beginning of next month.
