### ISSUE TITLE
builder/azure: panic: ssh: cannot decode encrypted private keys (crash)

### ISSUE THREAD

**Issue by beuno** [hashicorp/packer#4841]
Describe the problem and include the following information:

- Packer version: Packer v1.0.0
- Host platform: OSX 10.12.4

Attaching the crash log.
[crash.log.zip](https://github.com/hashicorp/packer/files/961467/crash.log.zip)

**Comment by mwhooker** [comment]
```
2017/04/27 08:50:56 ui: [1;32mazure-arm output will be in this color.[0m
2017/04/27 08:50:56 ui: 
2017/04/27 08:50:56 Build debug mode: false
2017/04/27 08:50:56 Force build: false
2017/04/27 08:50:56 On error: ask
2017/04/27 08:50:56 Preparing build: azure-arm
2017/04/27 08:50:56 packer: panic: ssh: cannot decode encrypted private keys
2017/04/27 08:50:56 packer: 
2017/04/27 08:50:56 packer: goroutine 35 [running]:
2017/04/27 08:50:56 packer: github.com/mitchellh/packer/builder/azure/arm.setSshValues(0xc42028e400, 0x0, 0x0)
2017/04/27 08:50:56 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/azure/arm/config.go:255 +0x4b3
2017/04/27 08:50:56 packer: github.com/mitchellh/packer/builder/azure/arm.newConfig(0xc42027c0c0, 0x2, 0x2, 0x0, 0x0, 0xc4202a0300, 0x209efc0, 0xc42027c3a0, 0x1f5cea0)
2017/04/27 08:50:56 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/azure/arm/config.go:218 +0x294
2017/04/27 08:50:56 packer: github.com/mitchellh/packer/builder/azure/arm.(*Builder).Prepare(0xc42022a030, 0xc42027c0c0, 0x2, 0x2, 0x10ac3a1, 0x1f5cea0, 0x1f5cea0, 0x1, 0x2f30e10)
2017/04/27 08:50:56 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/azure/arm/builder.go:41 +0x4c
2017/04/27 08:50:56 packer: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Prepare(0xc420270000, 0xc42027c080, 0xc42027c360, 0x0, 0x0)
2017/04/27 08:50:56 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:78 +0x5c
2017/04/27 08:50:56 packer: reflect.Value.call(0xc42001cc00, 0xc42000e120, 0x13, 0x22d165e, 0x4, 0xc420273f20, 0x3, 0x3, 0x30, 0xc4200256e8, ...)
2017/04/27 08:50:56 packer: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2017/04/27 08:50:56 packer: reflect.Value.Call(0xc42001cc00, 0xc42000e120, 0x13, 0xc420025720, 0x3, 0x3, 0xc420025748, 0xc42001cb40, 0x0)
2017/04/27 08:50:56 packer: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/04/27 08:50:56 packer: net/rpc.(*service).call(0xc42022c600, 0xc42022c5c0, 0xc4200fc6d8, 0xc420086c00, 0xc4202700e0, 0x1f5ce60, 0xc42027c080, 0x16, 0x1f5cea0, 0xc42027c360, ...)
2017/04/27 08:50:56 packer: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2017/04/27 08:50:56 packer: created by net/rpc.(*Server).ServeCodec
2017/04/27 08:50:56 packer: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
2017/04/27 08:50:56 Build 'azure-arm' prepare failure: unexpected EOF
2017/04/27 08:50:56 ui error: unexpected EOF
2017/04/27 08:50:56 waiting for all plugin processes to complete...
```
