### ISSUE TITLE
Packer crashed when baking image

### ISSUE THREAD

**Issue by bevacqua** [hashicorp/packer#5010]
- packer v0.10.2
- macOS Sierra 10.12.4

```
2017/06/13 14:44:38 packer: 2017/06/13 14:44:38 [INFO] Waiting for SSH, up to timeout: 5m0s
2017/06/13 14:44:38 ui: [1;32m==> amazon-ebs: Waiting for SSH to become available...[0m
2017/06/13 14:44:40 packer: panic: interface conversion: interface {} is **ec2.Instance, not *ec2.Instance
2017/06/13 14:44:40 packer: 
2017/06/13 14:44:40 packer: goroutine 14 [running]:
2017/06/13 14:44:40 packer: panic(0xb5a300, 0xc4202ef9c0)
2017/06/13 14:44:40 packer: 	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
2017/06/13 14:44:40 packer: github.com/mitchellh/packer/builder/amazon/common.SSHHost.func1(0x12bc7a0, 0xc42013a450, 0xc420066340, 0x0, 0xc420414300, 0xc420046ce8)
2017/06/13 14:44:40 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/amazon/common/ssh.go:19 +0x4b5
2017/06/13 14:44:40 packer: github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).waitForSSH(0xc4201f7e00, 0x12bc7a0, 0xc42013a450, 0xc4203928a0, 0x0, 0x0, 0x100000002, 0x20001)
2017/06/13 14:44:40 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:119 +0x244
2017/06/13 14:44:40 packer: github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).Run.func1(0x12bef00, 0xc4203a3120, 0xc4201f3ae0, 0xc4201f3af0, 0xc4201f7e00, 0x12bc7a0, 0xc42013a450, 0xc4203928a0, 0xc42022e3f0)
2017/06/13 14:44:40 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:39 +0x82
2017/06/13 14:44:40 packer: created by github.com/mitchellh/packer/helper/communicator.(*StepConnectSSH).Run
2017/06/13 14:44:40 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/helper/communicator/step_connect_ssh.go:41 +0x1e4
2017/06/13 14:44:40 ui error: [1;31mBuild 'amazon-ebs' errored: unexpected EOF[0m
2017/06/13 14:44:40 Builds completed. Waiting on interrupt barrier...
```

Full log: https://gist.github.com/bevacqua/2c09d2c4b11ca0f27226598589f8b160

**Comment by mwhooker** [comment]
Please update to the latest version of packer, as this has already been fixed

**Comment by bevacqua** [comment]
Figured as much, glad it's already fixed 👍
