### ISSUE TITLE
packer crash when aborting cloudstack build

### ISSUE THREAD

**Issue by rmwiseman** [hashicorp/packer#5386]
As requested by Packer, here's my crash.log.  I pressed ^C to cancel the build during the "Creating instance..." step, and Packer crashed.
[crash.log](https://github.com/hashicorp/packer/files/1333555/crash.log)

**Comment by mwhooker** [comment]
thanks for the report. Here's the stack trace

```
2017/09/26 15:35:15 Running builder: cloudstack
2017/09/26 15:35:15 [INFO] (telemetry) Starting builder cloudstack
2017/09/26 15:35:15 ui: [1;32m==> cloudstack: Preparing config...[0m
2017/09/26 15:35:15 ui: [0;32m    cloudstack: Config has been prepared![0m
2017/09/26 15:35:15 ui: [1;32m==> cloudstack: Not using a keypair[0m
2017/09/26 15:35:15 ui: [1;32m==> cloudstack: Creating instance...[0m
2017/09/26 15:36:10 Stopping build: cloudstack
2017/09/26 15:36:10 packer: 2017/09/26 15:36:10 Received interrupt signal (count: 1). Ignoring.
2017/09/26 15:36:10 Closing stdin because interrupt received.
2017/09/26 15:36:10 packer: 2017/09/26 15:36:10 Received interrupt signal (count: 1). Ignoring.
2017/09/26 15:36:10 packer: 2017/09/26 15:36:10 Received interrupt signal (count: 1). Ignoring.
2017/09/26 15:36:10 ui: [1;32m==> cloudstack: Cancelling the step runner...[0m
2017/09/26 15:36:47 ui: [0;32m    cloudstack: Instance has been created![0m
2017/09/26 15:36:47 ui: [1;32m==> cloudstack: Deleting instance...[0m
2017/09/26 15:36:57 ui: [0;32m    cloudstack: Instance has been deleted![0m
2017/09/26 15:36:57 packer: panic: interface conversion: interface {} is nil, not *cloudstack.CreateTemplateResponse
2017/09/26 15:36:57 packer: 
2017/09/26 15:36:57 packer: goroutine 83 [running]:
2017/09/26 15:36:57 packer: github.com/hashicorp/packer/builder/cloudstack.(*Builder).Run(0xc4202d9080, 0x30ddb40, 0xc4204ac1e0, 0x30d4c40, 0xc4204a8580, 0x30dc440, 0xc420168110, 0x80000000018, 0x28, 0x28, ...)
2017/09/26 15:36:57 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/cloudstack/builder.go:109 +0xe7a
2017/09/26 15:36:57 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc4202ecac0, 0x1, 0xc4201649d0, 0x0, 0x0)
2017/09/26 15:36:57 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:93 +0x1dd
2017/09/26 15:36:57 packer: reflect.Value.call(0xc420177440, 0xc42014c2f8, 0x13, 0x2047aa8, 0x4, 0xc420407f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/09/26 15:36:57 packer: 	/usr/local/go/src/reflect/value.go:434 +0x906
2017/09/26 15:36:57 packer: reflect.Value.Call(0xc420177440, 0xc42014c2f8, 0x13, 0xc420495720, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/09/26 15:36:57 packer: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/09/26 15:36:57 packer: net/rpc.(*service).call(0xc420153400, 0xc420147220, 0xc420164030, 0xc420159100, 0xc420166240, 0x1ac5d00, 0xc4201649cc, 0x18a, 0x1a6d600, 0xc4201649d0, ...)
2017/09/26 15:36:57 packer: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2017/09/26 15:36:57 packer: created by net/rpc.(*Server).ServeCodec
2017/09/26 15:36:57 packer: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2017/09/26 15:36:57 Error cancelling builder: unexpected EOF
2017/09/26 15:36:57 Build cancelled: cloudstack
2017/09/26 15:36:57 /home/richard/bin/packer: plugin process exited
2017/09/26 15:36:57 [INFO] (telemetry) ending cloudstack
2017/09/26 15:36:57 [INFO] (telemetry) found error: unexpected EOF
2017/09/26 15:36:57 ui error: [1;31mBuild 'cloudstack' errored: unexpected EOF[0m
```

**Comment by mwhooker** [comment]
@rmwiseman I've got a fix in #5388 if you want to test it

**Comment by rmwiseman** [comment]
Thanks for such a quick fix!  Is there an easy way of testing it?  I'm using the standard single-executable version of packer so can't really patch it, can I...?

**Comment by rmwiseman** [comment]
Thanks, I've tried the 1.1.1 build and cancelled in [as close as I could manage] the same place and it exited cleanly.
