### ISSUE TITLE
EBS Volume missing field CreateTagsInput.Tags when launching spot instance

### ISSUE THREAD

**Issue by chappoo** [hashicorp/packer#5486]
- Packer version 1.1.1 only
- Windows
- Gist: https://gist.github.com/chappoo/9fc5b226975c8480188e920d6b0f67af

Since upgrading to Packer v1.1.1 the following error consistently occurs for templates that have previously worked fine:

> Error tagging source EBS Volumes on i-0f454d852f39d6550: InvalidParameter: 1 validation error(s) found.
>  - missing required field, CreateTagsInput.Tags.

This happens for both the `amazon-ebsvolume` and `amazon-ebs` builders (sample provided for `amazon-ebsvolume`).  I can confirm this bug was introduced in `v1.1.1` as previously tested versions where fine.

Note that with the amazon-ebs builder, a workaround is to provide both the `run_tags` and `run_volume_tags` parameters.

I've not seen any breaking changes documented as the revision bump would also indicate.

**Comment by chappoo** [comment]
Also worth mentioning that I've not found a workaround for the `amazon-ebsvolume` builder, so have been forced to rollback to v1.1.0 for the time being.  I'm taking a look at the code, but unfortunately my go skills are a bit lacking...

**Comment by rickard-von-essen** [comment]
Might be related to #5417

**Comment by phils** [comment]
I ran into this .. to work around it I stopped using spot and just used an on-demand instance.

**Comment by mwhooker** [comment]
interesting, thanks for the report.

**Comment by mwhooker** [comment]
@ofosos any chance you want to take a look? I investigated briefly and noticed that the `stepTagEBSVolumes` step was taken out of the ebsvolume builder completely. I'm not sure this is correct. Importantly, it calls `state.Put("ebsvolumes", volumes)` which is needed for the ebsvolume artifact.

**Comment by ofosos** [comment]
Looking into it right now.

**Comment by ofosos** [comment]
I can reproduce this.
I do have a patch to fix this partly, at least in the ebs builder.

**Comment by ofosos** [comment]
Actually this might fix both, since this is in common code. Please give it a go.

**Comment by mwhooker** [comment]
I made a couple of changes in d20d70896 that I think would be useful. it also moves the failure to where it tried to get the `ebsvolumes` for the artifact

**Comment by ofosos** [comment]
@mwhooker ok, looks interesting, I'm going to close PR 5495

**Comment by mwhooker** [comment]
feel free to keep it open. my branch does the same as yours except it has some new variables. Unfortunately it doesn't quite fix the issue yet

**Comment by ofosos** [comment]
WTF, this looks like some old code I already fixed O_o I mean exchanging the source and spot instances.

**Comment by ofosos** [comment]
Nope it's ok.... the following file runs fine with just my patch applied:

```
[mark@pericles ~]$ cat packer-spot-notags.json 
{
  "variables": {
    "access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
    "secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}"
  },
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "{{user `access_key`}}",
    "secret_key": "{{user `secret_key`}}",
    "region": "eu-west-1",
    "source_ami": "ami-5cc00825",
    "instance_type": "m3.medium",
    "ssh_username": "ubuntu",
    "ami_name": "packer-example {{timestamp}}",

            "spot_price": "auto",
"spot_price_auto_product": "Linux/UNIX"


  }]
}

```

**Comment by mwhooker** [comment]
@ofosos you're using the wrong builder, it should be `amazon-ebsvolume`

```
2017/10/23 12:29:09 packer: Build 'amazon-ebsvolume' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> amazon-ebsvolume: unexpected EOF

==> Builds finished but no artifacts were created.
panic: interface conversion: interface {} is nil, not ebsvolume.EbsVolumes
2017/10/23 12:29:09 packer:
2017/10/23 12:29:09 packer: goroutine 7 [running]:
2017/10/23 12:29:09 packer: github.com/hashicorp/packer/builder/amazon/ebsvolume.(*Builder).Run(0xc4203e6400, 0x3ccea20, 0xc420535d60, 0x3cc5c80, 0xc420480110, 0x3ccd380, 0xc420156130, 0x80000000000, 0x28, 0x28, ...)
2017/10/23 12:29:09 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/amazon/ebsvolume/builder.go:204 +0x1be6
2017/10/23 12:29:09 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc4201665e0, 0x1, 0xc42015a0c0, 0x0, 0x0)
2017/10/23 12:29:09 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:93 +0x1dd
2017/10/23 12:29:09 packer: reflect.Value.call(0xc42040c5a0, 0xc4203bc0b0, 0x13, 0x2c3d616, 0x4, 0xc42044bf20, 0x3, 0x3, 0xc42047b3d8, 0xc420546cb8, ...)
2017/10/23 12:29:09 packer: 	/usr/local/go/src/reflect/value.go:434 +0x906
2017/10/23 12:29:09 packer: reflect.Value.Call(0xc42040c5a0, 0xc4203bc0b0, 0x13, 0xc4204db720, 0x3, 0x3, 0xc4204db760, 0x131b135, 0xc420546c60)
2017/10/23 12:29:09 packer: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2017/10/23 12:29:09 packer: net/rpc.(*service).call(0xc420168280, 0xc4203b8320, 0xc4203c0230, 0xc420418580, 0xc420166900, 0x26bd020, 0xc42015a0bc, 0x18a, 0x2664360, 0xc42015a0c0, ...)
2017/10/23 12:29:09 packer: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2017/10/23 12:29:09 packer: created by net/rpc.(*Server).ServeCodec
2017/10/23 12:29:09 packer: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
2017/10/23 12:29:09 [INFO] (telemetry) ending amazon-ebsvolume
2017/10/23 12:29:09 [INFO] (telemetry) found error: unexpected EOF
2017/10/23 12:29:09 ui error: Build 'amazon-ebsvolume' errored: unexpected EOF
2017/10/23 12:29:09 Builds completed. Waiting on interrupt barrier...
2017/10/23 12:29:09 machine readable: error-count []string{"1"}
2017/10/23 12:29:09 ui error:
==> Some builds didn't complete successfully and had errors:
2017/10/23 12:29:09 machine readable: amazon-ebsvolume,error []string{"unexpected EOF"}
2017/10/23 12:29:09 ui error: --> amazon-ebsvolume: unexpected EOF
2017/10/23 12:29:09 ui:
==> Builds finished but no artifacts were created.
2017/10/23 12:29:09 [INFO] (telemetry) Finalizing.
2017/10/23 12:29:09 /Users/mwhooker/go/bin/packer: plugin process exited
2017/10/23 12:29:10 waiting for all plugin processes to complete...
```

**Comment by ofosos** [comment]
We need to bring back this hunk:

```
@@ -163,10 +163,6 @@ func (b *Builder) Run(ui packer.Ui, hook packer.Hook, cache packer.Cache) (packe
 			VpcId:            b.config.VpcId,
 		},
 		instanceStep,
-		&stepTagEBSVolumes{
-			VolumeMapping: b.config.VolumeMappings,
-			Ctx:           b.config.ctx,
-		},
 		&awscommon.StepGetPassword{
 			Debug:   b.config.PackerDebug,
 			Comm:    &b.config.RunConfig.Comm,

```

**Comment by mwhooker** [comment]
yeah I think so too. I think the tagging logic in `stepTagEBSVolumes` is slightly different than what's in step_run_spot_instance. It should be fine to do it twice

**Comment by ofosos** [comment]
Ok, the PR gives me a success for the following:

```
[mark@pericles ~]$ cat packer-spot-notags.json 
{
  "variables": {
    "access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
    "secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}"
  },
  "builders": [{
    "type": "amazon-ebsvolume",
    "access_key": "{{user `access_key`}}",
    "secret_key": "{{user `secret_key`}}",
    "region": "eu-west-1",
    "source_ami": "ami-5cc00825",
    "instance_type": "m3.medium",
    "ssh_username": "ubuntu",

            "spot_price": "auto",
"spot_price_auto_product": "Linux/UNIX",

            "ebs_volumes": [
                {
                    "volume_type": "gp2",
                    "device_name": "/dev/xvdf",
                    "delete_on_termination": false,
                    "volume_size": 12,
                    "tags": {
                        "zpool": "data",
                        "Name": "Data"
                    }
                }
                ]
  }]
}
```

**Comment by mwhooker** [comment]
hmm, something's not quite right still. this is the manifest.json from version 1.1.0 (working):

```
      "name": "amazon-ebsvolume",
      "builder_type": "amazon-ebsvolume",
      "build_time": 1508789016,
      "files": null,
      "artifact_id": "us-east-1:vol-091e49c59b486404a,us-east-1:vol-09f26d678762c11a6",
      "packer_run_uuid": "6bfda5df-5d2d-d761-7eda-ed5a2e719cbd"
    }
```

and your PR:
```
    {
      "name": "amazon-ebsvolume",
      "builder_type": "amazon-ebsvolume",
      "build_time": 1508789307,
      "files": null,
      "artifact_id": "",
      "packer_run_uuid": "ea1af7bb-9b2e-a839-a6ab-0487609aa228"
    }
```

**Comment by ofosos** [comment]
I broke all the things :( Now at least ebs and ebsvolume should be working again.

**Comment by mwhooker** [comment]
works! I don't quite understand how the tagging logic in `step_run_spot_instance.go` interacts with the logic in `step_tag_ebs_volumes.go`, but it works =)

I think this same treatment will need to be repeated on ebssurrogate as well

**Comment by ofosos** [comment]
Looking at 2661fd78 this doesn't seem to be the case. Blockdevices is still in there and we don't need the ebsvolumes variable.

**Comment by ofosos** [comment]
But ebssurrogate needs more cleanup and volume tagging, I just don't see a bug. I'm going to try and write a test case.
