### ISSUE TITLE
provisioner/windows-restart: use of closed channel

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#5537]
```
panic: send on closed channel
2017/10/17 13:31:38 packer:
2017/10/17 13:31:38 packer: goroutine 80 [running]:
2017/10/17 13:31:38 packer: github.com/hashicorp/packer/provisioner/windows-restart.glob..func1.1(0xc4203621c0, 0xc4203b2000, 0xc4200664d0)
2017/10/17 13:31:38 packer: 	/private/tmp/packer-20171014-45705-5rw8o9/src/github.com/hashicorp/packer/provisioner/windows-restart/provisioner.go:142 +0xa8
2017/10/17 13:31:38 packer: created by github.com/hashicorp/packer/provisioner/windows-restart.glob..func1
2017/10/17 13:31:38 packer: 	/private/tmp/packer-20171014-45705-5rw8o9/src/github.com/hashicorp/packer/provisioner/windows-restart/provisioner.go:139 +0x30d
2017/10/17 13:31:38 /usr/local/bin/packer: plugin process exited
2017/10/17 13:31:38 waiting for all plugin processes to complete...
2017/10/17 13:31:38 /usr/local/bin/packer: plugin process exited
2017/10/17 13:31:38 /usr/local/bin/packer: plugin process exited
2017/10/17 13:31:38 /usr/local/bin/packer: plugin process exited
2017/10/17 13:31:38 /usr/local/bin/packer: plugin process exited
```

this channel here can be closed https://github.com/hashicorp/packer/blob/52558e4f759b0825cfa35d84ec9088040fc0a89d/provisioner/windows-restart/provisioner.go#L142

on this line https://github.com/hashicorp/packer/blob/52558e4f759b0825cfa35d84ec9088040fc0a89d/provisioner/windows-restart/provisioner.go#L167

this whole bit of logic needs to be restructured

**Comment by SNikalaichyk** [comment]
I'm experiencing a problem with `windows-restart` that I suspect might be somehow related to this issue.

Occasionally `windows-restart` times out waiting for the Windows machine to reboot. However, machines do restart successfully and the cycle usually takes about 1-2 minutes to complete. `restart_timeout` is set to `30m`.

Packer version: `1.1.3`
Builder: `amazon-ebs`

**Comment by mwhooker** [comment]
unless you're getting a panic it's probably not related

**Comment by SNikalaichyk** [comment]
I'm not getting anything at all. 3 builds out of 10 `windows-restart` just waits forever. Should I create a new issue?
