### ISSUE TITLE
azure panic

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#5691]
Found an unchecked error case which can cause a panic. It's the array index on line 143

https://github.com/hashicorp/packer/blob/63f791570af9b11557816b324adb6b6a55926db1/builder/azure/arm/step_deploy_template.go#L138-L144

Seems like a simple enough fix, but I'm not familiar enough with this builder to say what should happen if the list has fewer than 2 or 3 elements.

cc @ArjenSchwarz

```
panic: runtime error: index out of range
2017/12/11 08:57:19 packer.exe: 	panic: runtime error: index out of range
2017/12/11 08:57:19 packer.exe:
2017/12/11 08:57:19 packer.exe: goroutine 193 [running]:
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*StepDeployTemplate).deleteImage(0xc042342f00, 0x0, 0x0, 0x0, 0x0, 0xc0422a6400, 0x11, 0xc0424586b0, 0x9)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/azure/arm/step_deploy_template.go:143 +0x402
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*StepDeployTemplate).(github.com/hashicorp/packer/builder/azure/arm.deleteImage)-fm(0x0, 0x0, 0x0, 0x0, 0xc0422a6400, 0x11, 0x9, 0x0)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/azure/arm/step_deploy_template.go:41 +0x70
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*StepDeployTemplate).Cleanup(0xc042342f00, 0x314b5c0, 0xc0422fa090)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/azure/arm/step_deploy_template.go:200 +0x889
2017/12/11 08:57:19 packer.exe: panic(0x1c704e0, 0x320e8e0)
2017/12/11 08:57:19 packer.exe: 	/usr/local/go/src/runtime/panic.go:491 +0x291
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*StepDeployTemplate).deleteImage(0xc042342f60, 0x0, 0x0, 0x0, 0x0, 0xc0422a6400, 0x11, 0xc0422b43a0, 0x9)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/azure/arm/step_deploy_template.go:143 +0x402
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*StepDeployTemplate).(github.com/hashicorp/packer/builder/azure/arm.deleteImage)-fm(0x0, 0x0, 0x0, 0x0, 0xc0422a6400, 0x11, 0x9, 0xc04228c5b0)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/azure/arm/step_deploy_template.go:41 +0x70
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*StepDeployTemplate).Cleanup(0xc042342f60, 0x314b5c0, 0xc0422fa090)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/azure/arm/step_deploy_template.go:200 +0x889
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc04214ac40, 0x314b5c0, 0xc0422fa090)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/vendor/github.com/mitchellh/multistep/basic_runner.go:82 +0x2e0
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc04222fb00, 0x314e5a0, 0xc0423b7ee0, 0x3145840, 0xc0422b2970, 0x314ce80, 0xc0420043f8, 0x80000000018, 0x28, 0x28, ...)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/builder/azure/arm/builder.go:206 +0xdf8
2017/12/11 08:57:19 packer.exe: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc04213d720, 0x1, 0xc0422060c0, 0x0, 0x0)
2017/12/11 08:57:19 packer.exe: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:93 +0x1e4
2017/12/11 08:57:19 packer.exe: reflect.Value.call(0xc04215e7e0, 0xc0421460c0, 0x13, 0x20b0070, 0x4, 0xc042595f20, 0x3, 0x3, 0xc0423b7d01, 0x1a65100, ...)
2017/12/11 08:57:19 packer.exe: 	/usr/local/go/src/reflect/value.go:434 +0x90d
2017/12/11 08:57:19 packer.exe: reflect.Value.Call(0xc04215e7e0, 0xc0421460c0, 0x13, 0xc042595f20, 0x3, 0x3, 0xc0421600e0, 0x0, 0x0)
2017/12/11 08:57:19 packer.exe: 	/usr/local/go/src/reflect/value.go:302 +0xab
2017/12/11 08:57:19 packer.exe: net/rpc.(*service).call(0xc0421323c0, 0xc042142320, 0xc042288188, 0xc042464380, 0xc0421442c0, 0x1b2dc60, 0xc04220609c, 0x18a, 0x1ad5240, 0xc0422060c0, ...)
2017/12/11 08:57:19 packer.exe: 	/usr/local/go/src/net/rpc/server.go:381 +0x149
2017/12/11 08:57:19 packer.exe: created by net/rpc.(*Server).ServeCodec
2017/12/11 08:57:19 packer.exe: 	/usr/local/go/src/net/rpc/server.go:475 +0x372
```

**Comment by ArjenSchwarz** [comment]
Interesting, this is the same as in https://github.com/hashicorp/packer/blob/63f791570af9b11557816b324adb6b6a55926db1/builder/azure/arm/step_delete_os_disk.go#L84

Putting an if statement around it and throwing an error/failure should prevent it from crashing, but I don't know how it would not get a valid array here in the first place. @mwhooker can you give an example of what you ran that caused it to happen? I'll prepare a fix to prevent it from crashing tonight, but I like to know the use case in case there's an underlying issue that should be fixed.

**Comment by mwhooker** [comment]
I'm afraid I don't have access to the config that generated this, sorry!

**Comment by ArjenSchwarz** [comment]
No problem, I suspect that it somehow got an invalid URL for the image. In #5695 I've added some code to deal with those situation and give a clean error instead.
