### ISSUE TITLE
Issues with Ansible 2.4.1 (and later) when building Windows + WinRM + QEMU because of "setup" module

### ISSUE THREAD

**Issue by ruzickap** [hashicorp/packer#5845]
I'm not able to build Windows image using latest Packer + Ansible 2.4.1 (and later) + WinRM + QEMU. 
The strange is that Ansible 2.4.0 is working fine. The provisioning dies on Ansible error:
```
2018/02/05 16:45:01 ui:     windows-enterprise-eval: <127.0.0.1> (1, '', "Warning: Permanently added '[127.0.0.1]:43919' (RSA) to the list of known hosts.\r\n'-' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")
2018/02/05 16:45:01 ui:     windows-enterprise-eval: fatal: [default]: FAILED! => {
2018/02/05 16:45:01 ui:     windows-enterprise-eval:     "changed": false,
2018/02/05 16:45:01 ui:     windows-enterprise-eval:     "failed": true,
2018/02/05 16:45:01 ui:     windows-enterprise-eval:     "module_stderr": "Warning: Permanently added '[127.0.0.1]:43919' (RSA) to the list of known hosts.\r\n'-' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n",
2018/02/05 16:45:01 ui:     windows-enterprise-eval:     "module_stdout": "",
2018/02/05 16:45:01 ui:     windows-enterprise-eval:     "msg": "MODULE FAILURE",
2018/02/05 16:45:01 ui:     windows-enterprise-eval:     "rc": 1
2018/02/05 16:45:01 ui:     windows-enterprise-eval: }
2018/02/05 16:45:01 ui:     windows-enterprise-eval:
2018/02/05 16:45:01 ui:     windows-enterprise-eval: PLAY RECAP *********************************************************************
2018/02/05 16:45:01 ui:     windows-enterprise-eval: default                    : ok=0    changed=0    unreachable=0    failed=1
2018/02/05 16:45:01 ui:     windows-enterprise-eval:
```

It looks like something changed in Ansible between 2.4.0 and 2.4.1 and the connection plugin can not handle it.

I'm using this simple Ansible playbook:
```
---
- hosts: all
  gather_facts: true
  tasks:
    - debug: msg="Getting facts works fine..."
```

When I keep `gather_facts: true` then Ansible 2.4.1 (and later) called by packer died with error described above. If I use `gather_facts: false` then "all" Ansible versions finish successfully.

Maybe something changed in Ansible `setup` module between 2.4.1 and 2.4.0 versions...  

- Packer version from `packer version`: 1.1.3
- Host platform: Fedora 27
- Debug log output from `PACKER_LOG=1 PACKER_LOG_PATH="packerlog" ./packer build ./windows-enterprise-eval.json`.
https://pastebin.com/xdPG4mef

- The _simplest example template and scripts_ needed to reproduce the bug:
I'm using this testing script: https://gist.github.com/ruzickap/3258c16015d35495811a65b17626b94a which creates Ansible playbook, Packer json file + files neede for building Windows automatically.

If you need any more logs from different Ansible versions / playbooks let me know - I already have a script to test this scenario. 

Thank you for looking at it.

**Comment by ruzickap** [comment]
Update:
I used Packer 1.2.0 and Ansible "2.5.0b2" and future "2.6" with the same "bad" results mentioned above.

The script "https://gist.github.com/ruzickap/3258c16015d35495811a65b17626b94a" used for reproducing this issue was updated...

**Comment by ruzickap** [comment]
I just want to add, that the issue is happening with qemu and virtualbox builder.

**Comment by SwampDragons** [comment]
Thanks for the update; given the traffic on this ticket you may find it worth knowing that the Ansible provisioner is community-supported and doesn't get a lot of active development--so the best chance you have of seeing this fixed is probably to make a PR.

**Comment by ruzickap** [comment]
Ok I understand... 
It's just handy for the others to know, that the Ansible provisioner (https://www.packer.io/docs/provisioners/ansible.html) is not working with WinRM in Packer.
Maybe somebody will fix it one day...

**Comment by ruzickap** [comment]
I'm getting slightly different with Ansible 2.5.0: 

```
2018/03/23 20:26:42 packer: 2018/03/23 20:26:42 Connected to machine
2018/03/23 20:26:42 ui: ==> windows-enterprise-eval: Connected to WinRM!
2018/03/23 20:26:42 packer: 2018/03/23 20:26:42 Running the provision hook
2018/03/23 20:26:42 [INFO] (telemetry) Starting provisioner ansible
2018/03/23 20:26:42 ui: ==> windows-enterprise-eval: Provisioning with Ansible...
2018/03/23 20:26:43 packer: 2018/03/23 20:26:43 SSH proxy: serving on 127.0.0.1:41775
2018/03/23 20:26:43 ui: ==> windows-enterprise-eval: Executing Ansible: ansible-playbook --extra-vars packer_build_name=windows-enterprise-eval packer_builder_type=qemu -i /var/tmp/packer-provisioner-ansible245298001 /var/tmp/mytest/test/win.yml -e ansible_ssh_private_key_file=/var/tmp/ansible-key377691450 --connection packer -vvv --extra-vars ansible_shell_type=powershell ansible_shell_executable=None
2018/03/23 20:26:44 ui:     windows-enterprise-eval: ansible-playbook 2.5.0
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   config file = /home/pruzicka/.ansible.cfg
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   configured module search path = [u'/home/pruzicka/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   ansible python module location = /var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   executable location = /var/tmp/mytest/test/my-ansible/bin/ansible-playbook
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
2018/03/23 20:26:44 ui:     windows-enterprise-eval: Using /home/pruzicka/.ansible.cfg as config file
2018/03/23 20:26:44 ui:     windows-enterprise-eval: Parsed /var/tmp/packer-provisioner-ansible245298001 inventory source with ini plugin
2018/03/23 20:26:44 ui:     windows-enterprise-eval:
2018/03/23 20:26:44 ui:     windows-enterprise-eval: PLAYBOOK: win.yml **************************************************************
2018/03/23 20:26:44 ui:     windows-enterprise-eval: 1 plays in /var/tmp/mytest/test/win.yml
2018/03/23 20:26:44 ui:     windows-enterprise-eval:
2018/03/23 20:26:44 ui:     windows-enterprise-eval: PLAY [all] *********************************************************************
2018/03/23 20:26:44 ui:     windows-enterprise-eval:
2018/03/23 20:26:44 ui:     windows-enterprise-eval: TASK [Gathering Facts] *********************************************************
2018/03/23 20:26:44 ui:     windows-enterprise-eval: task path: /var/tmp/mytest/test/win.yml:2
2018/03/23 20:26:44 ui:     windows-enterprise-eval: Using module file /var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
2018/03/23 20:26:44 ui:     windows-enterprise-eval: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
2018/03/23 20:26:44 ui:     windows-enterprise-eval: The full traceback is:
2018/03/23 20:26:44 ui:     windows-enterprise-eval: Traceback (most recent call last):
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 138, in run
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     res = self._execute()
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 554, in _execute
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     result = self._handler.run(task_vars=variables)
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 795, in _execute_module
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 902, in _low_level_execute_command
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 976, in exec_command
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     use_tty = self.get_option('use_tty')
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 58, in get_option
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/config/manager.py", line 284, in get_config_value
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     value, _drop = self.get_config_value_and_origin(config, cfile=cfile, plugin_type=plugin_type, plugin_name=plugin_name, keys=keys, variables=variables)
2018/03/23 20:26:44 ui:     windows-enterprise-eval:   File "/var/tmp/mytest/test/my-ansible/lib/python2.7/site-packages/ansible/config/manager.py", line 304, in get_config_value_and_origin
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     defs = self._plugins[plugin_type][plugin_name]
2018/03/23 20:26:44 ui:     windows-enterprise-eval: KeyError: 'connection'
2018/03/23 20:26:44 ui:     windows-enterprise-eval: fatal: [default]: FAILED! => {
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     "msg": "Unexpected failure during module execution.",
2018/03/23 20:26:44 ui:     windows-enterprise-eval:     "stdout": ""
2018/03/23 20:26:44 ui:     windows-enterprise-eval: }
2018/03/23 20:26:44 ui:     windows-enterprise-eval:
2018/03/23 20:26:44 ui:     windows-enterprise-eval: PLAY RECAP *********************************************************************
2018/03/23 20:26:44 ui:     windows-enterprise-eval: default                    : ok=0    changed=0    unreachable=0    failed=1
2018/03/23 20:26:44 ui:     windows-enterprise-eval:
2018/03/23 20:26:44 packer: 2018/03/23 20:26:44 shutting down the SSH proxy
2018/03/23 20:26:44 [INFO] (telemetry) ending ansible
```

Full log here: https://pastebin.com/HhPHx1yZ

Anyway result is the same -> "Gathering Facts" (setup module) is not working for Windows + WinRM + QEMU/VirtualBox + Ansible...

**Comment by dustyhorizon** [comment]
Getting the same issue on my end too

**Comment by zaitsxl** [comment]
Same here, ansible 2.5+packer 1.1.1

**Comment by hegawa** [comment]
I have tried the following methods and still getting the same errors as above:  

1. in the playbook, set gather_facts to no --> same error happens at the execution stage
2. made sure that port, winrm protocol, ansible_user, ansible_password is using what we specified in json file
3. ignore cert validation

all of above steps still comes back with 
` KeyError: 'connection'`
`"msg": "Unexpected failure during module execution.",`

I understand that you can just do local shell to do ansible execution.  However we aren't sure how to do error handling the right way for each playbook execution (meaning fail the build the moment playbook sends back any errors)

**Comment by zaitsxl** [comment]
Actually after playing a bit with packer json I managed to get this working on Ansible 2.4.1 + Packer 1.1.1

**Comment by hegawa** [comment]
@zaitsxl can you tell us how you got it to work?

**Comment by ruzickap** [comment]
Maybe it will be handy to test it with Packer 1.2.2 and Ansible 2.5 (both latest versions as of now).
Anyway @zaitsxl please let us know how you succeed with it and I (and probably others) can test it.

**Comment by zaitsxl** [comment]
Well I can paste my json and playbook here, but I cannot tell for sure what exactly has helped. My platform is OpenSUSE 42.2, ansible 2.4.1 was installed with zypper, python version 2.7.13.

Here's the json:
``
{
  "builders": [
    {   
      "type": "amazon-ebs",
      "communicator": "ssh",
      "ssh_pty": true,
      "region": "eu-west-1",
      "source_ami": "ami-12345678",
      "instance_type": "m3.large",
      "security_group_id": "sg-12345678",
      "subnet_id": "subnet-12345678",
      "communicator": "winrm",
      "ssh_keypair_name": "keypair",
      "ssh_private_key_file": "/root/.ssh/key.pem",
      "winrm_username": "administrator",
      "user_data_file": "winrm-prep.txt",
      "iam_instance_profile": "access-to-s3",
      "ami_name": "my_ami_name",
      "launch_block_device_mappings": [
        {   
        "device_name": "/dev/sda1",
        "volume_size": 30, 
        "volume_type": "gp2",
        "delete_on_termination": true
        }   
      ]   
    }   
  ],  
  "provisioners": [
    {   
       "type":  "ansible",
       "playbook_file": "./playbook.yml",
       "ansible_env_vars": [ "ANSIBLE_ROLES_PATH=/opt/ansible/:$ANSIBLE_ROLES_PATH" ],                  
       "extra_arguments": [
           "--connection", "packer", "-vvv",
           "--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"
       ]   
    }   
  ]
}

**Comment by hegawa** [comment]
@ruzickap Im willing to test with you. lets work together on this so we can get passed this issue.  I also saw another post that specifically "scripts" module for ansible is buggy with this.   Can you show me what your provisioner json is for the ansible portion and the playbook content?

mine is like this (please ignore the extra-vars I inserted thinking maybe its winrm authentication)
`    {
      "type":  "ansible",
      "playbook_file": "./windows-inspec-demo/ansible/playbook.yml",
      "extra_arguments": [
        "--connection", "packer",
        "-vvvv",
        "--extra-vars", "ansible_user={{user `winrm_username`}} ansible_password={{user `winrm_password`}} ansible_shell_type=powershell ansible_shell_executable=None ansible_winrm_scheme=http ansible_port=5985 ansible_winrm_server_cert_validation=ignore"
      ]
    },`

while the playbook is like this
`---
- name: install test
  hosts: all
  gather_facts: no
  tasks:

    - script: files/10-install-demo-app.ps1`

**Comment by ruzickap** [comment]
@zaitsxl - actually I can see you are using AWS instead of Qemu/Virtualhost. This bug is related to Qemu/Virtualhost issue.

@hegawa - thank you for your help.

-> I created the repository" https://github.com/ruzickap/packer_windows_winrm_ansible, where I put my test script + additional files. It's written for Fedora, but the main parts can be used somewhere else...

If you have the Fedora you can simply run the `packer_qemu_windows_ansible_winrm.sh` and it will do it's job and start testing...

To answer your question my packer template looks like: https://github.com/ruzickap/packer_windows_winrm_ansible/blob/master/packer_qemu_windows_ansible_winrm.sh#L26

Ansible playbook is really simple:
https://github.com/ruzickap/packer_windows_winrm_ansible/blob/master/packer_qemu_windows_ansible_winrm.sh#L16

**Comment by hegawa** [comment]
I removed all the extra arguments and used what @zaitsxl used.  I am facing the following error:

`ebug3: mux_client_read_packet: read header failed: Broken pipe
debug2: Received exit status from master 0
')
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": true,
	
	
	
	    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": true,
    amazon-ebs:     "failed": true,
    amazon-ebs:     "msg": "non-zero return code",
    amazon-ebs:     "rc": 1,
    amazon-ebs:     "stderr": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config`

**Comment by zaitsxl** [comment]
@ruzickap yes I know that original question was about virtualbox/QEMU, however at the beginning I had the same issue with AWS

**Comment by hegawa** [comment]
@zaitsxl can you also post how you configured the winrm? I have the exact same settings at this point, and I am starting to think maybe me not standing up a daemon on the executing machine (ubuntu) or winrm configuration on target

**Comment by zaitsxl** [comment]
@hegawa sure, I pass the below content in file as instance user-data
``
<powershell>    
netsh advfirewall set allprofiles state off    
Set-Item -Path "WSMan:\localhost\Service\AllowUnencrypted" -Value true                                               
Invoke-Expression ((New-Object System.Net.Webclient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1'))
Set-ExecutionPolicy Unrestricted -force    
</powershell>
``

**Comment by adarobin** [comment]
I was hitting the `KeyError: 'connection'` issue with Ansible 2.5 on Packer 1.2.2 with the AWS builder and I think I have discovered the issue.  It looks like Ansible now requires plugins to have a documentation string.  I copied the documentation string from the SSH connection plugin (since that is what the packer plugin is based on) made a few changes and my packer.py now looks like this:

```
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

from ansible.plugins.connection.ssh import Connection as SSHConnection

DOCUMENTATION = '''
    connection: packer
    short_description: connect via ssh client binary
    description:
        - This connection plugin allows ansible to communicate to the target packer machines via ssh based connections for powershell.
    author: Packer
    version_added: na
    options:
      host:
          description: Hostname/ip to connect to.
          default: inventory_hostname
          vars:
               - name: ansible_host
               - name: ansible_ssh_host
      host_key_checking:
          description: Determines if ssh should check host keys
          type: boolean
          ini:
              - section: defaults
                key: 'host_key_checking'
              - section: ssh_connection
                key: 'host_key_checking'
                version_added: '2.5'
          env:
              - name: ANSIBLE_HOST_KEY_CHECKING
              - name: ANSIBLE_SSH_HOST_KEY_CHECKING
                version_added: '2.5'
          vars:
              - name: ansible_host_key_checking
                version_added: '2.5'
              - name: ansible_ssh_host_key_checking
                version_added: '2.5'
      password:
          description: Authentication password for the C(remote_user). Can be supplied as CLI option.
          vars:
              - name: ansible_password
              - name: ansible_ssh_pass
      ssh_args:
          description: Arguments to pass to all ssh cli tools
          default: '-C -o ControlMaster=auto -o ControlPersist=60s'
          ini:
              - section: 'ssh_connection'
                key: 'ssh_args'
          env:
              - name: ANSIBLE_SSH_ARGS
      ssh_common_args:
          description: Common extra args for all ssh CLI tools
          vars:
              - name: ansible_ssh_common_args
      ssh_executable:
          default: ssh
          description:
            - This defines the location of the ssh binary. It defaults to `ssh` which will use the first ssh binary available in $PATH.
            - This option is usually not required, it might be useful when access to system ssh is restricted,
              or when using ssh wrappers to connect to remote hosts.
          env: [{name: ANSIBLE_SSH_EXECUTABLE}]
          ini:
          - {key: ssh_executable, section: ssh_connection}
          yaml: {key: ssh_connection.ssh_executable}
          #const: ANSIBLE_SSH_EXECUTABLE
          version_added: "2.2"
      scp_extra_args:
          description: Extra exclusive to the 'scp' CLI
          vars:
              - name: ansible_scp_extra_args
      sftp_extra_args:
          description: Extra exclusive to the 'sftp' CLI
          vars:
              - name: ansible_sftp_extra_args
      ssh_extra_args:
          description: Extra exclusive to the 'ssh' CLI
          vars:
              - name: ansible_ssh_extra_args
      retries:
          # constant: ANSIBLE_SSH_RETRIES
          description: Number of attempts to connect.
          default: 3
          type: integer
          env:
            - name: ANSIBLE_SSH_RETRIES
          ini:
            - section: connection
              key: retries
            - section: ssh_connection
              key: retries
      port:
          description: Remote port to connect to.
          type: int
          default: 22
          ini:
            - section: defaults
              key: remote_port
          env:
            - name: ANSIBLE_REMOTE_PORT
          vars:
            - name: ansible_port
            - name: ansible_ssh_port
      remote_user:
          description:
              - User name with which to login to the remote server, normally set by the remote_user keyword.
              - If no user is supplied, Ansible will let the ssh client binary choose the user as it normally
          ini:
            - section: defaults
              key: remote_user
          env:
            - name: ANSIBLE_REMOTE_USER
          vars:
            - name: ansible_user
            - name: ansible_ssh_user
      pipelining:
          default: ANSIBLE_PIPELINING
          description:
            - Pipelining reduces the number of SSH operations required to execute a module on the remote server,
              by executing many Ansible modules without actual file transfer.
            - This can result in a very significant performance improvement when enabled.
            - However this conflicts with privilege escalation (become).
              For example, when using sudo operations you must first disable 'requiretty' in the sudoers file for the target hosts,
              which is why this feature is disabled by default.
          env:
            - name: ANSIBLE_PIPELINING
            #- name: ANSIBLE_SSH_PIPELINING
          ini:
            - section: defaults
              key: pipelining
            #- section: ssh_connection
            #  key: pipelining
          type: boolean
          vars:
            - name: ansible_pipelining
            - name: ansible_ssh_pipelining
      private_key_file:
          description:
              - Path to private key file to use for authentication
          ini:
            - section: defaults
              key: private_key_file
          env:
            - name: ANSIBLE_PRIVATE_KEY_FILE
          vars:
            - name: ansible_private_key_file
            - name: ansible_ssh_private_key_file
      control_path:
        description:
          - This is the location to save ssh's ControlPath sockets, it uses ssh's variable substitution.
          - Since 2.3, if null, ansible will generate a unique hash. Use `%(directory)s` to indicate where to use the control dir path setting.
        env:
          - name: ANSIBLE_SSH_CONTROL_PATH
        ini:
          - key: control_path
            section: ssh_connection
      control_path_dir:
        default: ~/.ansible/cp
        description:
          - This sets the directory to use for ssh control path if the control path setting is null.
          - Also, provides the `%(directory)s` variable for the control path setting.
        env:
          - name: ANSIBLE_SSH_CONTROL_PATH_DIR
        ini:
          - section: ssh_connection
            key: control_path_dir
      sftp_batch_mode:
        default: 'yes'
        description: 'TODO: write it'
        env: [{name: ANSIBLE_SFTP_BATCH_MODE}]
        ini:
        - {key: sftp_batch_mode, section: ssh_connection}
        type: bool
      scp_if_ssh:
        default: smart
        description:
          - "Prefered method to use when transfering files over ssh"
          - When set to smart, Ansible will try them until one succeeds or they all fail
          - If set to True, it will force 'scp', if False it will use 'sftp'
        env: [{name: ANSIBLE_SCP_IF_SSH}]
        ini:
        - {key: scp_if_ssh, section: ssh_connection}
      use_tty:
        version_added: '2.5'
        default: 'yes'
        description: add -tt to ssh commands to force tty allocation
        env: [{name: ANSIBLE_SSH_USETTY}]
        ini:
        - {key: usetty, section: ssh_connection}
        type: bool
        yaml: {key: connection.usetty}
'''

class Connection(SSHConnection):
    ''' ssh based connections for powershell via packer'''

    transport = 'packer'
    has_pipelining = True
    become_methods = []
    allow_executable = False
    module_implementation_preferences = ('.ps1', '')

    def __init__(self, *args, **kwargs):
        super(Connection, self).__init__(*args, **kwargs)
```

Hopefully that fixes the issue for everyone else here as well.

**Comment by mangopirate** [comment]
@adarobin I came to a similar conclusion yesterday when investigating this, I found that the problem started with this specific Ansible pull request: [#33148](https://github.com/ansible/ansible/commit/218987eac1eb9a5671f996d2887dcca349199e51)

To be a bit more specific, that pull request added the line 

`use_tty = self.get_option('use_tty')`

which tries to get the `use_tty` option as seen at the bottom of the docstring you copied. You can get away with only including the `use_tty` option in the docstring, although using the whole thing may be safer. I'm not sure if anything else in there is used. Unfortunately you have to have the docstring in the packer.py connection plugin file instead of importing it. 

I'm working with AWS and this let me connect to start running Ansible tasks on a Windows EC2 instance. Unfortunately I've now run into other issues with the `win_copy` module, only when using Packer. It seems to always run successfully the first time in a playbook, but then the next task will fail and I see an error like

`amazon-ebs: OSError: [Errno 2] No such file or directory: '/home/mangopirate/.ansible/tmp/ansible-local-11857yrvf_o/tmpSrQJOW'`

Still looking into that error.

**Comment by Wenzel** [comment]
Same issue here, provisioning windows VMs is broken.
Ansible 2.4.1 and above :(
~~~
==> qemu: Provisioning with Ansible...
==> qemu: Executing Ansible: ansible-playbook --extra-vars packer_build_name=qemu packer_builder_type=qemu -i /tmp/packer-provisioner-ansible784960333 /home/tarrma/tmp/windows_windbg_template/playbook.yml -e ansible_ssh_private_key_file=/tmp/ansible-key090201126 --connection packer --extra-vars ansible_shell_type=powershell ansible_shell_executable=None
    qemu:
    qemu: PLAY [all] *********************************************************************
    qemu:
    qemu: TASK [Gathering Facts] *********************************************************
    qemu: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'connection'
    qemu: fatal: [default]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
    qemu: 	to retry, use: --limit @/home/tarrma/tmp/windows_windbg_template/playbook.retry
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=0    changed=0    unreachable=0    failed=1
    qemu:
==> qemu: Deleting output directory...
~~~

Please fix.

**Comment by zaitsxl** [comment]
What I also found out during this trouble shooting is that for some reason "raw" module fails when playbook is executed by packer, so I had to replace all "raw" executions to "win_shell" and it worked like a charm. Also it's recommended to do so by Ansible docs

**Comment by jamielennox** [comment]
Thanks @mangopirate that solved the issue for me in AWS builds with ansible 2.5. Any way we could get this distributed with packer rather than the documentation telling you to copy it over each time?

**Comment by ruzickap** [comment]
Hello.

I tried to use [packer.py](https://gist.github.com/adarobin/2f02b8b993936233e15d76f6cddb9e00) as the custom Ansible connection plugin, but I'm still getting the error described in the description.

It's good to hear that this change helped you to make Windows + WinRM + Ansible + AWS working, but can somebody check also the Windows + WinRM + Ansible + QEMU ?

I updated my test repository here to allow all people to do the testing (Windows + WinRM + Ansible + QEMU):

https://github.com/ruzickap/packer_windows_winrm_ansible

I believe the final `packer.py` should be working on "all" platforms: AWS, Virtualbox, QEMU, ...

Thank you

**Comment by Wenzel** [comment]
@ruzickap if i'm not mistaking, this is a bug in Ansible, not Packer itself.

As shown by @mangopirate, it seems that a specific PR broke WinRM with Packer.

Is there an issue opened in Ansible ?

**Comment by ruzickap** [comment]
@Wenzel - I'm not sure if the problem is in Ansible. 
If I use latest Ansible + WinRM (no Packer) with Windows (2012, 10, 2016) - it works fine.

I'm not a developer, so I can not say where the problem is but Ansible + WinRM (SSL) + Windows is working fine... (I tested it...)

It looks to me like Ansible in version 2.4.1 introduced some changes in code which broke compatibility with Packer and it's packer.py custom Ansible connection plugin, but it didn't break the main functionality with Windows.

I guess now the packer.py (Ansible connection plugin) should be modified to work with latest Ansible...

**Comment by mangopirate** [comment]
@ruzickap you're right that this isn't a problem with Ansible. As of 2.4 they made changes that require including the doc string if you're inheriting from a connection plugin (see http://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#plugin-configuration)

There's an old open PR [#5162](https://github.com/hashicorp/packer/pull/5162/) that makes some other changes to packer.py, I'm not sure if any of those are helpful. If not, I suspect your issue is with the Ansible Provisioner and not the packer.py connection plugin. 

From what I've seen in other issues, the Ansible provisioner is community maintained and using the `shell-local` provisioner is recommended if possible. That would run Ansible from your machine using WinRM instead of trying to use the connection plugin.

**Comment by ruzickap** [comment]
I didn't know the Ansible Provisioner (https://www.packer.io/docs/provisioners/ansible.html) is not part of Packer and it is only community maintained. I expected that if it's in the official documentation / git repository, then it's "supported" by "Packer team".

Anyway I tried the changes for connection plugin ([packer.py](https://github.com/bhcleek/packer/blob/724ca00c1dfbfcdc07f0c73d2d05eb7d7ef5950f/test/fixtures/provisioner-ansible/connection_plugins/packer.py)) mentioned in #5162, but I got the error again.

Using `shell-local` provisioner with ansible may be hard, because ansible needs IP of the machine which is being build and getting it's IP is pain (depend what OS are you running/building).

-> That's why I believed the Ansible Provisioner should be right/proper way of using Packer + Ansible.

This combination Windows + WinRM + QEMU + [Ansible Provisioner](https://www.packer.io/docs/provisioners/ansible.html) + [Ansible packer connection plugin](https://github.com/hashicorp/packer/blob/master/test/fixtures/provisioner-ansible/connection_plugins/packer.py) is working fine for old Ansible 2.4.0 (not for newer versions).

-> I hope somebody will fix the [packer.py](https://github.com/hashicorp/packer/blob/master/test/fixtures/provisioner-ansible/connection_plugins/packer.py) or [Ansible Provisioner](https://www.packer.io/docs/provisioners/ansible.html) to allow people use latest Ansible + Packer for all OS (including Windows)...

**Comment by SwampDragons** [comment]
@ruzickap I agree that it's confusing to have some community-maintained provisioners in the official documentation and repository. Terraform had a similar problem and recently split apart the HashiCorp-supported core features and the community supported providers, and we're hoping to eventually do something similar; we're just letting them work out the kinks first, since we'd like to benefit from their lessons learned. 

Hopefully that split will help make it clearer to users what tooling gets active development time from HashiCorp and what tooling does not. In the meantime, you can see the list of HashiCorp-supported plugins [here](https://www.packer.io/community-plugins.html); anything not on that list is community-supported, meaning that we'll give some guidance and we'll review PRs but we won't actively develop them.  This isn't because we think the community-maintained plugins aren't important; it's simply because we currently only have two Packer maintainers at HashiCorp and we can't do everything. We'd rather make sure the most heavily used plugins are well supported than spread ourselves too thin.

At my job before I worked on Packer, we used the ansible-local provisioner instead of dealing with the pain of finding the host IP. Is that also broken for windows, or is it just the ansible-remote provisioner?

**Comment by ruzickap** [comment]
That's true. Packer + ansible-local can be used only on "unix" based OS. 
You can not do it in in Windows...

**Comment by AndrewCi** [comment]
Can you explain the conflict between ansible-local and Windows? Is it not possible to run a Packer build from a "unix" based machine to build a Windows image using ansible-local?
