### ISSUE TITLE
amazon_ebs panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shadycuz** [hashicorp/packer#6029]
Using `packer -v 1.2.1` on `amazon linux`.

Part of crash log...
```
2018/03/19 15:23:23 ui: ESC[1;32m==> amazon-ebs: Connected to SSH!ESC[0m
2018/03/19 15:23:23 packer: 2018/03/19 15:23:23 Running the provision hook
2018/03/19 15:23:23 [INFO] (telemetry) Starting provisioner shell
2018/03/19 15:23:23 ui: ESC[1;32m==> amazon-ebs: Provisioning with shell script: /tmp/packer-shell735442832ESC[0m
2018/03/19 15:23:23 packer: 2018/03/19 15:23:23 Opening /tmp/packer-shell735442832 for reading
2018/03/19 15:23:23 packer: 2018/03/19 15:23:23 [INFO] 178 bytes written for 'uploadData'
2018/03/19 15:23:23 [INFO] 178 bytes written for 'uploadData'
2018/03/19 15:23:23 packer: 2018/03/19 15:23:23 opening new ssh session
2018/03/19 15:23:24 packer: 2018/03/19 15:23:24 starting remote command: test -d "/tmp/script_4845.sh"
2018/03/19 15:23:33 packer: 2018/03/19 15:23:33 path is a directory; copying file into directory.
2018/03/19 15:23:33 packer: panic: runtime error: invalid memory address or nil pointer dereference
2018/03/19 15:23:33 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9f19cc]
2018/03/19 15:23:33 packer:
2018/03/19 15:23:33 packer: goroutine 198 [running]:
2018/03/19 15:23:33 packer: github.com/hashicorp/packer/communicator/ssh.(*comm).scpUploadSession(0xc4206b9a70, 0xc4202adb60, 0x13, 0x22d89c0, 0xc42025b2b0, 0x0, 0x0, 0x22d89c0)
2018/03/19 15:23:33 packer:     /Users/mwhooker/go/src/github.com/hashicorp/packer/communicator/ssh/communicator.go:591 +0x41c
2018/03/19 15:23:33 packer: github.com/hashicorp/packer/communicator/ssh.(*comm).Upload(0xc4206b9a70, 0xc4202adb60, 0x13, 0x22d89c0, 0xc42025b2b0, 0x0, 0x0, 0xc420408000)
2018/03/19 15:23:33 packer:     /Users/mwhooker/go/src/github.com/hashicorp/packer/communicator/ssh/communicator.go:156 +0xcc
2018/03/19 15:23:33 packer: github.com/hashicorp/packer/packer/rpc.(*CommunicatorServer).Upload(0xc420106a80, 0xc420421500, 0xc420502770, 0x0, 0x0)
2018/03/19 15:23:33 packer:     /Users/mwhooker/go/src/github.com/hashicorp/packer/packer/rpc/communicator.go:294 +0x14a
2018/03/19 15:23:33 packer: reflect.Value.call(0xc42065b5c0, 0xc42000cdd0, 0x13, 0x20f465e, 0x4, 0xc420795f18, 0x3, 0x3, 0xc420086200, 0xc4204a6388, ...)
2018/03/19 15:23:33 packer:     /usr/local/go/src/reflect/value.go:447 +0x969
2018/03/19 15:23:33 packer: reflect.Value.Call(0xc42065b5c0, 0xc42000cdd0, 0x13, 0xc420498718, 0x3, 0x3, 0x1, 0x704a4e, 0x1)
2018/03/19 15:23:33 packer:     /usr/local/go/src/reflect/value.go:308 +0xa4
2018/03/19 15:23:33 packer: net/rpc.(*service).call(0xc42065c700, 0xc42017c8c0, 0xc4201824b8, 0xc4201824c0, 0xc420488f00, 0xc420421460, 0x1a404c0, 0xc420421500, 0x16, 0x1a96e40, ...)
2018/03/19 15:23:33 packer:     /usr/local/go/src/net/rpc/server.go:384 +0x14e
2018/03/19 15:23:33 packer: created by net/rpc.(*Server).ServeCodec
2018/03/19 15:23:33 packer:     /usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/03/19 15:23:33 /usr/bin/packer: plugin process exited
2018/03/19 15:23:33 [INFO] (telemetry) ending amazon-ebs
2018/03/19 15:23:33 ui error: ESC[1;31mBuild 'amazon-ebs' errored: unexpected EOFESC[0m
2018/03/19 15:23:33 Builds completed. Waiting on interrupt barrier...
2018/03/19 15:23:33 machine readable: error-count []string{"1"}
2018/03/19 15:23:33 ui error:
==> Some builds didn't complete successfully and had errors:
2018/03/19 15:23:33 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2018/03/19 15:23:33 ui error: --> amazon-ebs: unexpected EOF
2018/03/19 15:23:33 ui:
==> Builds finished but no artifacts were created.
2018/03/19 15:23:33 [INFO] (telemetry) Finalizing.
2018/03/19 15:23:33 packer: 2018/03/19 15:23:33 Retryable error: Error uploading script: unexpected EOF
2018/03/19 15:23:33 waiting for all plugin processes to complete...
2018/03/19 15:23:33 [INFO] (telemetry) ending shell
2018/03/19 15:23:33 /usr/bin/packer: plugin process exited
2018/03/19 15:23:33 /usr/bin/packer: plugin process exited
```

packer.json 
```
{
  "variables": {
    "jenkins_job": "{{env `JOB_NAME`}}",
    "jenkins_build": "{{env `BUILD_NUMBER`}}"
  },
  "builders": [{
    "type": "amazon-ebs",
    "ssh_pty" : true,
    "region": "{{user `region`}}",
    "source_ami": "{{user `base_ami`}}",
    "encrypt_boot": true,
    "instance_type": "{{user `instance_type`}}",
    "ssh_username": "{{user `ssh_username`}}",
    "vpc_id": "{{user `vpc_id`}}",
    "subnet_id": "{{user `subnet_id`}}",
    "ami_block_device_mappings": [{
      "device_name": "/dev/xvda",
      "delete_on_termination": "true",
      "volume_size": 50,
      "volume_type": "standard"
    }],
    "tags": {
      "Base Image Id": "{{user `base_ami`}}",
      "Git Commit": "{{user `git_commit`}}",
      "Git Branch": "{{user `git_branch`}}",
      "Git URL": "{{user `git_url`}}",
      "Operating System": "{{user `operating_system`}}",
      "Deprecated": "No",
      "Jenkins Job Name": "{{user `jenkins_job`}}",
      "Jenkins Build Number": "{{user `jenkins_build`}}"
    },
    "ami_name": "{{user `ami_name`}}-{{isotime \"2006.01.02.03.04.05\"}}",
    "ami_users": "{{ user `ami_users` }}",
    "ami_regions": "{{ user `ami_regions` }}",
    "associate_public_ip_address": false
     }],
  "provisioners": [
    {
        "type": "shell",
        "inline": [
            "sleep 30",
            "sudo yum upgrade -y",
            "sudo yum install -y epel-release",
            "sudo yum install -y gcc python-devel libffi-devel gcc openssl-devel zip unzip",
            "sudo pip install ansible"
        ]
    },
    {
      "type": "ansible-local",
      "playbook_file": "playbook.yml",
      "playbook_dir": "./"
    }
  ]
}
```

**Comment by mwhooker** [comment]
this is an odd bug. I was able to reproduce this once by using a centos AMI and using "root" as the username. I logged in manually and it told me to log in as "centos". fixing the username fixed the issue for me.

Can you post a full json that reproduces the issue?

**Comment by shadycuz** [comment]
That is the full json? What else would you like @mwhooker I will manually login to an ami and see what the username is, shame they dont put it on the marketplace page. I am using `root` here.

**Comment by shadycuz** [comment]
Changing the username to ec2-user did fix this, but I will leave open as it's not really a desirable outcome to throw a temper tantrum because you are the root user.
