### ISSUE TITLE
ansible panic when using wrong user

### ISSUE THREAD

**Issue by mwhooker** [hashicorp/packer#6174]
reporting for a user on the mailing list

```
$ packer --version
1.2.2
```
```
$ ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/loren/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]
```
```
$ PACKER_LOG=1 packer build -debug buildbot.json
<snip>
2018/04/22 18:28:58 [INFO] (telemetry) Starting provisioner ansible
2018/04/22 18:28:58 ui: ==> digitalocean: Provisioning with Ansible...
==> digitalocean: Provisioning with Ansible...
2018/04/22 18:28:59 packer: 2018/04/22 18:28:59 SSH proxy: serving on 127.0.0.1:35145
2018/04/22 18:28:59 ui: ==> digitalocean: Executing Ansible: ansible-playbook <REDACTED>
    digitalocean:
2018/04/22 18:29:00 ui:     digitalocean:
2018/04/22 18:29:00 ui:     digitalocean: PLAY [Install python2 so that Ansible can run] *********************************
    digitalocean: PLAY [Install python2 so that Ansible can run] *********************************
2018/04/22 18:29:01 ui:     digitalocean:
    digitalocean:
2018/04/22 18:29:31 ui:     digitalocean: TASK [Install python2] *********************************************************
    digitalocean: TASK [Install python2] *********************************************************
2018/04/22 18:29:31 packer: 2018/04/22 18:29:31 SSH proxy: accepted connection
2018/04/22 18:29:31 packer: 2018/04/22 18:29:31 authentication attempt from 127.0.0.1:49448 to 127.0.0.1:35145 as loren using none
2018/04/22 18:29:31 packer: 2018/04/22 18:29:31 authentication attempt from 127.0.0.1:49448 to 127.0.0.1:35145 as loren using publickey
2018/04/22 18:29:31 packer: ==> digitalocean: Pausing before cleanup of step 'StepConnect'. Press enter to continue. 
panic: runtime error: invalid memory address or nil pointer dereference
2018/04/22 18:29:31 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99b2fc]
2018/04/22 18:29:31 packer: 
2018/04/22 18:29:31 packer: goroutine 96 [running]:
2018/04/22 18:29:31 [INFO] (telemetry) ending ansible
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*CertChecker).CheckCert(0xc42019e4b0, 0xc4201a63c8, 0x5, 0xc42037c2c0, 0xc420272158, 0x5)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/certs.go:373 +0x57c
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*CertChecker).Authenticate(0xc42019e4b0, 0x22fba00, 0xc42058c080, 0x22f4ba0, 0xc42037c2c0, 0x22e23c0, 0xc42007cae0, 0x0)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/certs.go:320 +0x85
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*CertChecker).Authenticate-fm(0x22fba00, 0xc42058c080, 0x22f4ba0, 0xc42037c2c0, 0x657, 0x657, 0x0)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/provisioner/ansible/provisioner.go:221 +0x52
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*connection).serverAuthenticate(0xc42058c080, 0xc42058a0c0, 0x11, 0x40, 0x0)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/server.go:381 +0x17c1
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*connection).serverHandshake(0xc42058c080, 0xc42058a0c0, 0xc42014cee8, 0x4d744c, 0xc4200a80f0)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/server.go:228 +0x519
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.NewServerConn(0x22fdfe0, 0xc4201b21a8, 0xc42036a0c0, 0x0, 0x0, 0xc42048d9e0, 0x89609e, 0x1)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/server.go:159 +0xe7
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/provisioner/ansible.(*adapter).Handle(0xc42019e500, 0x22fdfe0, 0xc4201b21a8, 0x22f8820, 0xc4203511e0, 0xc4201bb2c0, 0x431dc8)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/provisioner/ansible/adapter.go:67 +0x93
2018/04/22 18:29:31 packer: github.com/hashicorp/packer/provisioner/ansible.(*adapter).Serve.func1(0xc42019e500, 0x22fdfe0, 0xc4201b21a8)
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/provisioner/ansible/adapter.go:57 +0x51
2018/04/22 18:29:31 packer: created by github.com/hashicorp/packer/provisioner/ansible.(*adapter).Serve
2018/04/22 18:29:31 packer: 	/Users/phinze/go/src/github.com/hashicorp/packer/provisioner/ansible/adapter.go:56 +0x1d0
2018/04/22 18:29:31 /usr/local/bin/packer: plugin process exited
2018/04/22 18:29:31 ui: ask: ==> digitalocean: Pausing before cleanup of step 'StepConnect'. Press enter to continue.
2018/04/22 18:30:18 ui: ask: ==> digitalocean: Pausing before cleanup of step 'stepDropletInfo'. Press enter to continue.
==> digitalocean: Pausing before cleanup of step 'stepDropletInfo'. Press enter to continue. 
2018/04/22 18:30:34 ui: ask: ==> digitalocean: Pausing before cleanup of step 'stepCreateDroplet'. Press enter to continue.
==> digitalocean: Pausing before cleanup of step 'stepCreateDroplet'. Press enter to continue. 
2018/04/22 18:30:35 ui: ==> digitalocean: Destroying droplet...
==> digitalocean: Destroying droplet...
2018/04/22 18:30:35 ui: ask: ==> digitalocean: Pausing before cleanup of step 'stepCreateSSHKey'. Press enter to continue.
==> digitalocean: Pausing before cleanup of step 'stepCreateSSHKey'. Press enter to continue. 
2018/04/22 18:30:37 ui: ==> digitalocean: Deleting temporary ssh key...
==> digitalocean: Deleting temporary ssh key...
<snip>
```

**Comment by mwhooker** [comment]
updating the ssh library here to see if that fixes it, since this seems like a library bug https://github.com/hashicorp/packer/compare/fix6174

attached is linux/amd64 build with updated library if anyone wants to help test

[packer-6174-linux-amd64.zip](https://github.com/hashicorp/packer/files/1936451/packer-6174-linux-amd64.zip)

**Comment by lorenjanwilson** [comment]
The new build gave me a similar error under the same conditions, although not identical... here's the traceback

```Build 'digitalocean' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> digitalocean: unexpected EOF

==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2018/04/23 07:28:15 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99c7e9]
2018/04/23 07:28:15 packer: 
2018/04/23 07:28:15 packer: goroutine 12 [running]:
2018/04/23 07:28:15 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*CertChecker).Authenticate(0xc4201bc230, 0x2309c20, 0xc42044a580, 0x2302c40, 0xc4200fc370, 0x22f0420, 0xc4204e8150, 0x0)
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/certs.go:330 +0x79
2018/04/23 07:28:15 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*CertChecker).Authenticate-fm(0x2309c20, 0xc42044a580, 0x2302c40, 0xc4200fc370, 0x657, 0x657, 0x0)
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/provisioner/ansible/provisioner.go:221 +0x52
2018/04/23 07:28:15 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*connection).serverAuthenticate(0xc42044a580, 0xc4201d8540, 0x11, 0x40, 0x0)
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/server.go:448 +0x1a13
2018/04/23 07:28:15 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.(*connection).serverHandshake(0xc42044a580, 0xc4201d8540, 0xc420498ee8, 0x4d671c, 0xc4200c20f0)
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/server.go:251 +0x519
2018/04/23 07:28:15 packer: github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh.NewServerConn(0x230c260, 0xc4201be0e0, 0xc4201d8000, 0x70404e, 0xc4205068a0, 0xc420498f40, 0x210b399, 0x1)
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/vendor/golang.org/x/crypto/ssh/server.go:182 +0xde
2018/04/23 07:28:15 packer: github.com/hashicorp/packer/provisioner/ansible.(*adapter).Handle(0xc4201bc280, 0x230c260, 0xc4201be0e0, 0x2306a40, 0xc42000aa60, 0xc420498fc8, 0x704703)
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/provisioner/ansible/adapter.go:67 +0x93
2018/04/23 07:28:15 packer: github.com/hashicorp/packer/provisioner/ansible.(*adapter).Serve.func1(0xc4201bc280, 0x230c260, 0xc4201be0e0)
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/provisioner/ansible/adapter.go:57 +0x51
2018/04/23 07:28:15 packer: created by github.com/hashicorp/packer/provisioner/ansible.(*adapter).Serve
2018/04/23 07:28:15 packer: 	/Users/mwhooker/go/src/github.com/hashicorp/packer/provisioner/ansible/adapter.go:56 +0x1d0
2018/04/23 07:28:15 [INFO] (telemetry) ending ansible
2018/04/23 07:28:15 /home/loren/pkg/linux_amd64/packer: plugin process exited
```

**Comment by rickard-von-essen** [comment]
Could you supply the first few hundred lines of the log.

**Comment by lorenjanwilson** [comment]
Here's a gist containing the entire log: https://gist.github.com/lorenjanwilson/adca67c5b1d9f488957b6214675b06d0

**Comment by pbullian** [comment]
hi, I'm facing the same error, I tried with the latest version 1.2.4 and this build also.
https://gist.github.com/pbullian/0da342b6a9f0ce5a7276e553c1a0fb61

**Comment by rdkls** [comment]
FYI also similar error with the "too many keys in ssh agent" described on the Ansible provisioner page https://www.packer.io/docs/provisioners/ansible.html (and the recommended `ssh-add -D` worked for me)
