### ISSUE TITLE
Packer Crash

### ISSUE THREAD

**Issue by jabbera** [hashicorp/packer#6478]
Packer version: 1.2.4
Host: Alpine 3.7 (Docker in azure container instances)
Can't reproduce so no debug log.

Hi,

Many apologies, but this is run in a docker container in azure so I cannot pull the crash log. Here is what was printed to the console log that I was able to retrieve.

```
    azure-arm: [00000004] [07/11/2018 16:07:32.37] [TRACE] Downloading https://zrdfepirv2mwh01prdstr01a.blob.core.windows.net/bfd5c281a7dc4e4b84381eb0b47e3aaf/Microsoft.WindowsAzure.GuestAgent_CRPProd_uswest2_manifest.xml to file: C:\Windows\TEMP\tmp881C.tmp
    azure-arm: [00000004] [07/11/2018 16:07:32.93] [TRACE] GA version in the manifest has not changed
==> azure-arm: Restarting Machine
==> azure-arm: Waiting for machine to restart...
    azure-arm: The interface is unknown.(1717)
    azure-arm: The interface is unknown.(1717)
    azure-arm: The interface is unknown.(1717)
    azure-arm: The interface is unknown.(1717)
    azure-arm: The interface is unknown.(1717)
    azure-arm: The interface is unknown.(1717)
Build 'azure-arm' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> azure-arm: unexpected EOF

==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2018/07/11 16:07:36 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x65a996]
2018/07/11 16:07:36 packer:
2018/07/11 16:07:36 packer: goroutine 2097 [running]:
2018/07/11 16:07:36 packer: net/http.redirectBehavior(0x226d741, 0x4, 0x0, 0xc4200b0800, 0x0, 0x0, 0x0)
2018/07/11 16:07:36 packer:     /usr/local/go/src/net/http/client.go:420 +0x26
2018/07/11 16:07:36 packer: net/http.(*Client).Do(0xc420792cf0, 0xc4200b0800, 0x6, 0xc420436b80, 0x20)
2018/07/11 16:07:36 packer:     /usr/local/go/src/net/http/client.go:628 +0x308
2018/07/11 16:07:36 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.clientRequest.Post(0x2461200, 0xc4205796a0, 0xc420606700, 0xc420541c20, 0x0, 0x0, 0x0, 0x0)
2018/07/11 16:07:36 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/http.go:82 +0x2bc
2018/07/11 16:07:36 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.ClientNTLM.Post(0x2461200, 0xc4205796a0, 0xc420606700, 0xc420541c20, 0xc420223340, 0xc420541c20, 0xc4203f9680, 0x227dc33)
2018/07/11 16:07:36 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/ntlm.go:22 +0x49
2018/07/11 16:07:36 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.(*Client).sendRequest(0xc420606700, 0xc420541c20, 0xc420541c20, 0xc420541c20, 0xc42002e000, 0x7fe34b2b8000)
2018/07/11 16:07:36 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/client.go:102 +0x43
2018/07/11 16:07:36 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.(*Client).CreateShell(0xc420606700, 0x0, 0x0, 0x0)
2018/07/11 16:07:36 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/client.go:81 +0x99
2018/07/11 16:07:36 packer: github.com/hashicorp/packer/communicator/winrm.(*Communicator).Start(0xc4204f2760, 0xc4203c4d20, 0xc4206f0780, 0x2461620)
2018/07/11 16:07:36 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/communicator/winrm/communicator.go:78 +0x33
2018/07/11 16:07:36 packer: github.com/hashicorp/packer/packer/rpc.(*CommunicatorServer).Start(0xc420589080, 0xc4205419c0, 0xc4204e1b20, 0x0, 0x0)
2018/07/11 16:07:36 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/packer/rpc/communicator.go:263 +0x1ee
2018/07/11 16:07:36 packer: reflect.Value.call(0xc420434ae0, 0xc42000cdf8, 0x13, 0x226d5cd, 0x4, 0xc42071ff18, 0x3, 0x3, 0xc4207f1600, 0xc42041f6b8, ...)
2018/07/11 16:07:36 packer:     /usr/local/go/src/reflect/value.go:447 +0x969
2018/07/11 16:07:36 packer: reflect.Value.Call(0xc420434ae0, 0xc42000cdf8, 0x13, 0xc42041f718, 0x3, 0x3, 0xc42056f880, 0xc, 0xc)
2018/07/11 16:07:36 packer:     /usr/local/go/src/reflect/value.go:308 +0xa4
2018/07/11 16:07:36 packer: net/rpc.(*service).call(0xc4204f5780, 0xc4203aa460, 0xc42056f910, 0xc42056f920, 0xc420607880, 0xc420589420, 0x1b61c60, 0xc4205419c0, 0x16, 0x1bba6a0, ...)
2018/07/11 16:07:36 packer:     /usr/local/go/src/net/rpc/server.go:384 +0x14e
2018/07/11 16:07:36 packer: created by net/rpc.(*Server).ServeCodec
2018/07/11 16:07:36 packer:     /usr/local/go/src/net/rpc/server.go:480 +0x43a
2018/07/11 16:07:36 [INFO] 0 bytes written for 'stdout'
2018/07/11 16:07:36 [INFO] 0 bytes written for 'stderr'
2018/07/11 16:07:36 [ERR] Error decoding response stream 30: EOF
2018/07/11 16:07:36 [INFO] (telemetry) ending azure-arm
2018/07/11 16:07:36 ui error: Build 'azure-arm' errored: unexpected EOF
2018/07/11 16:07:36 Builds completed. Waiting on interrupt barrier...
2018/07/11 16:07:36 machine readable: error-count []string{"1"}
2018/07/11 16:07:36 ui error:
==> Some builds didn't complete successfully and had errors:
2018/07/11 16:07:36 machine readable: azure-arm,error []string{"unexpected EOF"}
2018/07/11 16:07:36 ui error: --> azure-arm: unexpected EOF
2018/07/11 16:07:36 ui:
==> Builds finished but no artifacts were created.
2018/07/11 16:07:36 [INFO] (telemetry) Finalizing.
2018/07/11 16:07:36 packer: 2018/07/11 16:07:36 [INFO] 0 bytes written for 'stdout'
2018/07/11 16:07:36 packer: 2018/07/11 16:07:36 Waiting for machine to reboot with timeout: 5m0s
2018/07/11 16:07:36 packer: 2018/07/11 16:07:36 Waiting for machine to become available...
2018/07/11 16:07:36 packer: 2018/07/11 16:07:36 Checking that communicator is connected with: 'powershell.exe -EncodedCommand ZQBjAGgAbwAgACIAJAB7AGUAbgB2ADoAQwBPAE0AUABVAFQARQBSAE4AQQBNAEUAfQAgAHIAZQBzAHQAYQByAHQAZQBkAC4AIgA='
2018/07/11 16:07:36 packer: 2018/07/11 16:07:36 [INFO] 0 bytes written for 'stderr'
2018/07/11 16:07:36 /dest/packer: plugin process exited
2018/07/11 16:07:37 waiting for all plugin processes to complete...
2018/07/11 16:07:37 /dest/packer: plugin process exited
2018/07/11 16:07:37 /dest/packer: plugin process exited
2018/07/11 16:07:37 [INFO] (telemetry) ending windows-restart
2018/07/11 16:07:37 /dest/packer: plugin process exited
2018/07/11 16:07:37 /dest/packer: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

```

**Comment by SwampDragons** [comment]
Thanks for opening this issue.  Looks like something broke inside of the winrm communicator when the windows-restart provisioner ran, but it's hard to know what...  If you manage to reproduce this or it happens on you again, I'd like to hear it. I'm at a bit of a loss for how to investigate with what we have here, but I'll think on it and see if I can come up with anything.

**Comment by jabbera** [comment]
It turns out 2 of my containers hosted in the same region but different groups experienced this same issue at the same time. My guess is this was likely some sort of catastrophic failure in the underlying container infrastructure.

**Comment by SwampDragons** [comment]
Interesting. Thanks for the report and the follow-up!
