### ISSUE TITLE
vsphere-iso EOF error

### ISSUE THREAD

**Issue by chiccat** [hashicorp/packer#6647]
Packer version: 1.2.5
Platform: MacOS X High Siera
Module: vsphere-iso

Hello,
Getting this error when I trying to run a simple json test file:

```json
{
  "builders": [
    {
      "type": "vsphere-iso",

      "vcenter_server": "vsphere.example.com",
      "insecure_connection": "true",
      "username": "user@example.com",
      "password": "password",
      "datacenter": "DC",
      "cluster": "STG",

      "vm_name": "example-ubuntu",

      "guest_os_type": "ubuntu64Guest",

      "ssh_username": "jetbrains",
      "ssh_password": "jetbrains",

      "CPUs":             1,
      "RAM":              1024,
      "RAM_reserve_all": true,

      "disk_size":        32768
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": ["ls /"]
    }
  ]
}
```

```
LUSC02VL0A7HTDH:packer user$ PACKER_LOG=1 packer build centos7.json
2018/08/31 11:54:25 [INFO] Packer version: 1.2.5
2018/08/31 11:54:25 Packer Target OS/Arch: darwin amd64
2018/08/31 11:54:25 Built with Go Version: go1.10.3
2018/08/31 11:54:25 Detected home directory from env var: /Users/user
2018/08/31 11:54:25 [DEBUG] Discovered plugin: vsphere-iso = /Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos
2018/08/31 11:54:25 Using internal plugin for digitalocean
2018/08/31 11:54:25 Using internal plugin for file
2018/08/31 11:54:25 Using internal plugin for googlecompute
2018/08/31 11:54:25 Using internal plugin for qemu
2018/08/31 11:54:25 Using internal plugin for vmware-vmx
2018/08/31 11:54:25 Using internal plugin for amazon-ebs
2018/08/31 11:54:25 Using internal plugin for amazon-ebssurrogate
2018/08/31 11:54:25 Using internal plugin for null
2018/08/31 11:54:25 Using internal plugin for scaleway
2018/08/31 11:54:25 Using internal plugin for azure-arm
2018/08/31 11:54:25 Using internal plugin for docker
2018/08/31 11:54:25 Using internal plugin for hyperv-iso
2018/08/31 11:54:25 Using internal plugin for profitbricks
2018/08/31 11:54:25 Using internal plugin for virtualbox-ovf
2018/08/31 11:54:25 Using internal plugin for vmware-iso
2018/08/31 11:54:25 Using internal plugin for amazon-instance
2018/08/31 11:54:25 Using internal plugin for ncloud
2018/08/31 11:54:25 Using internal plugin for parallels-iso
2018/08/31 11:54:25 Using internal plugin for amazon-chroot
2018/08/31 11:54:25 Using internal plugin for lxc
2018/08/31 11:54:25 Using internal plugin for openstack
2018/08/31 11:54:25 Using internal plugin for amazon-ebsvolume
2018/08/31 11:54:25 Using internal plugin for hyperv-vmcx
2018/08/31 11:54:25 Using internal plugin for oracle-oci
2018/08/31 11:54:25 Using internal plugin for triton
2018/08/31 11:54:25 Using internal plugin for virtualbox-iso
2018/08/31 11:54:25 Using internal plugin for alicloud-ecs
2018/08/31 11:54:25 Using internal plugin for lxd
2018/08/31 11:54:25 Using internal plugin for cloudstack
2018/08/31 11:54:25 Using internal plugin for oneandone
2018/08/31 11:54:25 Using internal plugin for oracle-classic
2018/08/31 11:54:25 Using internal plugin for parallels-pvm
2018/08/31 11:54:25 Using internal plugin for chef-client
2018/08/31 11:54:25 Using internal plugin for puppet-masterless
2018/08/31 11:54:25 Using internal plugin for ansible-local
2018/08/31 11:54:25 Using internal plugin for shell
2018/08/31 11:54:25 Using internal plugin for shell-local
2018/08/31 11:54:25 Using internal plugin for powershell
2018/08/31 11:54:25 Using internal plugin for chef-solo
2018/08/31 11:54:25 Using internal plugin for ansible
2018/08/31 11:54:25 Using internal plugin for file
2018/08/31 11:54:25 Using internal plugin for puppet-server
2018/08/31 11:54:25 Using internal plugin for salt-masterless
2018/08/31 11:54:25 Using internal plugin for windows-restart
2018/08/31 11:54:25 Using internal plugin for windows-shell
2018/08/31 11:54:25 Using internal plugin for converge
2018/08/31 11:54:25 Using internal plugin for checksum
2018/08/31 11:54:25 Using internal plugin for docker-import
2018/08/31 11:54:25 Using internal plugin for vsphere
2018/08/31 11:54:25 Using internal plugin for amazon-import
2018/08/31 11:54:25 Using internal plugin for atlas
2018/08/31 11:54:25 Using internal plugin for docker-tag
2018/08/31 11:54:25 Using internal plugin for googlecompute-import
2018/08/31 11:54:25 Using internal plugin for shell-local
2018/08/31 11:54:25 Using internal plugin for alicloud-import
2018/08/31 11:54:25 Using internal plugin for manifest
2018/08/31 11:54:25 Using internal plugin for vagrant
2018/08/31 11:54:25 Using internal plugin for vagrant-cloud
2018/08/31 11:54:25 Using internal plugin for docker-push
2018/08/31 11:54:25 Using internal plugin for compress
2018/08/31 11:54:25 Using internal plugin for docker-save
2018/08/31 11:54:25 Using internal plugin for googlecompute-export
2018/08/31 11:54:25 Using internal plugin for vsphere-template
2018/08/31 11:54:25 Using internal plugin for artifice
2018/08/31 11:54:25 Detected home directory from env var: /Users/user
2018/08/31 11:54:25 Attempting to open config file: /Users/user/.packerconfig
2018/08/31 11:54:25 [WARN] Config file doesn't exist: /Users/user/.packerconfig
2018/08/31 11:54:25 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[parallels-pvm:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm hyperv-vmcx:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-vmcx alicloud-ecs:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-alicloud-ecs vmware-vmx:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx amazon-ebs:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs ncloud:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-ncloud amazon-chroot:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot docker:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker amazon-ebsvolume:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebsvolume triton:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-triton vsphere-iso:/Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos digitalocean:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean file:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file googlecompute:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute qemu:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu lxd:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-lxd cloudstack:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-cloudstack oracle-classic:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oracle-classic amazon-ebssurrogate:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebssurrogate azure-arm:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm amazon-instance:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance lxc:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-lxc oracle-oci:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oracle-oci hyperv-iso:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-hyperv-iso profitbricks:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-profitbricks vmware-iso:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso scaleway:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-scaleway virtualbox-ovf:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf openstack:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack null:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null parallels-iso:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso virtualbox-iso:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso oneandone:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-oneandone] PostProcessors:map[atlas:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas vagrant:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant compress:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress docker-save:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save vsphere:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere amazon-import:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import artifice:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice shell-local:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local vagrant-cloud:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud manifest:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-manifest googlecompute-export:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-export vsphere-template:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere-template checksum:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-checksum docker-tag:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag alicloud-import:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-alicloud-import docker-push:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push docker-import:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import googlecompute-import:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-import] Provisioners:map[powershell:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell chef-solo:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo puppet-masterless:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless shell:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell shell-local:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local chef-client:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client file:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file converge:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-converge ansible-local:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local ansible:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible puppet-server:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server salt-masterless:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless windows-restart:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart windows-shell:/Users/user/bin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell]}
2018/08/31 11:54:25 Detected home directory from env var: /Users/user
2018/08/31 11:54:25 Setting cache directory: /Users/user/Documents/projects/foreman/packer/packer_cache
2018/08/31 11:54:25 Detected home directory from env var: /Users/user
2018/08/31 11:54:25 Loading builder: vsphere-iso
2018/08/31 11:54:25 Creating plugin client for path: /Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos
2018/08/31 11:54:25 Starting plugin: /Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos []string{"/Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos"}
2018/08/31 11:54:25 Waiting for RPC address for: /Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos
2018/08/31 11:54:25 packer-builder-vsphere-iso.macos: 2018/08/31 11:54:25 Plugin minimum port: 10000
2018/08/31 11:54:25 packer-builder-vsphere-iso.macos: 2018/08/31 11:54:25 Plugin maximum port: 25000
2018/08/31 11:54:25 packer-builder-vsphere-iso.macos: 2018/08/31 11:54:25 Plugin address: unix /var/folders/p_/nvwm9chs1sjb48vdpz7ngm7c0000gn/T/packer-plugin708449782
2018/08/31 11:54:25 packer-builder-vsphere-iso.macos: 2018/08/31 11:54:25 Waiting for connection...
2018/08/31 11:54:25 packer-builder-vsphere-iso.macos: 2018/08/31 11:54:25 Serving a plugin connection...
2018/08/31 11:54:25 Loading provisioner: shell
2018/08/31 11:54:25 Plugin could not be found. Checking same directory as executable.
2018/08/31 11:54:25 Current exe path: /Users/user/bin/packer
2018/08/31 11:54:25 Creating plugin client for path: /Users/user/bin/packer
2018/08/31 11:54:25 Starting plugin: /Users/user/bin/packer []string{"/Users/user/bin/packer", "plugin", "packer-provisioner-shell"}
2018/08/31 11:54:25 Waiting for RPC address for: /Users/user/bin/packer
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 [INFO] Packer version: 1.2.5
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Packer Target OS/Arch: darwin amd64
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Built with Go Version: go1.10.3
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Detected home directory from env var: /Users/user
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Attempting to open config file: /Users/user/.packerconfig
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 [WARN] Config file doesn't exist: /Users/user/.packerconfig
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Detected home directory from env var: /Users/user
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Setting cache directory: /Users/user/Documents/projects/foreman/packer/packer_cache
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Detected home directory from env var: /Users/user
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 args: []string{"packer-provisioner-shell"}
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Plugin minimum port: 10000
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Plugin maximum port: 25000
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Plugin address: unix /var/folders/p_/nvwm9chs1sjb48vdpz7ngm7c0000gn/T/packer-plugin775203554
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Waiting for connection...
2018/08/31 11:54:25 packer: 2018/08/31 11:54:25 Serving a plugin connection...
2018/08/31 11:54:25 ui: vsphere-iso output will be in this color.
2018/08/31 11:54:25 ui:
2018/08/31 11:54:25 Build debug mode: false
2018/08/31 11:54:25 Force build: false
2018/08/31 11:54:25 On error:
2018/08/31 11:54:25 Preparing build: vsphere-iso
vsphere-iso output will be in this color.

2018/08/31 11:54:25 Waiting on builds to complete...
2018/08/31 11:54:25 Starting build run: vsphere-iso
2018/08/31 11:54:25 Running builder: vsphere-iso
2018/08/31 11:54:25 [INFO] (telemetry) Starting builder vsphere-iso
2018/08/31 11:54:26 ui: ==> vsphere-iso: Creating VM...
==> vsphere-iso: Creating VM...
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: Build 'vsphere-iso' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: unexpected EOF

==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x191f730]
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos:
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: goroutine 8 [running]:
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*Driver).addStorage(0xc4201cd3b0, 0xc4204329d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x200000000000, 0x0, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/driver.go:341 +0x260
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*Driver).CreateVM(0xc4201cd3b0, 0xc4202ba408, 0xe, 0x1c61060, 0xc4201cd3b0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/driver.go:97 +0x1ba
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*StepCreateVM).Run(0xc42029e0c0, 0x24daa80, 0xc4202f6fc0, 0x0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/step_create.go:56 +0x10e
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc42028f600, 0x24daa80, 0xc4202f6fc0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/mitchellh/multistep/basic_runner.go:70 +0x1e2
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*Builder).Run(0xc42028a000, 0x24dce40, 0xc42028bd60, 0x24d7a40, 0xc4202fbed0, 0x24dbd40, 0xc42029e0b0, 0xc4201cc840, 0x0, 0xc42029a180, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/builder.go:75 +0x6dd
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc42028a020, 0x1, 0xc4201ce0fc, 0x0, 0x0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/hashicorp/packer/packer/rpc/builder.go:93 +0x1ea
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: reflect.Value.call(0xc42029a180, 0xc42029e040, 0x13, 0x1cdcf14, 0x4, 0xc420048f20, 0x3, 0x3, 0xc42029b020, 0x0, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: reflect.Value.Call(0xc42029a180, 0xc42029e040, 0x13, 0xc4202e6f20, 0x3, 0x3, 0xc4202e6f60, 0x163cf13, 0x1a3e500)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: net/rpc.(*service).call(0xc42028e000, 0xc420224400, 0xc420296040, 0xc4202a4180, 0xc42028a2a0, 0x1a4d600, 0xc4201ce0f8, 0x18a, 0x1a229c0, 0xc4201ce0fc, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: created by net/rpc.(*Server).ServeCodec
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
2018/08/31 11:54:26 [INFO] (telemetry) ending vsphere-iso
2018/08/31 11:54:26 ui error: Build 'vsphere-iso' errored: unexpected EOF
2018/08/31 11:54:26 Builds completed. Waiting on interrupt barrier...
2018/08/31 11:54:26 machine readable: error-count []string{"1"}
2018/08/31 11:54:26 ui error:
==> Some builds didn't complete successfully and had errors:
2018/08/31 11:54:26 machine readable: vsphere-iso,error []string{"unexpected EOF"}
2018/08/31 11:54:26 ui error: --> vsphere-iso: unexpected EOF
2018/08/31 11:54:26 ui:
==> Builds finished but no artifacts were created.
2018/08/31 11:54:26 [INFO] (telemetry) Finalizing.
2018/08/31 11:54:26 /Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos: plugin process exited
2018/08/31 11:54:26 waiting for all plugin processes to complete...
2018/08/31 11:54:26 /Users/user/bin/packer: plugin process exited
panic: runtime error: invalid memory address or nil pointer dereference
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x191f730]
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos:
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: goroutine 8 [running]:
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*Driver).addStorage(0xc4201cd3b0, 0xc4204329d0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x200000000000, 0x0, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/driver.go:341 +0x260
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*Driver).CreateVM(0xc4201cd3b0, 0xc4202ba408, 0xe, 0x1c61060, 0xc4201cd3b0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/driver.go:97 +0x1ba
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*StepCreateVM).Run(0xc42029e0c0, 0x24daa80, 0xc4202f6fc0, 0x0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/step_create.go:56 +0x10e
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc42028f600, 0x24daa80, 0xc4202f6fc0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/mitchellh/multistep/basic_runner.go:70 +0x1e2
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: main.(*Builder).Run(0xc42028a000, 0x24dce40, 0xc42028bd60, 0x24d7a40, 0xc4202fbed0, 0x24dbd40, 0xc42029e0b0, 0xc4201cc840, 0x0, 0xc42029a180, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/builder.go:75 +0x6dd
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc42028a020, 0x1, 0xc4201ce0fc, 0x0, 0x0)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/go/src/github.com/martezr/packer-builder-vsphere-iso/vendor/github.com/hashicorp/packer/packer/rpc/builder.go:93 +0x1ea
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: reflect.Value.call(0xc42029a180, 0xc42029e040, 0x13, 0x1cdcf14, 0x4, 0xc420048f20, 0x3, 0x3, 0xc42029b020, 0x0, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/reflect/value.go:434 +0x91f
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: reflect.Value.Call(0xc42029a180, 0xc42029e040, 0x13, 0xc4202e6f20, 0x3, 0x3, 0xc4202e6f60, 0x163cf13, 0x1a3e500)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: net/rpc.(*service).call(0xc42028e000, 0xc420224400, 0xc420296040, 0xc4202a4180, 0xc42028a2a0, 0x1a4d600, 0xc4201ce0f8, 0x18a, 0x1a229c0, 0xc4201ce0fc, ...)
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/net/rpc/server.go:387 +0x144
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: created by net/rpc.(*Server).ServeCodec
2018/08/31 11:54:26 packer-builder-vsphere-iso.macos: 	/usr/local/go/src/net/rpc/server.go:481 +0x404
2018/08/31 11:54:26 [INFO] (telemetry) ending vsphere-iso
2018/08/31 11:54:26 ui error: Build 'vsphere-iso' errored: unexpected EOF
2018/08/31 11:54:26 Builds completed. Waiting on interrupt barrier...
2018/08/31 11:54:26 machine readable: error-count []string{"1"}
2018/08/31 11:54:26 ui error:
==> Some builds didn't complete successfully and had errors:
2018/08/31 11:54:26 machine readable: vsphere-iso,error []string{"unexpected EOF"}
2018/08/31 11:54:26 ui error: --> vsphere-iso: unexpected EOF
2018/08/31 11:54:26 ui:
==> Builds finished but no artifacts were created.
2018/08/31 11:54:26 [INFO] (telemetry) Finalizing.
2018/08/31 11:54:26 /Users/user/.packer.d/plugins/packer-builder-vsphere-iso.macos: plugin process exited
2018/08/31 11:54:26 waiting for all plugin processes to complete...
2018/08/31 11:54:26 /Users/user/bin/packer: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/hashicorp/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by SwampDragons** [comment]
vsphere-iso is a project maintained independently of Packer; we can't troubleshoot crashes because this builder isn't in our codebase. I think you need to open an issue with https://github.com/jetbrains-infra/packer-builder-vsphere
