### ISSUE TITLE
packer-provisioner-windows-update.exe failing to get updates in created image

### ISSUE THREAD

**Issue by panoschatz** [hashicorp/packer#6656]
Using packer-provisioner-windows-update.exe to update the custom image and the deployment fails giving the error below. The .exe file is in the same directory as the script and has run successfully in the past.

Packer  version 1.2.5

Running on Windows Server 2016 and creating a Windows Server-2016-with-Containers image in Azure

Output:

```
    azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing m
odules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Machine successfully restarted, moving on
==> azure-arm: Uploading the Windows update elevated script...
==> azure-arm: Uploading the Windows update script...
==> azure-arm: Running Windows update...
    azure-arm: #< CLIXML
    azure-arm: Searching for Windows updates...
    azure-arm: ERROR: Exception from HRESULT: 0x80072F8F
    azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 141
    azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1
    azure-arm: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80072F8F): Exception from HRESULT: 0x80072F8F
    azure-arm: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    azure-arm: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject , String )
    azure-arm: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    azure-arm: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
    azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing m
odules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>
-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
```

Script used for the image creation and update (interpolations are being used for the actual values, but the script, excluding the "type": "windows-update" part works fine, producing a deployable image):

```
{
    "variables": {
        "v_subscription_id": "{{env `ENV_subscription_id`}}",
        "v_tenant_id": "{{env `ENV_tenant_id`}}",
        "v_client_id": "{{env `ENV_service_principle_id`}}",
        "v_object_id": "{{env `ENV_service_principle_objectid`}}",
        "v_client_secret": "{{env `ENV_service_principle_secret`}}"
    },
    "builders": [
        {
            "type": "azure-arm",
            "client_id": "{{user `v_client_id`}}",
            "client_secret": "{{user `v_client_secret`}}",
            "tenant_id": "{{user `v_tenant_id`}}",
            "subscription_id": "{{user `v_subscription_id`}}",
            "object_id": "{{user `v_object_id`}}",
            "managed_image_resource_group_name": "{{user `v_image_resource_group`}}",

            "virtual_network_name":"{{user `v_virtual_network_name`}}",
            "virtual_network_resource_group_name" : "{{user `v_virtual_network_resource_group_name`}}",
            "virtual_network_subnet_name" : "{{user `v_virtual_network_subnet_name`}}",

            "managed_image_name": "{{user `v_image_name`}}",
            "os_type": "{{user `v_image_os_type`}}",
            "image_publisher": "{{user `v_image_publisher`}}",
            "image_offer": "{{user `v_image_offer`}}",
            "image_sku": "{{user `v_image_sku`}}",
            "image_version": "{{user `v_image_sku_version`}}",
            "communicator": "winrm",
            "winrm_use_ssl": "true",
            "winrm_insecure": "true",
            "winrm_timeout": "15m",
            "winrm_username": "packer",
            "azure_tags": {
                "dept": "{{user `v_image_tag_dept`}}",
                "createdDate": "{{isotime \"2006-01-02\"}}",
                "updatedBy": "{{user `v_image_tag_updatedBy`}}",
                "release": "{{user `v_image_tag_release`}}",
				"creationDate": "{{user `v_image_tag_creationDate`}}"
            },
            "location": "{{user `v_image_location`}}",
            "vm_size": "{{user `v_image_vm_size`}}"
        }
    ],
    "provisioners": [

        {
            "type": "windows-restart",
            "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
        },

        {
            "type": "windows-update",
            "filters": [
                "exclude:$_.Title -like '*Preview*'",
                "include:$_.Title -like '*Cumulative Update for Windows*'",
                "include:$_.Title -like '*Windows Defender Antivirus*'",
                "include:$_.Title -like '*Update for Windows Server 2016*'",
                "include:$_.Title -like '*Windows Malicious Software Removal Tool*'",
                "include:$_.AutoSelectOnWebSites"        
            ]            
        },
        
        
        {
            "type": "windows-restart",
            "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
        },        

        {
            "type": "powershell",
            "inline": [
                "winrm quickconfig -q",
                "winrm set winrm/config/winrs '@{MaxMemoryPerShellMB=\"300\"}'",
                "winrm set winrm/config '@{MaxTimeoutms=\"1800000\"}'",
                "winrm set winrm/config/service '@{AllowUnencrypted=\"true\"}'",
                "winrm set winrm/config/service/auth '@{Basic=\"true\"}'",
                "Get-NetFirewallPortFilter | ?{$_.LocalPort -eq 5985 } | Get-NetFirewallRule | ?{ $_.Direction -eq \"Inbound\" -and $_.Profile -eq \"Public\" -and $_.Action -eq \"Allow\"} | Set-NetFirewallRule -RemoteAddress \"Any\" ",
                "$newNetworkDialog = New-Item -Path HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Network\\NewNetworkWindowOff -Force",
                "Stop-Service -Name tiledatamodelsvc -nowait -force -confir:$false",
                "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
                "#while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 30  } else { break } }"
            ]
        }

    ]

}
```

**Comment by arizvisa** [comment]
Ftr, the error code 0x80072F8F seems to be related to windows activation failure.

Some external forum posts like the following suggest to verify the date/time of the machine as when windows tries to verify the ssl certificate for windows update, the time skew results in the certificate validation failing.

https://answers.microsoft.com/en-us/windows/forum/windows_7/error-code-0x80072f8f/d5006dbe-5946-4d68-8f08-8620eeb65efd

**Comment by panoschatz** [comment]
This suggests configuration in the temporary Packer VM, which negates the whole automated image creation process. We've also run this many times in the past successfully.

From the below lines I understand that the required script  from the exe is not uploaded correctly:
```
azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 141
azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1
```
but using Wireshark I could see Packer only uses ports 5985/5986 to the temprary VM, to which I can connect successfully. No drops or firewall blocking those.

**Comment by SwampDragons** [comment]
Actually, can you share a few previous loglines? Specifically, we run this command to make sure powershell modules have loaded: winrm.Powershell(`echo "${env:COMPUTERNAME} restarted."` and I'd like to know if you're seeing the output from that echo in your logs.

**Comment by panoschatz** [comment]
Please below see the output. I've used the "pause" command and the variable you specified above.

It could be related to our current environment, as I'm not facing this issue in a "clean" lab subscription. 

We were suspecting an issue with date/time format, when packer issues the certificate, but running from a non-domain joined VM in the same environment still results in the same error.

```
==> azure-arm: Waiting for WinRM to become available...
    azure-arm: #< CLIXML
    azure-arm: WinRM connected.
    azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing m
odules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>
-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Connected to WinRM!
==> azure-arm: Restarting Machine
==> azure-arm: Waiting for machine to restart...
    azure-arm: A system shutdown is in progress.(1115)
    azure-arm: restarted.
    azure-arm: pkrvm7f9dynp1tf restarted.
    azure-arm: #< CLIXML
    azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing m
odules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Machine successfully restarted, moving on
==> azure-arm: Pausing 1m0s before the next provisioner...
==> azure-arm: Uploading the Windows update elevated script...
==> azure-arm: Uploading the Windows update script...
==> azure-arm: Running Windows update...
    azure-arm: #< CLIXML
    azure-arm: Searching for Windows updates...
    azure-arm: ERROR: Exception from HRESULT: 0x80072F8F
    azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 141
    azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1
    azure-arm: ERROR EXCEPTION: System.Runtime.InteropServices.COMException (0x80072F8F): Exception from HRESULT: 0x80072F8F
    azure-arm: ERROR EXCEPTION:    at System.Management.Automation.ComInterop.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, ComMethodDesc method, Object[] args, UInt32 argErr)
    azure-arm: ERROR EXCEPTION:    at CallSite.Target(Closure , CallSite , ComObject , String )
    azure-arm: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    azure-arm: ERROR EXCEPTION:    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
    azure-arm: ERROR EXCEPTION:    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
    azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing m
odules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>
-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
```

**Comment by SwampDragons** [comment]
> We've also run this many times in the past successfully.
Has anything changed? Was this with a previous version of packer?

**Comment by panoschatz** [comment]
Not really. I just ran it again in my test/lab subscription and it worked fine.

There is something in the current environment that stops it from working as expected. When I'm doing packet tracing I can see comunication from the VM that runs the packer job to the packer temp VM only over WinRM on 5986.

I can confirm that network connectivity via WinRM between both VMs is fine.

Does the below mean that something is not uploaded properly on the temp VM ScriptBlock, No File:line 1?
```
==> azure-arm: Uploading the Windows update elevated script...
==> azure-arm: Uploading the Windows update script...
==> azure-arm: Running Windows update...
    azure-arm: #< CLIXML
    azure-arm: Searching for Windows updates...
    azure-arm: ERROR: Exception from HRESULT: 0x80072F8F
    azure-arm: ERROR: at <ScriptBlock>, C:\Windows\Temp\packer-windows-update.ps1: line 141
    azure-arm: ERROR: at <ScriptBlock>, <No file>: line 1
```
Cause otherwise we can isolate the error to the temp VM not conecting to the update services properly, either via the proxy or something else.

**Comment by SwampDragons** [comment]
I've never seen this error before but it's not one of the ones we typically see if an upload fails or a file isn't present. In that case I'd expect to see an error complaining that our execute_command is invalid. So I think this is something broken in the environment.

**Comment by arizvisa** [comment]
This maybe newbish because I've never connected to azure before, but is it possible that the time/date is not correct? Can you execute `get-date` from a shell provisioner via powershell or connect to it and grab the current time/date for the VM?

**Comment by panoschatz** [comment]
It believe the proxy settings that are blocking the updates. I'm  building a few new images applying the OS proxy settings to the temp VM and will confirm whether it resolves the issue.

**Comment by panoschatz** [comment]
I can now confirm that it was the proxy that was stopping the updates from being installed.

Just as an FYI, using the powershell provisioner I added the proxy setting in the packer temp VM, bypassing the Azure public DNS IP to allow the VM agent to register and it works fine.

Issue can now be closed. Thanks for your help everyone.

**Comment by arizvisa** [comment]
@panoschatz, I think you should be able to close this comment yourself since you were the original reporter.

**Comment by Marcus-James-Adams** [comment]
@panoschatz do you mind sharing the code you used to update the proxy settings to get around this issue, please?

**Comment by panoschatz** [comment]
Hi @Marcus-James-Adams . Sure, see provisioner blocks below. In both cases I also had to by-pass the Azure default DNS (168.63.129.16). I can't exactly remember why I had to remove the Azure agents, but I recall they were causing problems.

Also, avoid using very small VM sizes when generalising images, as they tend to not spinup fast enough in terms of services etc and packer thinks they're not working as they should.

This is for a fully fledged Win2016 Datacenter image:
```
{
   "type":"powershell",
   "inline":[
      "Set-Service RdAgent -StartupType Disabled",
      "Set-Service WindowsAzureTelemetryService -StartupType Disabled",
      "Set-Service WindowsAzureGuestAgent -StartupType Disabled",
      "remove-itemproperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\SysPrepExternal\\Generalize' -Name '*'",
      "REG ADD 'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings' /v ProxyEnable /t REG_DWORD /d '00000001' /f",
      "REG ADD 'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings' /v ProxyServer /t REG_SZ /d '<yourproxy:port>' /f",
      "REG ADD 'HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings' /v ProxyOverride /t REG_SZ /d '<local>' /f",
      "netsh winhttp set proxy <yourproxy:port> bypass-list='168.63.129.16,<local>'"
   ],
   "pause_before":"150s"
}
```

This is for a Win2016-Core-1803:
```
{
   "type":"powershell",
   "inline":[
      "Set-Service RdAgent -StartupType Disabled",
      "Set-Service WindowsAzureTelemetryService -StartupType Disabled",
      "Set-Service WindowsAzureGuestAgent -StartupType Disabled",
      "remove-itemproperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\SysPrepExternal\\Generalize' -Name '*'",
      "New-WinUserLanguageList -Language 'en-gb' | Set-WinUserLanguageList -Force",
      "Uninstall-WindowsFeature -Name Windows-Defender",
      "netsh winhttp set proxy <yourproxy:port> bypass-list='168.63.129.16,<local>'"
   ],
   "pause_before":"150s"
}
```
