### ISSUE TITLE
openstack: crashes if a non existing network name is used in floating_ip_pool 

### ISSUE THREAD

**Issue by rickard-von-essen** [hashicorp/packer#6885]
```
==> Builds finished but no artifacts were created.
2018/10/19 12:53:43 packer: panic: interface conversion: interface {} is nil, not []interface {}
2018/10/19 12:53:43 packer:
2018/10/19 12:53:43 packer: goroutine 42 [running]:
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/vendor/github.com/gophercloud/gophercloud.Result.extractIntoPtr(0xc0006a40a0, 0xc000324cf0, 0xc000324db0, 0x0, 0x0, 0x2a041e0, 0xc000451300, 0x31e1e54, 0x8, 0x0, ...)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/vendor/github.com/gophercloud/gophercloud/results.go:93 +0xc18
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/vendor/github.com/gophercloud/gophercloud.Result.ExtractIntoSlicePtr(0xc0006a40a0, 0xc000324cf0, 0xc000324db0, 0x0, 0x0, 0x2a041e0, 0xc000451300, 0x31e1e54, 0x8, 0xd, ...)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/vendor/github.com/gophercloud/gophercloud/results.go:200 +0x1ba
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks.ExtractNetworksInto(0x34bf200, 0xc0005d03c0, 0x2a041e0, 0xc000451300, 0x34bf200, 0xc0005d0180)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go:120 +0xd6
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/builder/openstack.GetFloatingIPNetworkIDByName(0xc0000ecbe0, 0xc0000d86b6, 0x7, 0x0, 0x34a6820, 0xc00056b0c0, 0xc00068f3b0)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/builder/openstack/networks.go:112 +0x1a3
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/builder/openstack.CheckFloatingIPNetwork(0xc0000ecbe0, 0xc0000d86b6, 0x7, 0x2a1f7e0, 0xc00040a4d0, 0x140, 0x52)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/builder/openstack/networks.go:89 +0x63
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/builder/openstack.(*StepAllocateIp).Run(0xc00068f440, 0x34bfd80, 0xc00004d540, 0x34bda80, 0xc00068f3b0, 0x0)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/builder/openstack/step_allocate_ip.go:83 +0xade
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc00004d500, 0x34bda80, 0xc00068f3b0)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/helper/multistep/basic_runner.go:72 +0x222
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/builder/openstack.(*Builder).Run(0xc0000e1100, 0x34c6320, 0xc0005d8d60, 0x34b2e80, 0xc00069c1a0, 0x34c0140, 0xc0001da110, 0x10bb3ec, 0x2a8e3a0, 0x2a8e3a0, ...)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/builder/openstack/builder.go:151 +0xbb3
2018/10/19 12:53:43 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc0000ea480, 0x1, 0xc0005e6090, 0x0, 0x0)
2018/10/19 12:53:43 packer:     /Users/rickard/src/go-code/src/github.com/hashicorp/packer/packer/rpc/builder.go:94 +0x1cd
2018/10/19 12:53:43 packer: reflect.Value.call(0xc0001ca4e0, 0xc0001e00b0, 0x13, 0x31dba2a, 0x4, 0xc000163f18, 0x3, 0x3, 0xc0001d2040, 0xb40000005a, ...)
2018/10/19 12:53:43 packer:     /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:447 +0x449
2018/10/19 12:53:43 packer: reflect.Value.Call(0xc0001ca4e0, 0xc0001e00b0, 0x13, 0xc000318f18, 0x3, 0x3, 0x0, 0x0, 0x0)
2018/10/19 12:53:43 packer:     /usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:308 +0xa4
2018/10/19 12:53:43 packer: net/rpc.(*service).call(0xc0001e2240, 0xc0003d61e0, 0xc0001e61d8, 0xc0001e6290, 0xc0001ee200, 0xc0001aab20, 0x2b006c0, 0xc0005e608c, 0x18a, 0x2a8e3a0, ...)
2018/10/19 12:53:43 packer:     /usr/local/Cellar/go/1.11.1/libexec/src/net/rpc/server.go:384 +0x14e
2018/10/19 12:53:43 packer: created by net/rpc.(*Server).ServeCodec
2018/10/19 12:53:43 packer:     /usr/local/Cellar/go/1.11.1/libexec/src/net/rpc/server.go:481 +0x47e
2018/10/19 12:53:43 /Users/rickard/src/go-code/bin/packer: plugin process exited
2018/10/19 12:53:43 [INFO] (telemetry) ending openstack
2018/10/19 12:53:43 ui error: Build 'openstack' errored: unexpected EOF
2018/10/19 12:53:43 Builds completed. Waiting on interrupt barrier...
2018/10/19 12:53:43 machine readable: error-count []string{"1"}
2018/10/19 12:53:43 ui error:
```

**Comment by rickard-von-essen** [comment]
Seems like an upstream bug similar to https://github.com/gophercloud/gophercloud/issues/1269.

(Updating to the latest gohercloud 0719c6b22f30132b0ae6c90b038e0d50992107b0 doesn't resolve the issue).
