### ISSUE TITLE
Bad password  from {{ .WinRMPassword }} (possibly?) from Azure-ARM builder?

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/packer#6944]
## Overview

Running Packer with the `azure-arm` builder and then attempting to use the credentials in `shell-local` provisioner to run Ansible results in an access denied error message to the target node. 

This is being done for a Windows instance, note that identical steps done with the `amazon-ebs` builder work fine, hence my suspicion.  

## Packer Version

```
packer --version
1.3.1
```

## Details

The crazy details are within, but essentially it all comes down to what I'm doing in the provisioners via template vars I get from the `azure-arm` builder.  High level flow:

* Builder does it's thing specifically with `os_type` defined (which supposedly configures winrm)
* Initial `powershell` provisioners run (perfectly fine) to gather required information off the host for configuring an ansible inventory file (this uses {{.WinRMPassword}} to populate a password into said file)
* `shell-local` is used to call anisble and reference said inventory file, but fails to login citing bad username/password.

### Sample Packer JSON

The below json has been simplified and had aws builder/provisioning steps removed.

```json
{
    "description": "universal builder",
    "min_packer_version": "1.2.4",
    "variables": {
        "artifact_server": "{{ env `ARTIFACT_SERVER` }}",
        "azure_subscription": "{{ env `AZURE_SUBSCRIPTION_ID` }}",
        "azure_clientid": "{{ env `AZURE_CLIENT_ID` }}",
        "azure_secret": "{{ env `AZURE_SECRET` }}",
        "azure_tenant": "{{ env `AZURE_TENANT` }}"
    },
    "builders": [
      {
        "type": "azure-arm",
        "os_type": "Windows",
        "image_publisher": "MicrosoftWindowsServer",
        "image_offer": "WindowsServer",
        "image_sku": "2016-Datacenter",
        "location": "South Central US",
        "vm_size": "Standard_DS2_v2",
        "virtual_network_name": "network-oz-southcentralus-vnet",
        "virtual_network_resource_group_name": "network-oz-southcentralus-rg",
        "virtual_network_subnet_name": "srv1-oz-southcentralus-subnet",
        "async_resourcegroup_delete": "true",
        "client_id": "{{ user `azure_clientid` }}",
        "client_secret": "{{ user `azure_secret` }}",
        "subscription_id": "{{ user `azure_subscription` }}",
        "managed_image_resource_group_name": "packertest",
        "managed_image_name": "cg-win-2016-{{isotime \"20060102_1504\"}}",
        "azure_tags": {
            "Name": "Windows 2016 encrypted",
            "OS": "Windows",
            "OSVER": "2016"
        },
        "communicator": "winrm",
        "winrm_username": "packer",
        "winrm_use_ssl": true,
        "winrm_insecure": true
      }
    ],
    "provisioners": [
        {
            "type": "powershell",
            "scripts": [
                "{{template_dir}}/scripts/Setup_AnsibleInventory.ps1"
            ],
            "environment_vars": [
                "ARTIFACT_SERVER={{user `artifact_server`}}",
                "PACKER_WINRMINSEC=True",
                "PACKER_PASSWORD={{.WinRMPassword}}",
                "PACKER_USESSL=True"
            ]
        },
        {
            "type": "file",
            "source": "inventory.txt",
            "destination": "inventory.txt",
            "direction": "download"
        },
        {
            "type": "shell-local",
            "command": "ansible-playbook playbooks/apply_roles.yml -i ./inventory.txt -e disable_reboot=True -vvvvv"
        },
        {
            "type": "windows-restart",
        },
        {
            "type": "powershell",
            "inline": [
                "Remove-Item -Path $env:TEMP\\* -Force -Recurse",
                "Remove-Item -Path $env:WINDIR\\Temp\\* -Force -Recurse"
            ]
        },
        {
            "type": "powershell",
            "only": ["azure-arm"],
            "inline": [
                "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
                "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
            ]
        }
    ]
}
```

### Setup_AnsibleInventory.ps1

This little script gets run on the target then downloaded.  Why?  On the server I can use environment variables and powershell to query things not provided by Packer templates (or they are so poorly documented I can't discover them).  things like host IP and username.  So the password is "passed on" to PowerShell so it can write the file, then downloaded (see json).

```powershell
param(
    [string]$artifact_server = $env:ARTIFACT_SERVER,
    [string]$winrm_insecure = $env:PACKER_WINRMINSEC,
    [string]$winrm_username = $env:USERNAME,
    [string]$winrm_password = $env:PACKER_PASSWORD,
    [string]$winrm_use_ssl = $env:PACKER_USESSL
)

#Convert 'packer speak' of true/false to actual values
If ([System.Convert]::ToBoolean($winrm_use_ssl)) {$winrm_port = '5986'} else {$winrm_port = '5985'}    
If ([System.Convert]::ToBoolean($winrm_insecure)) {$winrm_certval = 'ignore'} else {$winrm_certval = 'validate'}

#Grab current IP
$IPAddress = (get-WmiObject Win32_NetworkAdapterConfiguration|Where-Object {$_.Ipaddress.length -gt 1}).ipaddress[0]

#build a template
$content = "[default]`n[[IPADDRESS]]`n`n[default:vars]`nansible_connection=winrm`nansible_port=[[PORT]]`nansible_winrm_transport=basic`nansible_user=[[USER]]`nansible_password=[[PASS]]`nansible_winrm_message_encryption=auto`nansible_winrm_server_cert_validation=[[INSEC]]`nartifact_server=[[ARTSERVER]]`n"

#Update content with connectionstrings
$content = $content.replace('[[IPADDRESS]]',$IPAddress)
$content = $content.replace('[[USER]]',$winrm_username)
$content = $content.replace('[[PASS]]',$winrm_password)
$content = $content.replace('[[PORT]]',$winrm_port)
$content = $content.replace('[[INSEC]]',$winrm_certval)
$content = $content.replace('[[ARTSERVER]]',$artifact_server)

#commit the file
Set-Content -Path inventory.txt -Value $content -force
```

## Debug output

Below is the debug outout.  it's rather lengthy ... so I only grabbed the provider steps (one imediately before that shows providers _are_ in fact connecting to WinRM ... then the one called by shell-local that cites a bad username/password.  Please note that you cna inspct the downlaoded inventory.txt and verify that the username/password are infact populated.  PLUS, as mentioned earlier, this exact provisioner combination works unaltered in AWS which implies something funky is a foot.

```debug
==> azure-arm: Connected to WinRM!
2018/10/31 20:46:11 packer: 2018/10/31 20:46:11 Connected to machine
2018/10/31 20:46:11 packer: 2018/10/31 20:46:11 Running the provision hook
2018/10/31 20:46:11 [INFO] (telemetry) Starting provisioner powershell
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: /home/me/ans_code/misc_scripts/packer/w2016_encrypted/scripts/Setup_AnsibleInventory.ps1
2018/10/31 20:46:11 packer: 2018/10/31 20:46:11 Opening /home/me/ans_code/misc_scripts/packer/w2016_encrypted/scripts/Setup_AnsibleInventory.ps1 for reading
2018/10/31 20:46:11 packer: 2018/10/31 20:46:11 Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5bda1302-24f9-1932-c261-4b5b3f3d8be5.ps1
2018/10/31 20:46:11 packer: 2018/10/31 20:46:11 [INFO] 227 bytes written for 'uploadData'
2018/10/31 20:46:11 [INFO] 227 bytes written for 'uploadData'
2018/10/31 20:46:11 packer: 2018/10/31 20:46:11 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5bda1302-24f9-1932-c261-4b5b3f3d8be5.ps1'
2018/10/31 20:46:16 packer: #< CLIXML
2018/10/31 20:46:20 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2018/10/31 20:46:20 packer: 2018/10/31 20:46:20 [INFO] 1445 bytes written for 'uploadData'
2018/10/31 20:46:20 [INFO] 1445 bytes written for 'uploadData'
2018/10/31 20:46:20 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2018/10/31 20:46:20 Uploading file to 'c:/Windows/Temp/script-5bda1302-b4c5-4c6e-bcd8-d8c765e74156.ps1'
2018/10/31 20:46:26 packer: #< CLIXML
2018/10/31 20:46:31 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2018/10/31 20:46:32 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2018/10/31 20:46:32 [INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5bda1302-24f9-1932-c261-4b5b3f3d8be5.ps1; &'c:/Windows/Temp/script-5bda1302-b4c5-4c6e-bcd8-d8c765e74156.ps1';exit $LastExitCode }"
2018/10/31 20:46:36 packer: 2018/10/31 20:46:36 [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5bda1302-24f9-1932-c261-4b5b3f3d8be5.ps1; &'c:/Windows/Temp/script-5bda1302-b4c5-4c6e-bcd8-d8c765e74156.ps1';exit $LastExitCode }"' exited with code: 0
2018/10/31 20:46:36 [INFO] 0 bytes written for 'stdout'
2018/10/31 20:46:36 [INFO] 0 bytes written for 'stderr'
2018/10/31 20:46:36 [INFO] RPC client: Communicator ended with: 0
2018/10/31 20:46:36 [INFO] RPC endpoint: Communicator ended with: 0
2018/10/31 20:46:36 packer: 2018/10/31 20:46:36 [INFO] RPC endpoint: Communicator ended with: 0
2018/10/31 20:46:36 [INFO] (telemetry) ending powershell
2018/10/31 20:46:36 [INFO] (telemetry) Starting provisioner file
2018/10/31 20:46:36 packer: 2018/10/31 20:46:36 [INFO] 0 bytes written for 'stdout'
2018/10/31 20:46:36 packer: 2018/10/31 20:46:36 [INFO] 0 bytes written for 'stderr'
2018/10/31 20:46:36 packer: 2018/10/31 20:46:36 [INFO] RPC client: Communicator ended with: 0
==> azure-arm: Downloading inventory.txt => inventory.txt
2018/10/31 20:46:42 [INFO] 297 bytes written for 'downloadWriter'
2018/10/31 20:46:42 packer: 2018/10/31 20:46:42 [INFO] 297 bytes written for 'downloadWriter'
2018/10/31 20:46:42 [INFO] (telemetry) ending file
2018/10/31 20:46:42 [INFO] (telemetry) Starting provisioner shell-local
2018/10/31 20:46:42 packer: 2018/10/31 20:46:42 [INFO] (shell-local): Prepending inline script with #!/bin/sh -e
==> azure-arm: Running local shell script: /tmp/packer-shell998931244
2018/10/31 20:46:42 packer: 2018/10/31 20:46:42 [INFO] (shell-local): starting local command: /bin/sh -c PACKER_BUILDER_TYPE='azure-arm' PACKER_BUILD_NAME='azure-arm'  /tmp/packer-shell998931244
2018/10/31 20:46:42 packer: 2018/10/31 20:46:42 [INFO] (shell-local communicator): Executing local shell command [/bin/sh -c PACKER_BUILDER_TYPE='azure-arm' PACKER_BUILD_NAME='azure-arm'  /tmp/packer-shell998931244]
    azure-arm: ansible-playbook 2.5.5
    azure-arm:   config file = /home/me/ans_code/ansible.cfg
    azure-arm:   configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
    azure-arm:   ansible python module location = /users/ansible/lib/python2.7/site-packages/ansible
    azure-arm:   executable location = /users/ansible/bin/ansible-playbook
    azure-arm:   python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
    azure-arm: Using /home/me/ans_code/ansible.cfg as config file
    azure-arm: Reading vault password file: /home/me/.ssh/vault_pass.txt
    azure-arm: setting up inventory plugins
    azure-arm: Parsed /home/me/ans_code/misc_scripts/packer/w2016_encrypted/inventory.txt inventory source with ini plugin
    azure-arm: Loading callback plugin default of type stdout, v2.0 from /users/ansible/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc
    azure-arm: Loading callback plugin profile_tasks of type aggregate, v2.0 from /users/ansible/lib/python2.7/site-packages/ansible/plugins/callback/profile_tasks.pyc
    azure-arm:
    azure-arm: PLAYBOOK: apply_roles.yml ******************************************************
    azure-arm: 1 plays in playbooks/apply_roles.yml
    azure-arm:
    azure-arm: PLAY [Provisioning playbook to apply additional roles] *************************
    azure-arm:
    azure-arm: TASK [Gathering Facts] *********************************************************
    azure-arm: task path: /home/me/ans_code/misc_scripts/packer/w2016_encrypted/playbooks/apply_roles.yml:2
    azure-arm: Wednesday 31 October 2018  20:46:43 +0000 (0:00:00.111)       0:00:00.111 *****
    azure-arm: Using module file /users/ansible/lib/python2.7/site-packages/ansible/modules/windows/setup.ps1
    azure-arm: <172.17.147.15> ESTABLISH WINRM CONNECTION FOR USER: packer on PORT 5986 TO 172.17.147.15
    azure-arm: checking if winrm_host 172.17.147.15 is an IPv6 address
    azure-arm: <172.17.147.15> WINRM CONNECT: transport=basic endpoint=https://172.17.147.15:5986/wsman
    azure-arm: <172.17.147.15> WINRM CONNECTION ERROR: the specified credentials were rejected by the server
    azure-arm: Traceback (most recent call last):
    azure-arm:   File "/users/ansible/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 382, in _winrm_connect
    azure-arm:     self.shell_id = protocol.open_shell(codepage=65001)  # UTF-8
    azure-arm:   File "/users/ansible/lib/python2.7/site-packages/winrm/protocol.py", line 157, in open_shell
    azure-arm:     res = self.send_message(xmltodict.unparse(req))
    azure-arm:   File "/users/ansible/lib/python2.7/site-packages/winrm/protocol.py", line 234, in send_message
    azure-arm:     resp = self.transport.send_message(message)
    azure-arm:   File "/users/ansible/lib/python2.7/site-packages/winrm/transport.py", line 256, in send_message
    azure-arm:     response = self._send_message_request(prepared_request, message)
    azure-arm:   File "/users/ansible/lib/python2.7/site-packages/winrm/transport.py", line 266, in _send_message_request
    azure-arm:     raise InvalidCredentialsError("the specified credentials were rejected by the server")
    azure-arm: InvalidCredentialsError: the specified credentials were rejected by the server
    azure-arm: fatal: [172.17.147.15]: UNREACHABLE! => {
    azure-arm:     "changed": false,
    azure-arm:     "msg": "basic: the specified credentials were rejected by the server",
    azure-arm:     "unreachable": true
    azure-arm: }
    azure-arm:  to retry, use: --limit @/home/me/ans_code/misc_scripts/packer/w2016_encrypted/playbooks/apply_roles.retry
    azure-arm:
    azure-arm: PLAY RECAP *********************************************************************
    azure-arm: 172.17.147.15              : ok=0    changed=0    unreachable=1    failed=0
    azure-arm:
    azure-arm: Wednesday 31 October 2018  20:46:43 +0000 (0:00:00.308)       0:00:00.419 *****
    azure-arm: ===============================================================================
    azure-arm: Gathering Facts --------------------------------------------------------- 0.31s
    azure-arm: /home/me/ans_code/misc_scripts/packer/w2016_encrypted/playbooks/apply_roles.yml:2
2018/10/31 20:46:43 [INFO] (telemetry) ending shell-local
==> azure-arm: Cleanup requested, deleting resource group ...
```

It's possible Azure is doing something "special" and locking down what can connect to an Azure instance during provisioning?  But all I see is that "basic: the specified credentials were rejected by the server" ... which means I'm making it to the target node ... but the password is getting actively rejected.  It seems like the password being returned in .WinRMPassword is somehow incorrect?

**Comment by boumenot** [comment]
Azure does use a different authentication mechanism. Support for this auth method had to be added to the WinRM communicator that Packer uses.  The library is call  ed [Azure/go-ntlmssp](https://github.com/Azure/go-ntlmssp).  I don't know if Ansible supports it or not.

**Comment by Justin-DynamicD** [comment]
Well that did it.  Changing my ansible inventory file to pass ntlm allowed the connection.  This means there's in fact nothing wrong with the password being passed and the error message of "InvalidCredentialsError: the specified credentials were rejected by the server" was just a red herring, and really not your problem at all.  Thank you for the silver bullet!

I'll probably open a feature request from this, however.  It would be wonderful to have more vars like .WinRMPassword available, especially as shell-local is the recommended way to kick off ansible code.  Things like .WinRMUser (as different builders will often default to different users), .WinRMCom (to spot differences like basic, ntlm) ... basically exposing this "stuff" to the provisioners would be a great boon.

Thank you again for the insight!

**Comment by SwampDragons** [comment]
@Justin-DynamicD I agree, and we're trying to figure out a good way to share more information between the builders and the provisioners.
