### ISSUE TITLE
panic: interface conversion: interface is nil, not packer.Communicator

### ISSUE THREAD

**Issue by jorgelon** [hashicorp/packer#7238]
I am trying to build an image  and i get this error
Packer v1.3.3
Host centos 7 using a jenkins task
{
        "variables": {
                "vmname": "{{env `VMNAME`}}",
                "iso_name": "{{env `ISO_NAME`}}",
                "iso_url": "{{env `ISO_URL`}}",
                "iso_checksum_type": "{{env `ISO_CHECKSUM_TYPE`}}",
                "iso_checksum_url": "{{env `ISO_CHECKSUM_URL`}}"
        },
        "builders": [
                {
                "type": "qemu",
                "iso_url": "{{user `iso_url`}}",
                "iso_checksum_type": "{{user `iso_checksum_type`}}",
                "iso_checksum_url": "{{user `iso_checksum_url`}}",
                "vm_name": "{{user `vmname`}}",
                "disk_size": 20480,
                "format": "qcow2",
                "headless": true,
                "qemuargs": [
                [ "-m", "2048M"]
                ],
                "boot_wait": "10s",
                "boot_command": [
                        "<esc><wait5>",
                        "<ommited>",
                        "<enter>"
                ],
                "communicator": "none",
                "shutdown_command": "shutdown -p",
                "shutdown_timeout": "40m",
                "output_directory": "{{user `vmname`}}"
                }
        ]
}

2019/01/28 18:32:35 packer: 2019/01/28 18:32:35 Running the provision hook
**2019/01/28 18:32:35 packer: panic: interface conversion: interface is nil, not packer.Communicator**
2019/01/28 18:32:35 packer:
2019/01/28 18:32:35 packer: goroutine 27 [running]:
2019/01/28 18:32:35 packer: github.com/hashicorp/packer/common.(*StepCleanupTempKeys).Run(0xc00009c608, 0x2901480, 0xc0002d3700, 0x28ff080, 0xc0003da2d0, 0x0)
2019/01/28 18:32:35 packer:     /Users/azr/go/src/github.com/hashicorp/packer/common/step_cleanup_temp_keys.go:22 +0x82
2019/01/28 18:32:35 packer: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc0002d36c0, 0x28ff080, 0xc0003da2d0)
2019/01/28 18:32:35 packer:     /Users/azr/go/src/github.com/hashicorp/packer/helper/multistep/basic_runner.go:72 +0x222
2019/01/28 18:32:35 packer: github.com/hashicorp/packer/builder/qemu.(*Builder).Run(0xc000114680, 0x2907340, 0xc000351d20, 0x28f4480, 0xc0002be1c0, 0x2901840, 0xc00009c600, 0x4bcd3c, 0x1ec2bc0, 0x1ec2bc0, ...)
2019/01/28 18:32:35 packer:     /Users/azr/go/src/github.com/hashicorp/packer/builder/qemu/builder.go:447 +0xc45
2019/01/28 18:32:35 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc000350c20, 0x1, 0xc0003060a0, 0x0, 0x0)
2019/01/28 18:32:35 packer:     /Users/azr/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:94 +0x1cd
2019/01/28 18:32:35 packer: reflect.Value.call(0xc000081ce0, 0xc00000c330, 0x13, 0x2616169, 0x4, 0xc0000bdf18, 0x3, 0x3, 0xc00007f7c0, 0xc0000d0900, ...)
2019/01/28 18:32:35 packer:     /usr/local/Cellar/go/1.11.2/libexec/src/reflect/value.go:447 +0x449
2019/01/28 18:32:35 packer: reflect.Value.Call(0xc000081ce0, 0xc00000c330, 0x13, 0xc000022f18, 0x3, 0x3, 0x1, 0x729b8e, 0x100010000)
2019/01/28 18:32:35 packer:     /usr/local/Cellar/go/1.11.2/libexec/src/reflect/value.go:308 +0xa4
2019/01/28 18:32:35 packer: net/rpc.(*service).call(0xc00007f780, 0xc0001a7130, 0xc000331f38, 0xc000331f40, 0xc0001e0b80, 0xc00000a500, 0x1f34d00, 0xc00030607c, 0x18a, 0x1ec2bc0, ...)
2019/01/28 18:32:35 packer:     /usr/local/Cellar/go/1.11.2/libexec/src/net/rpc/server.go:384 +0x14e
2019/01/28 18:32:35 packer: created by net/rpc.(*Server).ServeCodec
2019/01/28 18:32:35 packer:     /usr/local/Cellar/go/1.11.2/libexec/src/net/rpc/server.go:481 +0x47e
2019/01/28 18:32:35 [INFO] (telemetry) ending qemu
2019/01/28 18:32:35 ui error: Build 'qemu' errored: unexpected EOF
2019/01/28 18:32:35 Builds completed. Waiting on interrupt barrier...
2019/01/28 18:32:35 machine readable: error-count []string{"1"}
2019/01/28 18:32:35 ui error:
==> Some builds didn't complete successfully and had errors:
2019/01/28 18:32:35 machine readable: qemu,error []string{"unexpected EOF"}
2019/01/28 18:32:35 ui error: --> qemu: unexpected EOF
2019/01/28 18:32:35 ui:
==> Builds finished but no artifacts were created.
2019/01/28 18:32:35 [INFO] (telemetry) Finalizing.
2019/01/28 18:32:35 /usr/local/bin/packer: plugin process exited
2019/01/28 18:32:36 waiting for all plugin processes to complete...

**Comment by SwampDragons** [comment]
Interesting. Packer should fail gracefully rather than crashing here. 

If you supply the communicator does it work for you?
https://www.packer.io/docs/templates/communicator.html#ssh

**Comment by jorgelon** [comment]
if I choose ssh as communicator I dont get that error

**Comment by SwampDragons** [comment]
I think it should.

**Comment by anish** [comment]
I'm pretty sure you hit what I fixed here https://github.com/hashicorp/packer/pull/7095 @jorgelon , can you verify with 1.3.4 ?
