### ISSUE TITLE
Intermittent Packer Crash

### ISSUE THREAD

**Issue by ChulHul** [hashicorp/packer#7350]
- Packer version: 1.3.4
- Host platform: Azure
- Crash text: https://gist.github.com/ChulHul/8af8111a1e67c1d54588bcb7ea633f81

I keep hitting an intermittent crash that i can't reliably reproduce... Anyone has any ideas?

**Comment by SwampDragons** [comment]
My guess is this is a network hiccup, since WinRM is failing during an upload.

**Comment by SNikalaichyk** [comment]
I also occasionally experience the same crash, but in AWS.

```
2019/02/26 21:59:48 ui: ==> amazon-ebs: Waiting for WinRM to become available...
2019/02/26 21:59:53 packer: 2019/02/26 21:59:53 [INFO] Attempting WinRM connection...
2019/02/26 21:59:53 packer: 2019/02/26 21:59:53 [DEBUG] connecting to remote shell using WinRM
2019/02/26 21:59:54 packer: panic: runtime error: invalid memory address or nil pointer dereference
2019/02/26 21:59:54 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x679346]
2019/02/26 21:59:54 packer:
2019/02/26 21:59:54 packer: goroutine 292 [running]:
2019/02/26 21:59:54 packer: net/http.redirectBehavior(0x27cba03, 0x4, 0x0, 0xc000554200, 0x0, 0x0, 0x0)
2019/02/26 21:59:54 packer:     /usr/local/Cellar/go/1.11.4/libexec/src/net/http/client.go:422 +0x26
2019/02/26 21:59:54 packer: net/http.(*Client).do(0xc0003bac00, 0xc000554200, 0x0, 0x0, 0x0)
2019/02/26 21:59:54 packer:     /usr/local/Cellar/go/1.11.4/libexec/src/net/http/client.go:655 +0x320
2019/02/26 21:59:54 packer: net/http.(*Client).Do(0xc0003bac00, 0xc000554200, 0xd, 0xc00048d880, 0x20)
2019/02/26 21:59:54 packer:     /usr/local/Cellar/go/1.11.4/libexec/src/net/http/client.go:509 +0x35
2019/02/26 21:59:54 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.clientRequest.Post(0x2abeda0, 0xc0004f4060, 0xc000132100, 0xc0005500c0, 0x0, 0x0, 0x0, 0x0)
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/http.go:82 +0x2c2
2019/02/26 21:59:54 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.ClientNTLM.Post(0x2abeda0, 0xc0004f4060, 0xc000132100, 0xc0005500c0, 0xc0005500c0, 0xc000360090, 0x27da7b8, 0xd)
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/ntlm.go:22 +0x49
2019/02/26 21:59:54 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.(*Client).sendRequest(0xc000132100, 0xc0005500c0, 0xc0005500c0, 0xc0005500c0, 0xc0005ca420, 0x2e)
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/client.go:102 +0x43
2019/02/26 21:59:54 packer: github.com/hashicorp/packer/vendor/github.com/masterzen/winrm.(*Client).CreateShell(0xc000132100, 0x0, 0x0, 0x0)
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/vendor/github.com/masterzen/winrm/client.go:81 +0x99
2019/02/26 21:59:54 packer: github.com/hashicorp/packer/communicator/winrm.New(0xc0000aa1e0, 0xc0000aa1e0, 0x1, 0xd)
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/communicator/winrm/communicator.go:58 +0x180
2019/02/26 21:59:54 packer: github.com/hashicorp/packer/helper/communicator.(*StepConnectWinRM).waitForWinRM(0xc0004c4d80, 0x2ad7d80, 0xc0005a41b0, 0xc00004b140, 0x1, 0x0, 0x0, 0xc00008a720)
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/helper/communicator/step_connect_winrm.go:132 +0x318
2019/02/26 21:59:54 packer: github.com/hashicorp/packer/helper/communicator.(*StepConnectWinRM).Run.func1(0x2ae00e0, 0xc0003180e0, 0xc0004c4d80, 0x2ad7d80, 0xc0005a41b0, 0xc00004b140, 0xc000527e20, 0xc000527e30, 0xc0001e55e0)
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/helper/communicator/step_connect_winrm.go:46 +0x76
2019/02/26 21:59:54 packer: created by github.com/hashicorp/packer/helper/communicator.(*StepConnectWinRM).Run
2019/02/26 21:59:54 packer:     /Users/azr/go/src/github.com/hashicorp/packer/helper/communicator/step_connect_winrm.go:44 +0x1a1
2019/02/26 21:59:54 [INFO] (telemetry) ending amazon-ebs
2019/02/26 21:59:54 ui error: Build 'amazon-ebs' errored: unexpected EOF
2019/02/26 21:59:54 Builds completed. Waiting on interrupt barrier...
2019/02/26 21:59:54 machine readable: error-count []string{"1"}
2019/02/26 21:59:54 ui error:
==> Some builds didn't complete successfully and had errors:
2019/02/26 21:59:54 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2019/02/26 21:59:54 ui error: --> amazon-ebs: unexpected EOF
2019/02/26 21:59:54 ui:
==> Builds finished but no artifacts were created.
2019/02/26 21:59:54 [INFO] (telemetry) Finalizing.
2019/02/26 21:59:54 /usr/local/bin/packer: plugin process exited
2019/02/26 21:59:54 waiting for all plugin processes to complete...
2019/02/26 21:59:54 /usr/local/bin/packer: plugin process exited
```

**Comment by SwampDragons** [comment]
@ChulHul and @SNikalaichyk I think we've (finally) tracked down this bug. The patched build here should solve it https://circleci.com/gh/hashicorp/packer/21445#artifacts/containers/0; this comes from the PR linked above.
