### ISSUE TITLE
[tty] panic on termination

### ISSUE THREAD

**Issue by azr** [hashicorp/packer#7434]
Hello there, on rare occasions, packer crashed for me:  upon termination + resizing the term windows at the same time: `panic: send on closed channel`.

I opened a pr here https://github.com/mattn/go-tty/pull/15/ to fix it.

**Comment by azr** [comment]
It happening on windows too !
```
panic: send on closed channel

goroutine 1779 [running]:
github.com/hashicorp/packer/vendor/github.com/mattn/go-tty.(*TTY).readRune(0xc000305240, 0xc000000000, 0x0, 0x0)
	/Users/azr/go/src/github.com/hashicorp/packer/vendor/github.com/mattn/go-tty/tty_windows.go:209 +0xd33
github.com/hashicorp/packer/vendor/github.com/mattn/go-tty.(*TTY).readString(0xc000305240, 0x1, 0xc000326058, 0x30ce96d, 0x1, 0x0)
	/Users/azr/go/src/github.com/hashicorp/packer/vendor/github.com/mattn/go-tty/tty.go:60 +0x70
github.com/hashicorp/packer/vendor/github.com/mattn/go-tty.(*TTY).ReadString(0xc000305240, 0x0, 0x0, 0x0, 0x0)
	/Users/azr/go/src/github.com/hashicorp/packer/vendor/github.com/mattn/go-tty/tty.go:91 +0x95
github.com/hashicorp/packer/packer.(*BasicUi).Ask.func1(0xc0004262a0, 0xc000742600)
	/Users/azr/go/src/github.com/hashicorp/packer/packer/ui.go:212 +0x47
created by github.com/hashicorp/packer/packer.(*BasicUi).Ask
	/Users/azr/go/src/github.com/hashicorp/packer/packer/ui.go:211 +0x23f
```

**Comment by azr** [comment]
I opened a new fix in https://github.com/mattn/go-tty/pull/25
