### ISSUE TITLE
Powershell Provisoner unexpected EOF

### ISSUE THREAD

**Issue by mobee-pdufresne** [hashicorp/packer#7687]
Provisoning any powershell script returns an EOF error.

Packer OS: CentOS7
Packer Version 1.4.0

the powershell script is the following, though any powershell script seems to be causing an EOF
```
$invocation = (Get-Variable MyInvocation).Value
$directorypath = Split-Path $invocation.MyCommand.Path

Get-WindowsFeature | Where-Object -FilterScript { $_.Name -like '*Windows-Defender*' -or $_.Name -like '*SMB1*' -or $_.Name -like '*NET-WCF*' } | Remove-WindowsFeature
```

```
==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with powershell script: /local/packer/playbooks/windows/scripts/base_removefeatures.ps1
Build 'amazon-ebs' errored: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: unexpected EOF

==> Builds finished but no artifacts were created.
panic: runtime error: invalid memory address or nil pointer dereference
2019/05/24 14:52:22 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe91452]
2019/05/24 14:52:22 packer:
2019/05/24 14:52:22 packer: goroutine 1527 [running]:
2019/05/24 14:52:22 packer: github.com/hashicorp/packer/communicator/winrm.(*Communicator).Upload(0xc000627260, 0xc00058aca0, 0x17, 0x324d2e0, 0xc000       0e89c0, 0x0, 0x24e6720, 0x1)
2019/05/24 14:52:22 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/communicator/winrm/communicator.go:133 +0x242
2019/05/24 14:52:22 packer: github.com/hashicorp/packer/packer/rpc.(*CommunicatorServer).Upload(0xc00023dce0, 0xc0006c6880, 0xc00063f790, 0x0, 0x0)
2019/05/24 14:52:22 packer:     /Users/mmarsh/go/src/github.com/hashicorp/packer/packer/rpc/communicator.go:297 +0x148
2019/05/24 14:52:22 packer: reflect.Value.call(0xc0004bcc60, 0xc00000f0c0, 0x13, 0x2d81824, 0x4, 0xc000737f18, 0x3, 0x3, 0xc00072c840, 0x5, ...)
2019/05/24 14:52:22 packer:     /usr/local/go/src/reflect/value.go:447 +0x461
2019/05/24 14:52:22 packer: reflect.Value.Call(0xc0004bcc60, 0xc00000f0c0, 0x13, 0xc0005c1718, 0x3, 0x3, 0xc00066ca08, 0xc000074000, 0xc0005c1730)
2019/05/24 14:52:22 packer:     /usr/local/go/src/reflect/value.go:308 +0xa4
2019/05/24 14:52:22 packer: net/rpc.(*service).call(0xc000592440, 0xc000594550, 0xc000657750, 0xc000657760, 0xc0004f9080, 0xc0002345a0, 0x2472a60, 0x       c0006c6880, 0x16, 0x24e6720, ...)
2019/05/24 14:52:22 packer:     /usr/local/go/src/net/rpc/server.go:384 +0x14e
2019/05/24 14:52:22 packer: created by net/rpc.(*Server).ServeCodec
2019/05/24 14:52:22 packer:     /usr/local/go/src/net/rpc/server.go:481 +0x440
2019/05/24 14:52:22 [INFO] (telemetry) ending amazon-ebs
2019/05/24 14:52:22 ui error: Build 'amazon-ebs' errored: unexpected EOF
2019/05/24 14:52:22 Builds completed. Waiting on interrupt barrier...
2019/05/24 14:52:22 machine readable: error-count []string{"1"}
2019/05/24 14:52:22 ui error:
==> Some builds didn't complete successfully and had errors:
2019/05/24 14:52:22 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2019/05/24 14:52:22 ui error: --> amazon-ebs: unexpected EOF
2019/05/24 14:52:22 ui:
==> Builds finished but no artifacts were created.
2019/05/24 14:52:22 [INFO] (telemetry) Finalizing.
2019/05/24 14:52:22 /opt/packer/packer: plugin process exited
2019/05/24 14:52:22 packer: 2019/05/24 14:52:22 Retryable error: Error uploading script: unexpected EOF
2019/05/24 14:52:22 waiting for all plugin processes to complete...
2019/05/24 14:52:22 /opt/packer/packer: plugin process exited
```

provisioners chunk of file
```
  "provisioners": [
    {
      "type": "file",
      "source": "{{user `packer_path`}}/playbooks/windows/files/lgpo.exe",
      "destination": "c:\\Windows\\Temp\\deploy\\"
    },
    {
      "type": "file",
      "source": "{{user `packer_path`}}/playbooks/windows/policy/basepcidss3",
      "destination": "c:\\Windows\\Temp\\deploy\\"
    },
    {
      "type": "file",
      "source": "{{user `packer_path`}}/playbooks/windows/sysprep/base.xml",
      "destination": "C:\\ProgramData\\Amazon\\EC2-Windows\\Launch\\Sysprep\\Unattend.xml"
    },
    {
    "type": "file",
    "destination": "c:\\Windows\\Temp\\deploy\\",
    "source":"{{user `packer_path`}}/playbooks/windows/scripts/base_removefeatures.ps1"
    },
    {
    "type": "powershell",
    "remote_path": "c:\\Windows\\Temp\\deploy\\",
    "script":"{{user `packer_path`}}/playbooks/windows/scripts/base_removefeatures.ps1"
    }
```

**Comment by azr** [comment]
Hello @mobee-pdufresne thanks for reporting and sorry about the inconvenience, I think this could have been solved in [1.4.1](https://www.packer.io/downloads.html) that was recently released, could you please try this version to see if you still have the same issue ?

**Comment by mobee-pdufresne** [comment]
Hi there

same result with 1.4.1

 packer]$ packer --version
1.4.1

```

2019/05/24 15:53:52 ui: ==> amazon-ebs: Provisioning with powershell script: /local/packer/playbooks/windows/scripts/base_removefeatures.ps1
2019/05/24 15:53:52 packer: 2019/05/24 15:53:52 Opening /local/packer/playbooks/windows/scripts/base_removefeatures.ps1 for reading
2019/05/24 15:53:52 packer: 2019/05/24 15:53:52 Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5ce81244-3223-fe85-612a-54ab71937029.ps1
2019/05/24 15:53:52 packer: 2019/05/24 15:53:52 [INFO] 76 bytes written for 'uploadData'
2019/05/24 15:53:52 [INFO] 76 bytes written for 'uploadData'
2019/05/24 15:53:52 packer: 2019/05/24 15:53:52 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5ce81244-3223-fe85-612a-54ab71937029.ps1'
2019/05/24 15:53:55 packer: #< CLIXML
2019/05/24 15:54:00 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2019/05/24 15:54:00 packer: 2019/05/24 15:54:00 [INFO] 169 bytes written for 'uploadData'
2019/05/24 15:54:00 [INFO] 169 bytes written for 'uploadData'
2019/05/24 15:54:00 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>panic: runtime error: invalid memory address or nil pointer dereference
2019/05/24 15:54:00 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11cf9f2]
2019/05/24 15:54:00 packer:
2019/05/24 15:54:00 packer: goroutine 1601 [running]:
2019/05/24 15:54:00 packer: github.com/hashicorp/packer/communicator/winrm.(*Communicator).Upload(0xc000221d20, 0xc00023e180, 0x17, 0x3b83d80, 0xc0000f8000, 0x0, 0x2b6e940, 0x1)
2019/05/24 15:54:00 packer:     /Users/azr/go/src/github.com/hashicorp/packer/communicator/winrm/communicator.go:133 +0x242
2019/05/24 15:54:00 packer: github.com/hashicorp/packer/packer/rpc.(*CommunicatorServer).Upload(0xc00024b9a0, 0xc000495680, 0xc0002606c0, 0x0, 0x0)
2019/05/24 15:54:00 packer:     /Users/azr/go/src/github.com/hashicorp/packer/packer/rpc/communicator.go:297 +0x148
2019/05/24 15:54:00 packer: reflect.Value.call(0xc000585f80, 0xc00000f388, 0x13, 0x3641306, 0x4, 0xc000665f18, 0x3, 0x3, 0xc000668a00, 0x5, ...)
2019/05/24 15:54:00 packer:     /usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:447 +0x461
2019/05/24 15:54:00 packer: reflect.Value.Call(0xc000585f80, 0xc00000f388, 0x13, 0xc0004b7718, 0x3, 0x3, 0xc000052968, 0x0, 0xc0004b7730)
2019/05/24 15:54:00 packer:     /usr/local/Cellar/go/1.12.5/libexec/src/reflect/value.go:308 +0xa4
2019/05/24 15:54:00 packer: net/rpc.(*service).call(0xc000669a00, 0xc000682fa0, 0xc000053b70, 0xc000053b90, 0xc0005bc080, 0xc00024bd20, 0x2af59c0, 0xc000495680, 0x16, 0x2b6e940, ...)
2019/05/24 15:54:00 packer:     /usr/local/Cellar/go/1.12.5/libexec/src/net/rpc/server.go:384 +0x14e
2019/05/24 15:54:00 packer: created by net/rpc.(*Server).ServeCodec
2019/05/24 15:54:00 packer:     /usr/local/Cellar/go/1.12.5/libexec/src/net/rpc/server.go:481 +0x42b
2019/05/24 15:54:00 /opt/packer/packer: plugin process exited
2019/05/24 15:54:00 [INFO] (telemetry) ending amazon-ebs
2019/05/24 15:54:00 ui error: Build 'amazon-ebs' errored: unexpected EOF
2019/05/24 15:54:00 machine readable: error-count []string{"1"}
2019/05/24 15:54:00 ui error:
==> Some builds didn't complete successfully and had errors:
2019/05/24 15:54:00 machine readable: amazon-ebs,error []string{"unexpected EOF"}
2019/05/24 15:54:00 ui error: --> amazon-ebs: unexpected EOF
2019/05/24 15:54:00 ui:
==> Builds finished but no artifacts were created.

```

**Comment by azr** [comment]
Thanks for testing !

**Comment by mobee-pdufresne** [comment]
suggested workaround? I assume upload the file and do a shell "powershell.exe -file [path_of_script]" provision?

**Comment by azr** [comment]
I am not experienced in powershell/windows, will try to take some time and repro.

The first thing that I see from your buildfile is that the these two upload to the same file:
```
    {
    "type": "file",
    "destination": "c:\\Windows\\Temp\\deploy\\",
    "source":"{{user `packer_path`}}/playbooks/windows/scripts/base_removefeatures.ps1"
    },
    {
    "type": "powershell",
    "remote_path": "c:\\Windows\\Temp\\deploy\\",
    "script":"{{user `packer_path`}}/playbooks/windows/scripts/base_removefeatures.ps1"
    }
```
which should cause some issues.

**Comment by mobee-pdufresne** [comment]
Hi there

that was a copy/paste error from opening the issue, in the actual JSON, the file provisoner is not present in my current JSON

I meant more something like this to do the same steps that the powershell provisoner does, assuming double quotes is the correct way to past the command to the windows command prompt. 

```
#upload file
{
    "type": "file",
    "destination": "c:\\Windows\\Temp\\deploy\\",
    "source":"{{user `packer_path`}}/playbooks/windows/scripts/base_removefeatures.ps1"
},
#execute file
{
  "type": "windows-shell",
  "inline": ["cmd -c "powershell.exe -file c:\Windows\Temp\deploy\base_removefeatures.ps1" "]
}
```

**Comment by azr** [comment]
@mobee-pdufresne, try executing that scipt with the powershell provisioner instead, packer will upload your script and run it with special args that make it so that there will be more chance for it to pass.

see: https://www.packer.io/docs/provisioners/powershell.html#script

**Comment by mobee-pdufresne** [comment]
hi there

the steps you talk about the powershell provisonner, it seems the uploading it does it causes a null pointer reference somewhere

```
#success
2019/05/24 15:54:00 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2019/05/24 15:54:00 packer: 2019/05/24 15:54:00 [INFO] 169 bytes written for 'uploadData'
2019/05/24 15:54:00 [INFO] 169 bytes written for 'uploadData'
#fail 
2019/05/24 15:54:00 packer: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>panic: runtime error: invalid memory address or nil pointer dereference
2019/05/24 15:54:00 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11cf9f2]
2019/05/24 15:54:00 packer:
2019/05/24 15:54:00 packer: goroutine 1601 [running]:
2019/05/24 15:54:00 packer: github.com/hashicorp/packer/communicator/winrm.(*Communicator).Upload(0xc000221d20, 0xc00023e180, 0x17, 0x3b83d80, 0xc0000f8000, 0x0, 0x2b6e940, 0x1)
```

where as the 2 step upload works fine
```
    {
      "type": "file",
      "destination": "c:\\Windows\\Temp\\deploy\\",
      "source":"{{user `packer_path`}}/playbooks/windows/scripts/base_removefeatures.ps1"
    },
    {
      "type": "windows-shell",
      "inline": ["powershell.exe -file c:\\Windows\\Temp\\deploy\\base_removefeatures.ps1"]
    },
```

#output
```
base.xml 5.55 KiB / 5.55 KiB [==================================================================================================================] 100.00% 1s
==> amazon-ebs: Uploading /local/packer/playbooks/windows/scripts/base_removefeatures.ps1 => c:\Windows\Temp\deploy\
base_removefeatures.ps1 169 B / 169 B [=========================================================================================================] 100.00% 1s
==> amazon-ebs: Provisioning with windows-shell...
==> amazon-ebs: Provisioning with shell script: /tmp/windows-shell-provisioner486461706
    amazon-ebs:
    amazon-ebs: C:\Users\Administrator>powershell.exe -file c:\Windows\Temp\deploy\base_removefeatures.ps1
    amazon-ebs:
    amazon-ebs: Success Restart Needed Exit Code      Feature Result
    amazon-ebs: ------- -------------- ---------      --------------
    amazon-ebs: True    Yes            SuccessRest... {SMB 1.0/CIFS File Sharing Support, WCF Se...
    amazon-ebs: WARNING: You must restart this server to finish the removal process.
    amazon-ebs:
    amazon-ebs:
==> amazon-ebs: Restarting Machine
```

**Comment by SwampDragons** [comment]
Looks like the failure is happening inside the winrm upload call.

**Comment by mobee-pdufresne** [comment]
hi there

whats interesting, is that it seems to have uploaded, if the file size is correct between the 2 different methods

#powershell provsioner
2019/05/24 15:54:00 packer: 2019/05/24 15:54:00 [INFO] 169 bytes written for 'uploadData'
2019/05/24 15:54:00 [INFO] 169 bytes written for 'uploadData'

#file upload provisoner
==> amazon-ebs: Uploading /local/packer/playbooks/windows/scripts/base_removefeatures.ps1 => c:\Windows\Temp\deploy\
base_removefeatures.ps1 169 B / 169 B

**Comment by SwampDragons** [comment]
I can't reproduce; can you please share more details about your packer template?

**Comment by SwampDragons** [comment]
Nevermind, I'm able to reproduce the crash if I upload the file first.

**Comment by SwampDragons** [comment]
I'm still trying to find the root of the crash but you can work around this by making sure the remote_path includes the basename. For example: 

```
    {
    "type": "powershell",
    "remote_path": "c:\\Windows\\Temp\\deploy\\base_removefeatures.ps1",
    "script":"{{user `packer_path`}}/playbooks/windows/scripts/base_removefeatures.ps1"
    },
```

**Comment by mobee-pdufresne** [comment]
Hi there

This may have to do with what is being passed to be executed by the remote shell.

the example I gave is the remote path a directory path where as your example has the filename as part of the remote_path string. 

is the remote_path viewed as a directory path or the final output of whatever is to be executed? If it's interpreted as a script than it's not correct as it should be remote_script

**Comment by SwampDragons** [comment]
You're right. The problem was that you were using a directory path rather than a file path, and the powershell provisioner code expected a file path. I have written a patch (#7705) to fix this so that you may use directory paths and your original code will work as expected.

**Comment by mobee-pdufresne** [comment]
hi there

great, thanks.  I'll pull a binary version once the patch is rolled into one and will test, otherwise, I have a functional workaround.

**Comment by mobee-pdufresne** [comment]
Hi there

don't know if this is "closed" but I found another bug, a validation bug.

    {
    "type": "powershell",
    "remote_path": ":\\Windows\\Temp\\deploy\\base.ps1",
    "script":"{{user `packer_path`}}/playbooks/windows/scripts/base.ps1"
    },

if the path is malformed, packer still executes the JSON and when that particular Provisoner goes to execute, it hangs for a while then terminates in an unexpected EOF error.

So adding a windows path validation for anything windows provisoner would be good.
