### ISSUE TITLE
Packer crash using openstack builder

### ISSUE THREAD

**Issue by cacack** [hashicorp/packer#8197]
#### Overview of the Issue

Crash in 1.4.4 when using OpenStack builder.  Seems to be consistently crashing.  However, despite the message of not producing an artifact, there is a glance image that is created.

#### Reproduction Steps

Steps to reproduce this issue

### Packer version

```
> packer --version
1.4.4
```

### Simplified Packer Buildfile

```
{
  "variables": {
    "build_sha": ""
  },

  "builders": [
    {
      "type": "openstack",
      "ssh_username": "ubuntu",
      "ssh_pty": "true",
      "source_image_name": "dist-ubuntu-bionic-20190814-unscanned",
      "image_name": "bionic_test_{{user `build_sha`}}",
      "flavor": "VCPU2_R4_D10",
      "security_groups": ["default"],
      "networks": ["b08f4efa-62f7-4e37-861f-98e622916661"],
      "domain_name": "default",
      "metadata": {
        "os_distro": "ubuntu",
        "os_type": "linux",
        "os_version": "bionic"
      }
    }
  ],

  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sudo apt update && sudo apt install -y python"
      ]
    }
  ]
}
```

### Operating system and Environment details

Running packer on Fedora 30, interacting with OpenStack Newton

### Log Fragments and crash.log files

Relevant lines from the crash.log:
```
2019/10/04 18:13:33 packer: 2019/10/04 18:13:33 Waiting for image creation status: saving
2019/10/04 18:13:35 packer: 2019/10/04 18:13:35 Waiting for image creation status: saving
2019/10/04 18:13:37 packer: 2019/10/04 18:13:37 Waiting for image creation status: saving
2019/10/04 18:13:39 ui: ESC[1;32m==> openstack: Terminating the source server: 30b8285c-8436-4f7d-b09f-e8a3611fa97a ...ESC[0m
2019/10/04 18:13:40 packer: 2019/10/04 18:13:40 Waiting for state to become: [DELETED]
2019/10/04 18:13:40 packer: 2019/10/04 18:13:40 Waiting for state to become: [DELETED] currently SHUTOFF (0%)
2019/10/04 18:13:42 packer: 2019/10/04 18:13:42 [INFO] 404 on ServerStateRefresh, returning DELETED
2019/10/04 18:13:42 ui: ESC[1;32m==> openstack: Deleting temporary keypair: packer_5d978a9b-4b90-95df-5a9a-0d5ad7d3eb14 ...ESC[0m
2019/10/04 18:13:42 packer: panic: interface conversion: interface {} is nil, not string
2019/10/04 18:13:42 packer:
2019/10/04 18:13:42 packer: goroutine 131 [running]:
2019/10/04 18:13:42 packer: github.com/hashicorp/packer/builder/openstack.(*stepCreateImage).Run(0xc000052b46, 0x40dbb20, 0xc0003c7280, 0x40bc860, 0xc00053b080, 0x0)
2019/10/04 18:13:42 packer:     /Users/mmarsh/Projects/packer/builder/openstack/step_create_image.go:95 +0x102c
2019/10/04 18:13:42 packer: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc00053b110, 0x40dbb20, 0xc0003c7280, 0x40bc860, 0xc00053b080)
2019/10/04 18:13:42 packer:     /Users/mmarsh/Projects/packer/helper/multistep/basic_runner.go:67 +0x217
2019/10/04 18:13:42 packer: github.com/hashicorp/packer/builder/openstack.(*Builder).Run(0xc0002e7000, 0x40dbb20, 0xc0003c7280, 0x40f5160, 0xc000534c40, 0x406e700, 0xc000539120, 0x203000, 0x203000, 0x203000, ...)
2019/10/04 18:13:42 packer:     /Users/mmarsh/Projects/packer/builder/openstack/builder.go:162 +0xd22
2019/10/04 18:13:42 packer: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc0001c6c90, 0x1, 0xc0003c4520, 0x0, 0x0)
2019/10/04 18:13:42 packer:     /Users/mmarsh/Projects/packer/packer/rpc/builder.go:109 +0x236
2019/10/04 18:13:42 packer: reflect.Value.call(0xc0003b8720, 0xc0004ac020, 0x13, 0x3ab010f, 0x4, 0xc000602f18, 0x3, 0x3, 0x40528a, 0xc00029d4a0, ...)
2019/10/04 18:13:42 packer:     /usr/local/go/src/reflect/value.go:460 +0x5f6
2019/10/04 18:13:42 packer: reflect.Value.Call(0xc0003b8720, 0xc0004ac020, 0x13, 0xc0001cff18, 0x3, 0x3, 0xc00029d4a0, 0xc0001cfef8, 0x404d65)
2019/10/04 18:13:42 packer:     /usr/local/go/src/reflect/value.go:321 +0xb4
2019/10/04 18:13:42 packer: net/rpc.(*service).call(0xc0003c8640, 0xc00010cc80, 0xc0003ca370, 0xc0003ca380, 0xc0000de000, 0xc0002bc360, 0x2f625a0, 0xc0003c443c, 0x18a, 0x2eacde0, ...)
2019/10/04 18:13:42 packer:     /usr/local/go/src/net/rpc/server.go:377 +0x16f
2019/10/04 18:13:42 packer: created by net/rpc.(*Server).ServeCodec
2019/10/04 18:13:42 packer:     /usr/local/go/src/net/rpc/server.go:474 +0x42b
2019/10/04 18:13:42 /home/cac21/bin/packer: plugin process exited
2019/10/04 18:13:42 [INFO] (telemetry) ending openstack
2019/10/04 18:13:42 ui error: ESC[1;31mBuild 'openstack' errored: unexpected EOFESC[0m
2019/10/04 18:13:42 machine readable: error-count []string{"1"}
2019/10/04 18:13:42 ui error:
==> Some builds didn't complete successfully and had errors:
2019/10/04 18:13:42 machine readable: openstack,error []string{"unexpected EOF"}
2019/10/04 18:13:42 ui error: --> openstack: unexpected EOF
2019/10/04 18:13:42 ui:
==> Builds finished but no artifacts were created.
2019/10/04 18:13:42 [INFO] (telemetry) Finalizing.
2019/10/04 18:13:42 waiting for all plugin processes to complete...
```

**Comment by SwampDragons** [comment]
Thanks for opening! I believe this was fixed in #8176, and the patch should be part of the current nightly build -- https://github.com/hashicorp/packer/releases/tag/nightly

Sorry for this regression. If the bug still exists in the nightly build we can investigate further. I am going to leave this issue open for now so that other people who experience this bug can find it.

**Comment by cacack** [comment]
@SwampDragons That was it.  Using the current nightly (reporting as 1.5.0) works as expected!

**Comment by cacack** [comment]
Whoops, didn't the comment about leaving it open...
