### ISSUE TITLE
vagrant builder's vagrantfile template mixes source and output

### ISSUE THREAD

**Issue by andkononykhin** [hashicorp/packer#8245]
#### Overview of the Issue

A patch #7957 introduced new multi-machine vagrantfile template for vagrant builder:
- source box is taken by `source_path` but not by `box_name`
- for output machine it sets box name of the source box as a `vm.box` but also sets output package.box file as `vm.box_url` which seems confusing

It leads to:
- `vagrant up` itself during packer build tries to add box for source machine and it might fail the build if the source path is too long
- two boxes are actually added during the build: one by packer with `box_name` value and one by vagrant with `source_path` value as a name
- `vagrant up output` will bring up machine based on a source box instead of output one

### Packer version

1.4.4

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "type"                : "vagrant",
      "provider"            : "virtualbox",
      "source_path"         : "{{template_dir}}/../../bla/bla/bla/long-path/package.box",
      "add_force"           : true,
      "box_name"            : "centos7-base",
      "output_dir"          : "{{template_dir}}/../../.boxes/centos7-with-new-dir",
      "communicator"        : "ssh",
      ...
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "mkdir -p /tmp/new"
      ]
    }
  ]
}
```
### Generated Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.define "source", autostart: false do |source|
        source.vm.box = "... <skipped> .../../../bla/bla/bla/long-path/package.box"
  end
  config.vm.define "output" do |output|
        output.vm.box = "centos7-base"
        output.vm.box_url = "file://package.box"
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
```

### Operating system and Environment details

centos7

### Log Fragments and crash.log files

```
2019/10/18 14:46:51 packer: 2019/10/18 14:46:51 Calling Vagrant CLI: []string{"up", "source", "--provider=virtualbox"}
2019/10/18 14:46:55 packer: 2019/10/18 14:46:55 [vagrant driver] stdout: Bringing machine 'source' up with 'virtualbox' provider...
2019/10/18 14:46:55 packer: ==> source: Box '... <skipped> .../../../bla/bla/bla/long-path/package.box' could not be found. Attempting to find and install...
2019/10/18 14:46:55 packer:     source: Box Provider: virtualbox
2019/10/18 14:46:55 packer:     source: Box Version: >= 0
2019/10/18 14:46:55 packer: ==> source: Box file was not detected as metadata. Adding it directly...
2019/10/18 14:46:55 packer: ==> source: Adding box '... <skipped> .../../../bla/bla/bla/long-path/package.box' (v0) for provider: virtualbox
2019/10/18 14:46:55 packer:     source: Unpacking necessary files from: file://... <skipped> .../../../bla/bla/bla/long-path/package.box

2019/10/18 14:46:55 packer: 2019/10/18 14:46:55 [vagrant driver] stderr: /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': File name too long @ dir_s_mkdir -  ... <skipped> ...-VAGRANTSLASH-..-VAGRANTSLASH-..-VAGRANTSLASH-bla-VAGRANTSLASH-bla-VAGRANTSLASH-bla-VAGRANTSLASH-long-path-VAGRANTSLASH-package.box (Errno::ENAMETOOLONG)
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/fileutils.rb:206:in `reverse_each'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/fileutils.rb:206:in `block in mkdir_p'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/fileutils.rb:191:in `each'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/pathname.rb:576:in `mkpath'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:161:in `block (3 levels) in add'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:470:in `with_temp_dir'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:134:in `block (2 levels) in add'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:470:in `with_temp_dir'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:115:in `block in add'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:457:in `block in with_collection_lock'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:456:in `with_collection_lock'
2019/10/18 14:46:55 packer:     from /tmp/.mount_vagran5Uh4mU/usr/gembundle/gems/vagrant-2.2.5/lib/vagrant/box_collection.rb:104:in `add'
==> vagrant: destroying Vagrant box...
```

**Comment by SwampDragons** [comment]
Hi, thanks for reaching out. box_url is appropriate. From the [Vagrant docs](https://www.vagrantup.com/docs/vagrantfile/machine_settings.html#config-vm-box_url): 

> The URLs can also be local files by using the file:// scheme. For example: "file:///tmp/test.box".

But the other issue with the source.vm.box being the path to the box rather than the name of the source box is definitely valid. @milescrabill I went to revisit your particular Packer template that #7957 was supposed to be fixing, but I think you must have taken down the gist because I got a 404. I am wondering now if instead of adding the whole second template, we should have stuck to a single one and your template or the Packer code just wasn't properly adding the source box before calling `Vagrant up`. Do you think you can share again so I can find a solution that solves both use cases?
