### ISSUE TITLE
vsphere-clone builder crashes when using a distributed port group as network

### ISSUE THREAD

**Issue by andrewjkeith** [hashicorp/packer#8885]
#### Overview of the Issue

I am trying to use packer to build an ami based off a vsphere template that was also created by packer.
When using the vsphere-clone builder and specifying a network object that is a distributed port group in the clone configuration, the build crashes. If the network key is removed, the build will timeout at the wait for IP step, but it will not crash.

#### Reproduction Steps

Using the `vsphere-clone` builder, specify a network that is a distributed port group. Then run `packer build`.

### Packer version

`1.5.4`

### Simplified Packer Buildfile

```
{
  "variables": {
    "vsphere_user":     "{{env `TF_VAR_vsphere_user`}}",
    "vsphere_password": "{{env `TF_VAR_vsphere_password`}}"
  },
  "builders": [
    {
      "type": "vsphere-clone",

      "vcenter_server":      "alab",
      "username":            "{{user `vsphere_user`}}",
      "password":            "{{user `vsphere_password`}}",
      "insecure_connection": "true",

      "template": "rhel-7.7.0.1",
      "vm_name":  "rhel-clone-{{timestamp}}",
      "cluster":  "DEV",
      "host":     "vlab",
      "datastore": "DEVLAB_A_01",
      "network":   "VLAN_2362",

      "communicator": "ssh",
      "ssh_username": "root",
      "ssh_password": "xxxxx"
    }
  ]
}
```

### Operating system and Environment details

Vcenter: 6.7
ESXI: 6.5

### Log Fragments and crash.log files

<details>
  <Summary>crash.log</Summary>
```
  2020/03/11 17:26:53 [INFO] Packer version: 1.5.4 [go1.13.7 linux amd64]
2020/03/11 17:26:53 Checking 'PACKER_CONFIG' for a config file path
2020/03/11 17:26:53 'PACKER_CONFIG' not set; checking the default config file path
2020/03/11 17:26:53 Attempting to open config file: /export/home/user/.packerconfig
2020/03/11 17:26:53 [WARN] Config file doesn't exist: /export/home/user/.packerconfig
2020/03/11 17:26:53 Setting cache directory: /export/home/user/packer_cache
2020/03/11 17:26:53 Creating plugin client for path: /usr/local/bin/packer
2020/03/11 17:26:53 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-vsphere-clone"}
2020/03/11 17:26:53 Waiting for RPC address for: /usr/local/bin/packer
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: [INFO] Packer version: 1.5.4 [go1.13.7 linux amd64]
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: Checking 'PACKER_CONFIG' for a config file path
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: Attempting to open config file: /export/home/user/.packerconfig
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: [WARN] Config file doesn't exist: /export/home/user/.packerconfig
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: Setting cache directory: /export/home/user/packer_cache
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: args: []string{"packer-builder-vsphere-clone"}
2020/03/11 17:26:53 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin750801922
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: Plugin address: unix /tmp/packer-plugin750801922
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: Waiting for connection...
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: Serving a plugin connection...
2020/03/11 17:26:53 ui: vsphere-clone: output will be in this color.
2020/03/11 17:26:53 ui:
2020/03/11 17:26:53 Build debug mode: false
2020/03/11 17:26:53 Force build: false
2020/03/11 17:26:53 On error:
2020/03/11 17:26:53 Preparing build: vsphere-clone
2020/03/11 17:26:53 Waiting on builds to complete...
2020/03/11 17:26:53 Starting build run: vsphere-clone
2020/03/11 17:26:53 Running builder: vsphere-clone
2020/03/11 17:26:53 [INFO] (telemetry) Starting builder vsphere-clone
2020/03/11 17:26:53 ui: ==> vsphere-clone: Cloning VM...
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: panic: interface conversion: object.NetworkReference is *object.DistributedVirtualPortgroup, not *object.Network
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: goroutine 84 [running]:
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: github.com/hashicorp/packer/builder/vsphere/driver.(*Driver).FindNetwork(0xc0002992c0, 0xc000054b80, 0x13, 0xc000054c20, 0x16, 0xc0002b64f0)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /Users/mmarsh/Projects/packer/builder/vsphere/driver/network.go:27 +0x14a
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: github.com/hashicorp/packer/builder/vsphere/driver.(*VirtualMachine).Clone(0xc0003ebe50, 0x4945820, 0xc00043a500, 0xc0006d3710, 0x0, 0x0, 0xc0003ed6b0)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /Users/mmarsh/Projects/packer/builder/vsphere/driver/vm.go:242 +0x809
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: github.com/hashicorp/packer/builder/vsphere/clone.(*StepCloneVM).Run(0xc00052cd60, 0x4945820, 0xc00043a500, 0x4921aa0, 0xc0003ed5f0, 0x0)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /Users/mmarsh/Projects/packer/builder/vsphere/clone/step_clone.go:73 +0x345
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc0003ed740, 0x4945820, 0xc00043a500, 0x4921aa0, 0xc0003ed5f0)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /Users/mmarsh/Projects/packer/helper/multistep/basic_runner.go:67 +0x217
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: github.com/hashicorp/packer/builder/vsphere/clone.(*Builder).Run(0xc00061ad80, 0x4945820, 0xc00043a500, 0x4960920, 0xc0003ed590, 0x48cdd20, 0xc00052cd40, 0x203000, 0x203000, 0x203000, ...)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /Users/mmarsh/Projects/packer/builder/vsphere/clone/builder.go:86 +0x7ab
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc00009db00, 0x1, 0xc000057f50, 0x0, 0x0)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /Users/mmarsh/Projects/packer/packer/rpc/builder.go:117 +0x27c
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: reflect.Value.call(0xc0000929c0, 0xc0003ee130, 0x13, 0x422ae46, 0x4, 0xc0000d2f18, 0x3, 0x3, 0x0, 0x0, ...)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /usr/local/go/src/reflect/value.go:460 +0x5f6
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: reflect.Value.Call(0xc0000929c0, 0xc0003ee130, 0x13, 0xc000295f18, 0x3, 0x3, 0xd4, 0x5000000028, 0x9)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /usr/local/go/src/reflect/value.go:321 +0xb4
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: net/rpc.(*service).call(0xc00009db40, 0xc0000ecdc0, 0xc000564ed0, 0xc000564ee0, 0xc0000c2680, 0xc00000d7a0, 0x35c8840, 0xc000057f4c, 0x18a, 0x3503e20, ...)
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /usr/local/go/src/net/rpc/server.go:377 +0x16f
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin: created by net/rpc.(*Server).ServeCodec
2020/03/11 17:26:53 packer-builder-vsphere-clone plugin:        /usr/local/go/src/net/rpc/server.go:474 +0x42b
2020/03/11 17:26:53 [INFO] (telemetry) ending vsphere-clone
2020/03/11 17:26:53 ui error: Build 'vsphere-clone' errored: unexpected EOF
2020/03/11 17:26:53 machine readable: error-count []string{"1"}
2020/03/11 17:26:53 ui error:
==> Some builds didn't complete successfully and had errors:
2020/03/11 17:26:53 machine readable: vsphere-clone,error []string{"unexpected EOF"}
2020/03/11 17:26:53 ui error: --> vsphere-clone: unexpected EOF
2020/03/11 17:26:53 ui:
==> Builds finished but no artifacts were created.
2020/03/11 17:26:53 [INFO] (telemetry) Finalizing.
2020/03/11 17:26:53 /usr/local/bin/packer: plugin process exited
2020/03/11 17:26:53 waiting for all plugin processes to complete...
```
</details>

**Comment by jhawk28** [comment]
I think this is fixed in 1.5.5 by: https://github.com/hashicorp/packer/pull/8753

**Comment by andrewjkeith** [comment]
Oh yeah, looks like the same issue, apologies for the duplicate.

**Comment by azr** [comment]
Closing this issue then 🙂 thanks !
