### ISSUE TITLE
packer crash when using a json variables file

### ISSUE THREAD

**Issue by jhawk28** [hashicorp/packer#8910]
I'm not sure if its a configuration issue, but this is the crash that is occurring when I try to test changes from my vsphere_export_ovf branch. I built it using `go install`

```
$ packer build -on-error=ask -var-file variables.json ubuntu-18.04-amd64-docker.json
2020/03/19 00:06:27 [INFO] Packer version: 1.5.5-dev [go1.14 windows amd64]
2020/03/19 00:06:27 Checking 'PACKER_CONFIG' for a config file path
2020/03/19 00:06:27 'PACKER_CONFIG' not set; checking the default config file path
2020/03/19 00:06:27 Attempting to open config file: C:\Users\jhawk28\AppData\Roaming\packer.config
2020/03/19 00:06:27 [WARN] Config file doesn't exist: C:\Users\jhawk28\AppData\Roaming\packer.config
2020/03/19 00:06:27 Setting cache directory: C:\Users\jhawk28\repos\infrastructure\packer\packer_cache
cannot determine if process is in background: Process background check error: not implemented yet
2020/03/19 00:06:27 waiting for all plugin processes to complete...
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hashicorp/packer/command.(*Meta).Core(0xc00007c460, 0xc0004e20b0, 0xc0004e20b0, 0x0, 0x0)
        C:/Users/jhawk28/repos/packer/command/meta.go:54 +0x16a
github.com/hashicorp/packer/command.(*BuildCommand).GetBuilds(0xc00007c460, 0xc0000466c0, 0x1e, 0x6, 0x1, 0x7fffffffffffffff, 0xc00004e11a)
        C:/Users/jhawk28/repos/packer/command/build.go:155 +0x196
github.com/hashicorp/packer/command.(*BuildCommand).RunContext(0xc00007c460, 0x47a5700, 0xc000078200, 0xc000138020, 0x4, 0x6, 0xc000078200)
        C:/Users/jhawk28/repos/packer/command/build.go:185 +0xd1
github.com/hashicorp/packer/command.(*BuildCommand).Run(0xc00007c460, 0xc000138020, 0x4, 0x6, 0x0)
        C:/Users/jhawk28/repos/packer/command/build.go:55 +0x1d6
github.com/mitchellh/cli.(*CLI).Run(0xc0000cc3c0, 0xc0000cc3c0, 0x1, 0x1)
        C:/Users/jhawk28/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1e1
main.wrappedMain(0x0)
        C:/Users/jhawk28/repos/packer/main.go:238 +0x828
main.realMain(0x0)
        C:/Users/jhawk28/repos/packer/main.go:124 +0xec
main.main()
        C:/Users/jhawk28/repos/packer/main.go:34 +0x29
```

**Comment by jhawk28** [comment]
I just verified that it is also happening on master.

**Comment by jhawk28** [comment]
@azr I think its related to this commit: https://github.com/hashicorp/packer/commit/c8300b620a581f3c2fa9f505621f35d568f4a25a

**Comment by azr** [comment]
Hey @jhawk28 thanks for this ! I'm on it.

**Comment by azr** [comment]
#8914 contains a fix and another fix !
