### ISSUE TITLE
packer unable to ssh to Google Computes latest CentOS image

### ISSUE THREAD

**Issue by desolatorxxl** [hashicorp/packer#8924]
#### Overview of the Issue

Getting the below ssh error during the packer build process, similiar to #6341.

#### Reproduction Steps

```sh
packer build --force build.json
```
### Packer version

```
# packer version               
Packer v1.5.4
```

### Simplified Packer Buildfile

```json
{
  "builders": [
    {
      "image_name": "test_image_centos8",
      "type": "googlecompute",
      "account_file": "account.json",
      "project_id": "my-project",
      "source_image": "centos-8-v20200316",
      "metadata": { "enable-oslogin": "false" },
      "ssh_username": "packer",
      "ssh_timeout": "10m",
      "ssh_handshake_attempts": 20,
      "zone": "europe-west1-b"
    }
  ],
  "provisioners": [
      {
          "type": "shell",
          "inline": [ "sudo touch /boo" ]
      }
  ]
}
```

### Operating system and Environment details

Arch Linux 5.5.2-arch1-1

### Log Fragments and crash.log files

```
==> googlecompute: Checking image does not exist...                                                                                                                                            
==> googlecompute: Creating temporary SSH key for instance...                                                                                                                                  
==> googlecompute: Using image: centos-8-v20200316                                                                                                                                             
==> googlecompute: Creating instance...                                                                                                                                                        
    googlecompute: Loading zone: europe-west1-b                                                                                                                                                
    googlecompute: Loading machine type: n1-standard-1                                                                                                                                         
    googlecompute: Requesting instance creation...                                                                                                                                             
    googlecompute: Waiting for creation operation to complete...                                                                                                                               
2020/03/20 12:03:00 packer-builder-googlecompute plugin: Retryable error: retrying for state DONE, got RUNNING                                                                                 
2020/03/20 12:03:03 packer-builder-googlecompute plugin: Retryable error: retrying for state DONE, got RUNNING                                                                                 
    googlecompute: Instance has been created!                                                                                                                                                  
==> googlecompute: Waiting for the instance to become running...                                                                                                                               
    googlecompute: IP: 35.233.34.84                                                                                                                                                            
2020/03/20 12:03:05 packer-builder-googlecompute plugin: [INFO] Waiting for SSH, up to timeout: 10m0s                                                                                          
==> googlecompute: Using ssh communicator to connect: 35.233.34.84                                                                                                                             
==> googlecompute: Waiting for SSH to become available...                                                                                                                                      
2020/03/20 12:03:20 packer-builder-googlecompute plugin: [DEBUG] TCP connection to SSH ip/port failed: dial tcp 35.233.34.84:22: i/o timeout                                                   
2020/03/20 12:03:25 packer-builder-googlecompute plugin: [INFO] Attempting SSH connection to 35.233.34.84:22...                                                                                
2020/03/20 12:03:25 packer-builder-googlecompute plugin: [DEBUG] reconnecting to TCP connection for SSH                                                                                        
2020/03/20 12:03:25 packer-builder-googlecompute plugin: [DEBUG] handshaking with SSH                                                                                                          
2020/03/20 12:03:26 packer-builder-googlecompute plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported method
s remain                                                                                                                                                                                       
2020/03/20 12:03:26 packer-builder-googlecompute plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2020/03/20 12:03:33 packer-builder-googlecompute plugin: [INFO] Attempting SSH connection to 35.233.34.84:22...
2020/03/20 12:03:33 packer-builder-googlecompute plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/03/20 12:03:33 packer-builder-googlecompute plugin: [DEBUG] handshaking with SSH
2020/03/20 12:03:33 packer-builder-googlecompute plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported method
s remain
2020/03/20 12:03:33 packer-builder-googlecompute plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2020/03/20 12:03:40 packer-builder-googlecompute plugin: [INFO] Attempting SSH connection to 35.233.34.84:22...
2020/03/20 12:03:40 packer-builder-googlecompute plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/03/20 12:03:40 packer-builder-googlecompute plugin: [DEBUG] handshaking with SSH
2020/03/20 12:03:40 packer-builder-googlecompute plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported method
s remain
2020/03/20 12:03:40 packer-builder-googlecompute plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
2020/03/20 12:03:47 packer-builder-googlecompute plugin: [INFO] Attempting SSH connection to 35.233.34.84:22...
2020/03/20 12:03:47 packer-builder-googlecompute plugin: [DEBUG] reconnecting to TCP connection for SSH
2020/03/20 12:03:47 packer-builder-googlecompute plugin: [DEBUG] handshaking with SSH
2020/03/20 12:03:47 packer-builder-googlecompute plugin: [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported method
s remain
...
2020/03/20 12:04:32 packer-builder-googlecompute plugin: [DEBUG] Detected authentication error. Increasing handshake attempts.
==> googlecompute: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to doubl
e-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
==> googlecompute: Deleting instance...
...
```

Please note that SSH into a VM instance created with the same image manually works just fine.
Also using the second latest image `centos-8-v20200309` with packer works fine aswell.

Any guidance would be appreciated.

**Comment by SwampDragons** [comment]
thanks for opening this issue. This sounds like something may have changed on the google side of things, if the other images are still working. I'll see if I can check googlecompute update notes.

**Comment by desolatorxxl** [comment]
I guess I found the cause of the authentication failure.
The Google guest agent can't handle the "sshKeys" instance metadata that packer sets anymore. It fails quite ungracefully though:

```
# gcloud compute instances get-serial-port-output packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 | grep -i "guest.*agent"
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 GCEGuestAgent[2966]: 2020-03-23T21:34:26.7863Z GCEGuestAgent Info: GCE Agent Started (version 20200220.00)
[   21.443781] google_guest_agent[2966]: panic: runtime error: index out of range
[   21.514748] google_guest_agent[2966]: goroutine 45 [running]:
[   21.514800] google_guest_agent[2966]: main.removeExpiredKeys(0xc0002a04a0, 0x2, 0x2, 0x0, 0x0, 0x0)
[   21.514846] google_guest_agent[2966]:        /usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:303 +0x435
[   21.514884] google_guest_agent[2966]: main.(*accountsMgr).set(0xf08208, 0xa0bd01, 0x5)
[   21.514919] google_guest_agent[2966]:        /usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:113 +0x1d1
[   21.514957] google_guest_agent[2966]: main.runUpdate.func1(0xc0002a7b50, 0xad2ec0, 0xf08208)
[   21.514993] google_guest_agent[2966]:        /usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:116 +0xa0
[   21.515029] google_guest_agent[2966]: created by main.runUpdate
[   21.515064] google_guest_agent[2966]:        /usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:111 +0x24d
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: panic: runtime error: index out of range
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: goroutine 45 [running]:
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: main.removeExpiredKeys(0xc0002a04a0, 0x2, 0x2, 0x0, 0x0, 0x0)
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:303 +0x435
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: main.(*accountsMgr).set(0xf08208, 0xa0bd01, 0x5)
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/non_windows_accounts.go:113 +0x1d1
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: main.runUpdate.func1(0xc0002a7b50, 0xad2ec0, 0xf08208)
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:116 +0xa0
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: created by main.runUpdate
Mar 23 21:34:26 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 google_guest_agent[2966]: #011/usr/src/redhat/BUILD/google-guest-agent-20200220.00/google_guest_agent/main.go:111 +0x24d
Mar 23 21:34:27 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 systemd[1]: google-guest-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 23 21:34:27 packer-5e792b41-6814-ccb0-dfd1-6ca9de7bb1d9 systemd[1]: google-guest-agent.service: Failed with result 'exit-code'.
```
Replacing "sshKeys" with "ssh-keys" + rebooting + retrying the failed step while running with `-on-error=ask` fixed the issue temporarily.

I extended the changes in https://github.com/hashicorp/packer/pull/6445 a bit further and was able to fix it that way, but in a more persistent fashion.
This might be a sign that support for the "sshKeys" metadata field will end sooner rather than later, but right now it looks more like a bug to me.

**Comment by SwampDragons** [comment]
wonderful find -- would you be interested in cleaning up #6445 and creating a new PR?
