### ISSUE TITLE
packer fails with "netpoll: break fd ready for something unexpected"

### ISSUE THREAD

**Issue by trombik** [hashicorp/packer#9032]
#### Overview of the Issue

packer fails with "netpoll: break fd ready for something unexpected".

I found related issue [runtime: fatal error polling some file descriptors on macOS Mojave](https://github.com/golang/go/issues/37726) in go repo, and a fix ([don't call os.NewFile on unknown FDs #24562](https://github.com/hashicorp/terraform/pull/24562/commits/cd65b28da051174a13ac76e54b7bb95d3051255c) in terraform). also, other FreeBSD user reported [an issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244931).

#### Reproduction Steps

Run `packer --version`

### Packer version

1.5.1, [package from FreeBSD ports](https://www.freshports.org/sysutils/packer/).

### Simplified Packer Buildfile

N/A

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

```
> uname -msr
FreeBSD 13.0-CURRENT amd64
```

```
> go version 
go version go1.14.1 freebsd/amd64
```

### Log Fragments and crash.log files

```
> packer --version
runtime: netpoll: break fd ready for -2
fatal error: runtime: netpoll: break fd ready for something unexpected

runtime stack:
runtime.throw(0x3efc1bf, 0x39)
	/usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.netpoll(0xffffffffffffffff, 0x1)
	/usr/local/go/src/runtime/netpoll_kqueue.go:140 +0x30a
runtime.findrunnable(0xc000061000, 0x0)
	/usr/local/go/src/runtime/proc.go:2323 +0x72b
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2520 +0x2fc
runtime.goexit0(0xc000001c80)
	/usr/local/go/src/runtime/proc.go:2849 +0x1d6
runtime.mcall(0x200000)
	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive, locked to thread]:
text/template/parse.(*lexer).nextItem(...)
	/usr/local/go/src/text/template/parse/lex.go:195
text/template/parse.(*Tree).peek(...)
	/usr/local/go/src/text/template/parse/parse.go:95
text/template/parse.(*Tree).parse(0xc0000d6300)
	/usr/local/go/src/text/template/parse/parse.go:272 +0xb33
text/template/parse.(*Tree).Parse(0xc0000d6300, 0x3f2aedc, 0x172, 0x0, 0x0, 0x0, 0x0, 0xc000476930, 0xc0003279c0, 0x2, ...)
	/usr/local/go/src/text/template/parse/parse.go:225 +0x21c
text/template/parse.Parse(0x3e48beb, 0x9, 0x3f2aedc, 0x172, 0x0, 0x0, 0x0, 0x0, 0xc0003279c0, 0x2, ...)
	/usr/local/go/src/text/template/parse/parse.go:55 +0x115
text/template.(*Template).Parse(0xc000279200, 0x3f2aedc, 0x172, 0xc000476750, 0xc000476780, 0xc0004767b0)
	/usr/local/go/src/text/template/template.go:201 +0x111
html/template.(*Template).Parse(0xc000476900, 0x3f2aedc, 0x172, 0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:189 +0xa6
net/rpc.init()
	/usr/local/go/src/net/rpc/debug.go:39 +0x9b

goroutine 8 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00009f450)
	/wrkdirs/usr/ports/sysutils/packer/work/packer-1.5.1/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/wrkdirs/usr/ports/sysutils/packer/work/packer-1.5.1/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 9 [runnable]:
text/template/parse.(*lexer).run(0xc000470900)
	/usr/local/go/src/text/template/parse/lex.go:228
created by text/template/parse.lex
	/usr/local/go/src/text/template/parse/lex.go:223 +0x190
```

**Comment by trombik** [comment]
see also https://github.com/hashicorp/terraform/issues/24287

**Comment by nywilken** [comment]
This is good to now. Thanks for the Terraform issue references. We’ll take a look when we get a chance.

**Comment by SwampDragons** [comment]
Hi, thanks for opening -- I've ported Terraform's solution over here. PR is: https://github.com/hashicorp/packer/pull/9037 

That should work from you if you build from source.  Please let me know if the issue shows up again.

**Comment by trombik** [comment]
built a image. it worked. thanks.
