### ISSUE TITLE
amazon-ebssurrogate crash - Packer v1.6.0-dev (9c37d2072)

### ISSUE THREAD

**Issue by DanHam** [hashicorp/packer#9203]
### Overview of the Issue

Packer crashes at the final stages of an amazon-ebssurrogate build. 

From the logs, this looks to have been caused by the merge of #9082. Reverting the merge of #9082 fixes the issue and the build completes succesfully.

Ping @nywilken 

#### Reproduction Steps

Run an amazon-ebssurrogate build with the latest dev release of Packer.

### Packer version

Packer v1.6.0-dev (9c37d2072)

### Operating system and Environment details

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G4032

### Log Fragments and crash.log files

Log output in Gist: [HERE](https://gist.github.com/DanHam/e3f7f8041facfd15f593a66f653fe983) 

Just the crash info from the logs below:

```
2020/05/10 12:46:21 packer-provisioner-shell plugin: [INFO] RPC client: Communicator ended with: 0
2020/05/10 12:46:21 [INFO] (telemetry) ending shell
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: panic: runtime error: invalid memory address or nil pointer dereference
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53adf62]
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: goroutine 36 [running]:
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: github.com/hashicorp/packer/builder/amazon/common.(*StepCreateSSMTunnel).Cleanup(0xc00052e1e0, 0x86625c0, 0xc0002473b0)
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /Users/dan/working/go/src/github.com/hashicorp/packer/builder/amazon/common/step_create_ssm_tunnel.go:95 +0xf2
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc000247530, 0x8687b40, 0xc000896c40, 0x86625c0, 0xc0002473b0)
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /Users/dan/working/go/src/github.com/hashicorp/packer/helper/multistep/basic_runner.go:79 +0x2c6
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: github.com/hashicorp/packer/builder/amazon/ebssurrogate.(*Builder).Run(0xc00027d800, 0x8687b40, 0xc000896c40, 0x86a1960, 0xc000246e70, 0x8613320, 0xc00000f2c0, 0x0, 0x0, 0xc000092bd0, ...)
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /Users/dan/working/go/src/github.com/hashicorp/packer/builder/amazon/ebssurrogate/builder.go:364 +0x1ad4
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc0001d3b40, 0x1, 0xc0001b65f0, 0x0, 0x0)
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /Users/dan/working/go/src/github.com/hashicorp/packer/packer/rpc/builder.go:117 +0x1bd
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: reflect.Value.call(0xc0001b4c60, 0xc000010108, 0x13, 0x7f0b098, 0x4, 0xc000092f08, 0x3, 0x3, 0x8032740, 0xc00006d800, ...)
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /opt/local/lib/go/src/reflect/value.go:460 +0x8ab
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: reflect.Value.Call(0xc0001b4c60, 0xc000010108, 0x13, 0xc00051b708, 0x3, 0x3, 0xc00088ee38, 0xc0008807d8, 0x405f9c0)
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /opt/local/lib/go/src/reflect/value.go:321 +0xb4
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: net/rpc.(*service).call(0xc0001d3bc0, 0xc00018edc0, 0xc0001b6c48, 0xc0001b6c50, 0xc00050e380, 0xc0001aba00, 0x722f100, 0xc0001b624c, 0x18a, 0x715f280, ...)
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /opt/local/lib/go/src/net/rpc/server.go:377 +0x17f
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin: created by net/rpc.(*Server).ServeCodec
2020/05/10 12:48:10 packer-builder-amazon-ebssurrogate plugin:  /opt/local/lib/go/src/net/rpc/server.go:474 +0x42b
2020/05/10 12:48:10 /Users/dan/working/go/bin/packer: plugin process exited
2020/05/10 12:48:10 [INFO] (telemetry) ending amazon-ebssurrogate
2020/05/10 12:48:10 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/05/10 12:48:10 machine readable: amazon-ebssurrogate,error []string{"unexpected EOF"}
==> Builds finished but no artifacts were created.
2020/05/10 12:48:10 [INFO] (telemetry) Finalizing.
2020/05/10 12:48:10 waiting for all plugin processes to complete...
2020/05/10 12:48:10 /Users/dan/working/go/bin/packer: plugin process exited
2020/05/10 12:48:10 /Users/dan/working/go/bin/packer: plugin process exited
2020/05/10 12:48:10 /Users/dan/working/go/bin/packer: plugin process exited
```

**Comment by nywilken** [comment]
Hi @DanHam slight oversight :facepalm: I will get this squared away asap! Thanks.
