### ISSUE TITLE
Azure-arm: packer crash with HCL2

### ISSUE THREAD

**Issue by jmservianri** [hashicorp/packer#9984]
#### Overview of the Issue

At our company, we are updating all json files to HCL2. We have Azure and AWS builders, in aws it works fine but in azure-arm we have next error.
```
2020/09/24 09:32:12 packer.exe plugin: panic: assignment to entry in nil map
```

### Packer version

Packer version: 1.6.2 [go1.13.15 windows amd64]

### Simplified Packer Buildfile

We attach only azure-arm sources, without variable definition.

<details>
  <summary>sources.pkr.hcl</summary>

```
source "azure-arm" "centos7"{
    client_id = var.azure_spn.client_id
    client_secret = var.azure_spn.client_secret
    subscription_id = var.azure_spn.subscription_id
    tenant_id = var.azure_spn.tenant_id
    
    managed_image_name = var.name
    managed_image_resource_group_name = var.rg

    ssh_username= var.ssh_user
    ssh_password= var.ssh_pass

    build_resource_group_name = var.rg

    os_type = "Linux"
    image_publisher = "OpenLogic"
    image_offer = "CentOs"
    image_sku = "7.7"
    image_version = "latest"

    disk_additional_size = ["300"]


    shared_image_gallery_destination {
        gallery_name        = var.image_gallery.gallery_name
        image_name          = var.image_gallery.image_name
        image_version       = var.image_gallery.image_version
        replication_regions = var.image_gallery.replication_regions
        resource_group      = var.image_gallery.resource_group
    }
    shared_image_gallery_timeout = "2h5m2s"

    ssh_pty                      = "true"

    vm_size                      = var.instance_type_azure
      
    dynamic "azure_tag"{
        for_each = var.tags_resource
        
        content{
            name = azure_tag.key
            value = azure_tag.value
        }
    }

    azure_tag {
        name = "architecture"
        value = var.architecture
    }

}
```
</details>

</details>

<details>
  <summary>build.pkr.hcl</summary>

```
build {
    name ="azure"

    sources = [
        "source.azure-arm.centos7"
    ]
}
```
</details>

### Operating system and Environment details

We run the build in Ubuntu and Microsoft Windows 10 with same result.

### Log Fragments and crash.log files

<details>
 <summary>crash.log</summary>

```
2020/09/24 09:32:08 [INFO] Packer version: 1.6.2 [go1.13.15 windows amd64]
2020/09/24 09:32:08 Checking 'PACKER_CONFIG' for a config file path
2020/09/24 09:32:08 'PACKER_CONFIG' not set; checking the default config file path
2020/09/24 09:32:08 Attempting to open config file: C:\Users\jservian\packer.config
2020/09/24 09:32:08 [WARN] Config file doesn't exist: C:\Users\jservian\packer.config
2020/09/24 09:32:08 Setting cache directory: C:\Users\jservian\OneDrive - KPMG\Documentos\PROYECTOS\Packer\GoldenImage_Centos\packer_cache
cannot determine if process is in background: Process background check error: not implemented yet
2020/09/24 09:32:08 Creating plugin client for path: C:\Users\jservian\Programs\Packer\packer.exe
2020/09/24 09:32:08 Starting plugin: C:\Users\jservian\Programs\Packer\packer.exe []string{"C:\\Users\\jservian\\Programs\\Packer\\packer.exe", "plugin", "packer-builder-azure-arm"}
2020/09/24 09:32:08 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/packer?arch=amd64&os=windows&signature=43542fb7-f1f8-60c8-11ff-47b38f88aa9b&version=1.6.2: read tcp 10.181.164.222:53199->204.236.226.251:443: wsarecv: An existing connection was forcibly closed by the remote host.
2020/09/24 09:32:11 Waiting for RPC address for: C:\Users\jservian\Programs\Packer\packer.exe
2020/09/24 09:32:12 packer.exe plugin: [INFO] Packer version: 1.6.2 [go1.13.15 windows amd64]
2020/09/24 09:32:12 packer.exe plugin: Checking 'PACKER_CONFIG' for a config file path
2020/09/24 09:32:12 packer.exe plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/09/24 09:32:12 packer.exe plugin: Attempting to open config file: C:\Users\jservian\packer.config
2020/09/24 09:32:12 packer.exe plugin: [WARN] Config file doesn't exist: C:\Users\jservian\packer.config
2020/09/24 09:32:12 packer.exe plugin: Setting cache directory: C:\Users\jservian\OneDrive - KPMG\Documentos\PROYECTOS\Packer\GoldenImage_Centos\packer_cache
2020/09/24 09:32:12 packer.exe plugin: args: []string{"packer-builder-azure-arm"}
2020/09/24 09:32:12 packer.exe plugin: Plugin port range: [10000,25000]
2020/09/24 09:32:12 Received tcp RPC address for C:\Users\jservian\Programs\Packer\packer.exe: addr is 127.0.0.1:10000
2020/09/24 09:32:12 packer.exe plugin: Plugin address: tcp 127.0.0.1:10000
2020/09/24 09:32:12 packer.exe plugin: Waiting for connection...
2020/09/24 09:32:12 packer.exe plugin: Serving a plugin connection...
2020/09/24 09:32:12 packer.exe plugin: panic: assignment to entry in nil map
2020/09/24 09:32:12 packer.exe plugin: 
2020/09/24 09:32:12 packer.exe plugin: goroutine 14 [running]:
2020/09/24 09:32:12 packer.exe plugin: github.com/hashicorp/packer/builder/azure/arm.(*Config).Prepare(0xc000fbbb00, 0xc000ad12c0, 0x2, 0x2, 0xc000b90180, 0x0, 0x0, 0x10, 0x1)
2020/09/24 09:32:12 packer.exe plugin: 	/home/circleci/project/packer/builder/azure/arm/config.go:567 +0x23e
2020/09/24 09:32:12 packer.exe plugin: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Prepare(0xc000fbbb00, 0xc000ad12c0, 0x2, 0x2, 0x2, 0x2, 0x0, 0x0, 0x10, 0x20, ...)
2020/09/24 09:32:12 packer.exe plugin: 	/home/circleci/project/packer/builder/azure/arm/builder.go:41 +0x62
2020/09/24 09:32:12 packer.exe plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Prepare(0xc00007c500, 0xc000ad1280, 0xc00050d680, 0x0, 0x0)
2020/09/24 09:32:12 packer.exe plugin: 	/home/circleci/project/packer/packer/rpc/builder.go:97 +0xa7
2020/09/24 09:32:12 packer.exe plugin: reflect.Value.call(0xc000118c00, 0xc000ff88a0, 0x13, 0x4bc385a, 0x4, 0xc0005bbf18, 0x3, 0x3, 0x40587c, 0x433153, ...)
2020/09/24 09:32:12 packer.exe plugin: 	/usr/local/go/src/reflect/value.go:460 +0x5fd
2020/09/24 09:32:12 packer.exe plugin: reflect.Value.Call(0xc000118c00, 0xc000ff88a0, 0x13, 0xc0005bbf18, 0x3, 0x3, 0xc0003130e0, 0xc000313140, 0xc0005bbf98)
2020/09/24 09:32:12 packer.exe plugin: 	/usr/local/go/src/reflect/value.go:321 +0xbb
2020/09/24 09:32:12 packer.exe plugin: net/rpc.(*service).call(0xc00007c540, 0xc00010f1d0, 0xc000482150, 0xc000482160, 0xc000324980, 0xc000004de0, 0x3bd7400, 0xc000ad1280, 0x16, 0x3bd7440, ...)
2020/09/24 09:32:12 packer.exe plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x176
2020/09/24 09:32:12 packer.exe plugin: created by net/rpc.(*Server).ServeCodec
2020/09/24 09:32:12 packer.exe plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x432
2020/09/24 09:32:12 ui error: Error: unexpected EOF

  on sources.pkr.hcl line 56:
  (source code not available)

2020/09/24 09:32:12 Build debug mode: false
2020/09/24 09:32:12 Force build: false
2020/09/24 09:32:12 On error: 
2020/09/24 09:32:12 Waiting on builds to complete...
2020/09/24 09:32:12 ui: 
==> Wait completed after 0 seconds
2020/09/24 09:32:12 ui: 
==> Builds finished but no artifacts were created.
2020/09/24 09:32:12 [INFO] (telemetry) Finalizing.
2020/09/24 09:32:12 C:\Users\jservian\Programs\Packer\packer.exe: plugin process exited
2020/09/24 09:32:12 [WARN] (telemetry) Error finalizing report. This is safe to ignore. Post https://checkpoint-api.hashicorp.com/v1/telemetry/packer: read tcp 10.181.164.222:53204->204.236.226.251:443: wsarecv: An existing connection was forcibly closed by the remote host.
2020/09/24 09:32:12 waiting for all plugin processes to complete...
```

**Comment by sylviamoss** [comment]
Hey there, thanks for reporting! We will fix this for the next release.

**Comment by azr** [comment]
Hey @jmservianri, here's a fix : https://app.circleci.com/pipelines/github/hashicorp/packer/7299/workflows/a7440529-6e0d-4e3f-856d-ee587efc9ae8/jobs/83034/artifacts, this binary should unblock you; it's probably going to be in the next release
